### ISSUE TITLE
[Priest][Spell] Mind Flay

### ISSUE THREAD

**Issue by Stillkiller18** [GameFreedomGG/Sindragosa#101]
Hello, I would like to let you guys know Mind Flay when used is keeping me in combat an additional 3-5 seconds after every fight. That might not sound terrible but while leveling with my friend its very noticeable that hes able to mount maybe 3-5 seconds earlier than me and leaves me in the dust. Not to mention not being able to drink for that extra time not only left me OOM most of the time but is also not ideal for dungeon/raid groups. I've found it only affects the priest and happens if Mind Flay kills the target or not. Just using the spell is enough to make it take that additional time to get out of combat.

**Comment by scrublama** [comment]
ngl this was so painful in the leveling race always behind in mounting/drinking

**Comment by Godmatik** [comment]
Confirmed, VERY annoying
