### ISSUE TITLE
talent BM hunter "kindred spirit" not working 100%

### ISSUE THREAD

**Issue by blackfruitea** [GameFreedomGG/Sindragosa#102]
pls fix talent kindred spirit BM hunter, coz it's not work correctly, it suppose to be increase dmg pet + movement speed, but the buff show only movement speed, dmg pet increase doesn't show :
- i try positif thinking and w8, maybe it work but doesn't show in buff, so i lvl up talent skill till 5, and see the diffrent, i even 2x reset talent to really see if there is diffrent or not, but it is not show and it is not work the dmg pet increse

pls GM brothers fix  this, i even open my 2 account in diff server to see if im wrong(warmane and chromie), and yeah, it should show 2 buff, dmg pet increase and movement speed

**Comment by Soufly** [comment]
Without proofs,just dont bother... Your report should be not based on ''guessing'' :).
