### ISSUE TITLE
Quest: Iron Rune Constructs and You: The Bluff bug

### ISSUE THREAD

**Issue by pstefanuca** [GameFreedomGG/Sindragosa#104]
When you sit on the carpet nothing happens.
Quest description: https://wotlk-twinhead.twinstar.cz/?quest=11491
This is how it should work: https://www.youtube.com/watch?v=w84B28E_r_o

**Comment by MrTide** [comment]
Everything seems in order
I got the quest and clicked on the work bench got the construct 
![image](https://user-images.githubusercontent.com/36106057/149627171-a3f33d54-2a75-476f-9b3a-f8b27dd4eafb.png)
then went on the rug and pressed 1 and it worked
![image](https://user-images.githubusercontent.com/36106057/149627190-3e528aa5-6604-44e5-bbe6-4f2b474da2ee.png)
