### ISSUE TITLE
[Quest][NPC] Betrayal - "Big guys"

### ISSUE THREAD

**Issue by fozgate123** [GameFreedomGG/Sindragosa#108]
A short while after you mindcontrol the big guys they despawn and when trying to capture a new one they all despawn

**Comment by MrTide** [comment]
Can confirm there are a lot of issues with this quest. there are two of these npcs when you get up there 
![image](https://user-images.githubusercontent.com/36106057/150142731-21eeb442-e013-489f-9ca1-2aa3dba79d56.png)
and when you try to dominate one of the creatures which allows you to fight him they despawn after short while and you can't dominate another one and you need to restart the quest sometimes restart wont happen either 
I recommend rewriting the whole quest.

**Comment by UltraNix** [comment]
Fixed.
