### ISSUE TITLE
Saronite ore prospecting incorret drops

### ISSUE THREAD

**Issue by Luroxxar** [GameFreedomGG/Sindragosa#110]
Prospecting saronite ores drops only 1 green gem and a chance to drop 1 blue gem while it should drop 1-2 green gems and 1-2 blue gems of any kind according to wowhead or any prospecting video in wotlk

**Comment by Hotdogtree** [comment]
Seconding this - I prospected nearly 100 stacks of ore and got no doubles of any kind. RIP.
