### ISSUE TITLE
[Hunter][Spell] Freezing Arrow Trap

### ISSUE THREAD

**Issue by parsafr0st** [GameFreedomGG/Sindragosa#112]
Hi there ... So ... Basically when u do the ability on some adds or mobs to avoid pulling them ... the whole raid goes into combat or after the next combat they wouldnt come out of it till the mob is killed ... some times the mobs would be pulled when its defrosted (to the healer usaully)
well i guess you know how its suppose to work...not even the hunter shouldnt enter the combat when the freezing arrow applies to the target...

 -Madax

**Comment by UltraNix** [comment]
I can't reproduce it. @parsafr0st Please give me examples of these mobs/adds.

**Comment by parsafr0st** [comment]
@Loken-Whitemane its not specified to a type of adds, all the adds in general while u r in dung or raids and u cant test it solo, u have to have some healer or sort with u in the raid/dung, i believe thats what triggers it, getting healed or something when u did trap, im gussing thats the case

**Comment by Soufly** [comment]
Traps should not put y in combat, more info later*

**Comment by parsafr0st** [comment]
> Traps should not put u in combat: [SunwellTracker/issues#2564](https://github.com/SunwellTracker/issues/issues/2564) if thats the problem.

omg, its so simple.i mean when the target gets freezed!!!!!!

**Comment by UltraNix** [comment]
@parsafr0st Still nothing. Got Rejuvenation on my hunter and then used Freezing Arrow. Mob is freezed and no combat. Could you record a videos of this?

**Comment by parsafr0st** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, Jan 17, 2022 at 16:55, ***@***.***> wrote:   


@parsafr0st Still nothing. Got Rejuvenation on my hunter and then used Freezing Arrow. Mob is freezed and no combat. Could you record a videos of this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned. 

Sure, i ll make a vidMessage ID: ***@***.***>

**Comment by parsafr0st** [comment]
> @parsafr0st Still nothing. Got Rejuvenation on my hunter and then used Freezing Arrow. Mob is freezed and no combat. Could you record a videos of this?

https://file.io/oVINdQxOVWLd

u can see the problem here

**Comment by parsafr0st** [comment]
@UltraNix so u get it now?

**Comment by UltraNix** [comment]
Yes. Fixed. Not live yet.

**Comment by parsafr0st** [comment]
> Yes. Fixed. Not live yet.

nice, tnx
i also reported something else, check it out
https://github.com/GameFreedomGG/Sindragosa/issues/413
