### ISSUE TITLE
[Quest][NPC] Words of Power - High Priest Talet-Kha

### ISSUE THREAD

**Issue by Apakalipsis1992** [GameFreedomGG/Sindragosa#117]
Hello. Can't complete quest "Words of Power" because can't kill "High Priest Talet-Kha" and loot from he quest item. Mob bugged and not available for attacks. Help please with this problem.

**Comment by MrTide** [comment]
Quest itself doable but its not working 100% only a GM reset can make it doable again for other players (kill and respawn)

**Comment by UltraNix** [comment]
Looks okay to me. Please retest it.

**Comment by MrTide** [comment]
> Looks okay to me. Please retest it.
A player comes in and kills one of the cocoons
then leaves and that cocoon respawns.
another player comes in kills both cocoons
and nothing happens
event wont work
