### ISSUE TITLE
[Death Knight & Rogue][Spell] Death and Decay is not affected by Cloak of Shadows

### ISSUE THREAD

**Issue by Adoxz** [GameFreedomGG/Sindragosa#127]
Makes it pretty much impossible to vanish cloak vs a death knight. Does not go through cloak on neither warmane or circle

**Comment by UltraNix** [comment]
I got no problem with vanishing Death and Decay with cloak. @Adoxz More info needed.

**Comment by Adoxz** [comment]
@UltraNix It was fixed pretty fast after I made this post
