### ISSUE TITLE
Ionar (HOL) randomly immune to Lightning Bolt

### ISSUE THREAD

**Issue by Regular93** [GameFreedomGG/Sindragosa#130]
3rd Boss in Halls of Lightning is immune to Lightning Bolt (Shaman)
![WoWScrnShot_111721_194806](https://user-images.githubusercontent.com/94563076/142264365-5fe9ff1e-0540-49ec-a3fc-d3f1d6b1892f.jpg)

**Comment by MissZay** [comment]
that's not a bug, this boss is immune to nature damage

**Comment by Soufly** [comment]
https://youtu.be/lzG3eT2Zslg?t=310
https://www.youtube.com/watch?v=kqQD30n8Da0
https://github.com/SunwellTracker/issues/issues/3535
He is not immune.
