### ISSUE TITLE
Sons of Hodir Reputation Gain

### ISSUE THREAD

**Issue by 11jbrooks** [GameFreedomGG/Sindragosa#141]
As an adventurer we were supposed to be given x2 Reputation when Sons of Hodir is giving only x1. Please look into it.

**Comment by Hategodx** [comment]
Hello sir. It has been said multiple times that yes, Path of Adventurer will receive x2 rates APART from Sons of Hodir as this one will remain x1 for both paths.

**Comment by Loken-Whitemane** [comment]
This is intentional.
