### ISSUE TITLE
[Mage][Talent] Arcane Potency - Clearcast & Presence of Mind

### ISSUE THREAD

**Issue by Silvyplays** [GameFreedomGG/Sindragosa#148]
Arcane Potency buff not activating regularly after Clearcast nor Presence of Mind. Massive DPS-loss for Arcane.

Tested since launch. When active, it only affects the first missile in Arcane Missiles through Missile Barrage.

**Comment by MrTide** [comment]
Works as intended probably already got fixed since you reported it.
![image](https://user-images.githubusercontent.com/36106057/149790707-aee0d7b9-e7d5-4a95-9e40-cdb31350f135.png)
![image](https://user-images.githubusercontent.com/36106057/149790897-667e3fb6-97bc-4b93-91dd-92c74184c292.png)
