### ISSUE TITLE
Penance 3rd tick doesnt go off while being hit.

### ISSUE THREAD

**Issue by Soundmanone** [GameFreedomGG/Sindragosa#156]
Hello hi, 
Issue: Penance 3rd tick doesnt come off while being hit 
How its supposed to work: Penance 3rd tick should always come out 
How to reproduce: get hit and press penance 
This bug was also on whitemane at the beggining then it got fixed

**Comment by Game-Freedom** [comment]
https://github.com/SallyWhitemane/Mograine/issues/851
