### ISSUE TITLE
[Mage][Spell] Blink in Dustwallow Marsh

### ISSUE THREAD

**Issue by CeoOfCoronavirus** [GameFreedomGG/Sindragosa#16]
Issue: As a mage you easily fall through the map if you are not careful with blinks. There are a lot of steep hills that can be blinked through by accident. You will fall for a while until you finally die. Releasing spirit will automatically ressurect you at the nearest graveyard.

How to recreate: Get a mage with blink and find some steep terrain in Dustwallow Marsh. Around Witch Hill are a lot of them.

**Comment by UltraNix** [comment]
@CeoOfCoronavirus Give me exact coords.

**Comment by UltraNix** [comment]
No respone - closing.
