### ISSUE TITLE
Omen of Clarity -> Clearcasting

### ISSUE THREAD

**Issue by foxeelol** [GameFreedomGG/Sindragosa#160]
The problem is in Cat form it only procs from the normal auto attack , https://wotlkdb.com/?spell=16870#modifies:0+1+13+3 this is the list what spells can proc it.   (I never got proc from swipe , shred , mangle,rip) only Faire Fire and Fero bite can proc it rarely. Can you please check it ? Meanwhile in Bear form it works propely.

**Comment by styxel** [comment]
Omen of clarity works like it should stop making pointless reports.

Its not supposed to proc from swipe shred mangle etc..

That list does not mean those abilities proc ooc.

Rip and rake only proc it during ulduar with tier 8 set..

**Comment by gandalkk** [comment]
Working like on warmane here i think Its good too.  U have to understand that if it procced from swipe etc u would have close to 100% uptime on ooc procs :D.

**Comment by foxeelol** [comment]
Ooooh Yea its working 1 proc / min is completely normal. Styxel did you ever play feral?

**Comment by gandalkk** [comment]
Yes i am janualbert Best feral In world.

**Comment by styxel** [comment]
Yes, i am janualbert Best feral In wotlk.

**Comment by Soufly** [comment]
Patch 3.0.2 (2008-10-14): Now a passive spell. Now also procs on damage and healing spells, yet no longer procs on feral abilities(only auto-attacks proc it). Proc rate is roughly 6% with a 10 second internal cooldown.(OoC)

**Comment by foxeelol** [comment]
Okay , then i played on bugged servers before. I was proc it with consumables , fiery weapon etc
