### ISSUE TITLE
[Item] Pendant of the Violet Eye

### ISSUE THREAD

**Issue by Iordxidan** [GameFreedomGG/Sindragosa#161]
@https://tbc.wowhead.com/item=28727/pendant-of-the-violet-eye This item need to give 2x stacks when u heal with beacon+holy light any target, its working on same way like @https://www.wowhead.com/item=46051/meteorite-crystal from ulduar who gives 2 stacks when u heal with beacon+hlight/flash heal or holy shock, but there is 1 bug what i see in most of private servers and dont know if need to work liket this or no( if ur blood elf u can use trinket and if there are 4x target with racial u can tag them all and u get insta 4x stacks on trinket)

**Comment by MrTide** [comment]
This is correct and requires a full review specially on  [Meteorite Crystal]
even priests prayer of fortitude buff can get you to max stack with single cast while it shouldn't basically every cast should only give you one stacking buff
This include priest prayer of healing, circle of healing prayer of fortitude(basically any raid wide buff wild/gob/prayer of spirit and so on), druid wild growth 
only exception so far is paladin beacon of light which gives you two stack with one cast and that also does not include glyph of holy light heals.

similar issue on sunwell

More info here

https://github.com/SunwellTracker/issues/issues/1578
