### ISSUE TITLE
[Warrior][Spell] Overpower

### ISSUE THREAD

**Issue by vedude** [GameFreedomGG/Sindragosa#163]
Overpower does not activate on yellow dodge hits.

**How it's supposed to be:**

Overpower procs on all dodge hits. This includes white and yellow hits.

**How it's functioning currently:**

Overpower procs on white dodge hits, but not on the yellow ones.

**Comment by UltraNix** [comment]
![obraz_2022-01-12_183752](https://user-images.githubusercontent.com/80540499/149192654-a28429c8-7212-4ee2-aea1-a1bfb757ecae.png)
Not a bug. Everything works okay.
