### ISSUE TITLE
[Quest][NPC] The Jig Is Up - Kill Bear before it kills Jonah Sterling

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#166]
Replicate, get Jonah low to initiate the RP where he jumps down and gets eaten by the bear, kill the bear before the bear can kill Jonah and he will get stuck tagged and untargetable by others.

**Comment by MrTide** [comment]
Yes confirmed issue, requires a reset(kill and respawn) by game masters to fix it ingame thats the only way to make the quest available and doable again for other players

**Comment by UltraNix** [comment]
But Hozzer is not attackable before Sterling's dead- how to do it? @MrTide

**Comment by MrTide** [comment]
> But Hozzer is not attackable before Sterling's dead- how to do it? @MrTide

Sorry for late response, I can't reproduce the bug exactly but he jumps down and bears comes to eat it but his body stays down stuck with 6000-8000hp and we need to reset it.
I will try to reproduce again

**Comment by MrTide** [comment]
Found the issue
bear is still dead but jonah respawns and players do it and he jumps down and gets stuck in there @UltraNix
