### ISSUE TITLE
[NPC] Sister Mercy Ship NPCs falling through floor

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#168]
They are all stuck in the floor, when you get close they fall out when if the ship is in motion. There is a quest to kill them and only 1 on the ship doesn't fall through (top floor)

**Comment by runsonmypc** [comment]
No mobs were there when I checked.

**Comment by staylifted123** [comment]
That's because they have fallen through the floor. There is supposed to be mobs on the ship to complete one of the quests, when I engaged, every mob but 1 fell through the floor and never returned.

**Comment by UltraNix** [comment]
@staylifted123 @runsonmypc  I can't reproduce it. Please, retest it.

**Comment by MrTide** [comment]
Quest https://www.wowhead.com/quest=11527/mutiny-on-the-mercy
When first player kills them after respawn they respawn under the ship
https://cdn.discordapp.com/attachments/928055564301398056/928735668190973992/unknown.png
https://cdn.discordapp.com/attachments/928055564301398056/928735790761144341/unknown.png

**Comment by UltraNix** [comment]
Still works okay to me.

**Comment by MrTide** [comment]
https://cdn.discordapp.com/attachments/448057838263336961/928741002297110558/unknown.png
try testing while ship is moving and move them around

**Comment by UltraNix** [comment]
Yep - I was testing that while ship was moving.
