### ISSUE TITLE
[Dungeon][NPC][Pathing] The Nexus - Crystalline Frayer

### ISSUE THREAD

**Issue by pepet005** [GameFreedomGG/Sindragosa#171]
Decription:
Patrol at Ormorok is broken, stands still by boss.

How it works:
Patrol gets pulled with boss. (In 1 of our 2 pulls)

How it should work:
Patrol should patrol around boss platform, so we can kill it before boss.

Source (you should point out proofs of your report, please give us some source):
https://imgur.com/a/nfJz1Rn

There it stands still.

Compare to https://youtu.be/w7eVPPWZaVQ?t=391 (timestamp: 6:31)

**Comment by MrTide** [comment]
His video is from 2016 but still correct these npcs are missing way points which means they are barely moving and not patrolling at all just standing behind the boss doing nothing

![image](https://user-images.githubusercontent.com/36106057/148946664-53e7fd2b-eb19-4f80-b69c-0faa5b95a35a.png)
