### ISSUE TITLE
The Last Line Of Defense 

### ISSUE THREAD

**Issue by Weihwasser** [GameFreedomGG/Sindragosa#175]
Decription:
The Last Line Of Defense BUG 
How it works:
After you finish the Quest The Last Line Of Defense you get stuck an the little house dor  - if you alt f4 it kinda works - if you die and get ressed you stil walk on the same spot and cant move 
How it should work:
you should not get stuck there 
Source (you should point out proofs of your report, please give us some source):

https://ibb.co/NFscvbs
https://ibb.co/qBj4p7z

**Comment by MrTide** [comment]
This true but i am not sure if this can be fixed or not .. its not just related to the quest its simply that whole area causes this issue specially if you have slower hard drive it will happen more. i will leave this to devs to decide if this can be fixed or not

**Comment by UltraNix** [comment]
I can't really reproduce it.
