### ISSUE TITLE
[Profession] Fishing - Bobber

### ISSUE THREAD

**Issue by TheChegg** [GameFreedomGG/Sindragosa#179]
Decription:
Fishing bobber is randomly uninteractable when casting a new bobber.
How it works:
It happens seemingly randomly when casting a new bobber. but i have a theory that it could be caused by a bind by pickup item that can be obtained by fishing
How it should work:
The fishing bobber should be interactable

I have only fished in dalaran sewers and i dont know if this bug persists in other zones

**Comment by TheChegg** [comment]
(It happens everywhere, it jsut happened to me in borean tundra)

**Comment by MissZay** [comment]
it also happens in wintergrasp where the only things you can fish are items that aren't BoP

**Comment by UltraNix** [comment]
I can't reproduce it. @TheChegg @MissZay Need more info on that.

**Comment by MrTide** [comment]
I can't reproduce it either. everything seems in order might be UI addon related.
