### ISSUE TITLE
[Dungeon][NPC] Scarlet Monastery Cathedral -  Whitemane does not revive Mograine

### ISSUE THREAD

**Issue by serioux1337** [GameFreedomGG/Sindragosa#180]
Decription:
In Scarlet Monestary Cathedral High Inquisitor Whitemane should revive Scarlet Commander Mograine
How it works:
She does sometimes teleport to him and revive him, sometimes she does not and the instance is not finishable (stuck in combat)
How it should work:
She should always be able to revive him, independant of line of sight

Source (you should point out proofs of your report, please give us some source):
No proof needed, the instance is not finishable without bugfix

**Comment by MrTide** [comment]
So there are two issues ... 
1. she goes through wall after killing mograine
2. she gets stuck at 1hp

To Reproduce the first case you need to have someone at entrance so she basically ignores the player sometimes and runs through the wall, so its better to limit the encounter to the boss room and that should solve the issue

To reproduce the second issue, players casting a spell that disables the school of magic like mage counter spell and that stops whitemane to cast her spell and revive commander mograine so events get stuck and she stays at 1HP

**Comment by UltraNix** [comment]
@MrTide I can't reproduce the 2nd bug.

**Comment by MrTide** [comment]
> @MrTide I can't reproduce the 2nd bug.

Please use mage counter spell and when she is casting smite use mage counter spell on her then damage her to 50% hp she tries to ress mograine but she can't and event stops there she can't ress and also she wont die.
I would assume removing her Resurrection from holy school of magic should solve it. unless you have a better idea.

**Comment by UltraNix** [comment]
Yes - that's what I tried. Caster counterspell on her while casting smite, then immediately `.damage 10000`, she casted sleep on me, moved to mograine and ressed him (that resurrection spell has normal spell school and counterspell works only on magic spells).

**Comment by MrTide** [comment]
> Yes - that's what I tried. Casted counterspell on her while casting smite, then immediately `.damage 10000`, she casted sleep on me, moved to mograine and ressed him (that resurrection spell is physical and counterspell works only on magic spells).

I will try one more time to make sure i will update this message shortly
