### ISSUE TITLE
Monitoring the Rift: Cleftcliff Anomaly (quest) not working

### ISSUE THREAD

**Issue by Pajcone** [GameFreedomGG/Sindragosa#182]
Description:
Monitoring the Rift: Cleftcliff Anomaly (quest) not working
How it works:
Upon the entering the cave, the player is not able to use the quest item to do the reading of the anomaly per quest instructions. Tried going deeper into the cave to see if the quest item works in there - still nothing.  
How it should work:
Upon reaching the mouth of the cave, the player should be able to use quest item and complete the quest.
Source (you should point out proofs of your report, please give us some source):
Guide on YouTube, Blizzard's version.

**Comment by Leowasted** [comment]
Quest works fine, specific location is required when using the item. Personally completed all of them without issue.

**Comment by Raulfin** [comment]
same, they are all very picky about where you stand for the item to work.
