### ISSUE TITLE
[Profession] Tailoring -  Patterns not Appearing

### ISSUE THREAD

**Issue by Tsien13** [GameFreedomGG/Sindragosa#183]
Decription: Patterns not showing in Tailoring Panel

Bug happening to:  Lito, Blood Elf Mage, Level 80

What happened: While i was leveling up my Tailoring i Trained from Charles Worth <Grand Master Tailoring Trainer> in Dalaran,
I am currently level 431 Tailor, I have trained all patterns from him, but it seems all the Spellthreads and Embroidery patterns are not showing on my Tailoring Panel in order to make them.

I tried disabling all Add Ons, and clearing my cache folder, and i cant still see those specific patterns.
If i look to train them, it shows them as "Already Learned".

**Comment by MrTide** [comment]
Did you try different client ? did you check the trainer/ your own profession filters ? maybe you need to learn them. i don't see any issue here

**Comment by Godmatik** [comment]
@MrTide 
This was a bug occurring early on server's release but I believe Jimmy already fixed it
