### ISSUE TITLE
[Dungeon][Item] Blackrock Depths - Core Fragment Stone Missing

### ISSUE THREAD

**Issue by fatalization** [GameFreedomGG/Sindragosa#187]
Decription: In BRD at the entrance to MC you pick up a core fragment to become attuned

How it works: The core fragment stone is not interactable

How it should work: You are able to right click it to loot the core fragment

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Its only interactable if and only if you have the quest called Attunement to the core.
![image](https://user-images.githubusercontent.com/36106057/149940265-421f9942-dd3e-4565-94ba-91b64d2d9371.png)
