### ISSUE TITLE
[Core] Icecrown Airship Missing From Map

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#190]
Decription: The airships are not appearing on the map

How it works: The airships rarely appear on the map.

How it should work: The airships should move around the map constantly and appear on maps. 

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/b11yDi7

**Comment by staylifted123** [comment]
They sometimes do start moving, then get stuck at a location again.

**Comment by MrTide** [comment]
If you are talking about small icons of the ships yes thats true none of one of them are showing on map they appear when you board on them but disappear again once you leave, based on these comments they should show up. 
really minor issue tho.

https://www.wowhead.com/quest=13225/the-skybreaker#comments:id=790985

https://www.wowhead.com/quest=13225/the-skybreaker#comments:id=391142

**Comment by UltraNix** [comment]
Not doable without rewriting the grid system. Won't be fixed.
