### ISSUE TITLE
[Quest][NPC] Assault By Air - NPCs missing

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#191]
Decription: The quest Assault by Air has no enemy mobs attacking you in the sky. 

How it works: You just sit afk and nothing attacks you.

How it should work: Enemies are supposed to fly at and aggro you during the mission, you are meant to shoot them down.

Source (you should point out proofs of your report, please give us some source): Icecrown Daily  
![image](https://user-images.githubusercontent.com/47200469/142747811-51d53b2e-23c6-4142-9086-2419ce914703.png)

**Comment by MrTide** [comment]
I did this quest myself and there was no issue .. sadly this quest can be none sense but still i couldn't find an issue

https://www.youtube.com/watch?v=QocqIwmiMpk guide if you like to check

This issue can be closed.

**Comment by MrTide** [comment]
I did this quest myself and there was no issue .. sadly this quest can be none sense but still i couldn't find an issue

https://www.youtube.com/watch?v=QocqIwmiMpk guide if you like to check

This issue can be closed.
