### ISSUE TITLE
[Death Knight][Pet] Ghoul aggro

### ISSUE THREAD

**Issue by nwardoh** [GameFreedomGG/Sindragosa#192]
Decription: Not sure if it is all pets but my ghoul will run to attack as soon as I target an enemy mob rather than waiting for it to perform an action against me. 

How it works: target mob, ghoul runs to attack it

How it should work: Ghoul stays at my side passively until a hostile action is done to me. It should not attack when I target a mob or even perform an action on the mob, only when the mob performs a hostile action on me.

Source (you should point out proofs of your report, please give us some source): This is just how it is supposed to work, its even in the name defensive :)

**Comment by Soufly** [comment]
Did u right click the hostile target ? U have an option from interface for auto atack/shot and if u right click a hostile target,the pet will attack in defensive mode.

**Comment by nwardoh** [comment]
Any click on the target does it but it still shouldn't if you right click on it. That is not defensive, that is aggressive

**Comment by nwardoh** [comment]
I logged into a warlock on tbc classic to test, I am positive it never  changed in the history of wow. I have a video if you want to see it. Set pet to defensive. Left click mob, doesn't attack. right click mob doesn't attack. I attack the mob, doesn't attack until the mob hits me. Walk into the mob with it targetted or not, doesn't attack until the mob hits me. You can do the same in shadow lands to see it has never changed. This makes unholy almost unplayable.
