### ISSUE TITLE
[Quest][NPC] Honor is for the Weak - Restless Lookout

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#195]
Decription: The quest Honor is for the Weak (Icecrown)-Restless Lookouts see you as an Eidolon Watcher, you are supposed to be able to use Assassinate on them but you are put into combat with them.

How it works: Restless Lookouts see you as an Eidolon Watcher, you are supposed to be able to use Assassinate on them but you are put into combat with them.

How it should work: https://www.youtube.com/watch?v=eY-nO3IHrvM

**Comment by MrTide** [comment]
https://github.com/GameFreedomGG/Sindragosa/issues/222
