### ISSUE TITLE
[Quest][NPC] I'm Not Dead Yet - Brother Keltan

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#196]
Decription: Quest: I'm Not Dead Yet (Icecrown) Brother Keltan does not stop to attack or defend during escort.

How it works: Quest: I'm Not Dead Yet (Icecrown) Brother Keltan does not stop to attack or defend during escort. He just keeps walking and casting spells.

How it should work: He is supposed to stop and attack mobs that are aggro'd to him. https://www.youtube.com/watch?v=DMsh5ikE0c0

**Comment by Loken-Whitemane** [comment]
Confirmed. 
Father Kamaros (GUID 121631) will cast spells while moving, but does not stop to attack mobs, he will continue moving forward until death.
