### ISSUE TITLE
[Quest][NPC] Betrayal quest in chain

### ISSUE THREAD

**Issue by Renoucer** [GameFreedomGG/Sindragosa#197]
Decription:
For reasons unknown to me Brute dissapers after dealing ~25% hp to drakuru. when you try to tame another one brute, all dissaperrs. So quest becomes unable to make

How it should work:
Brutes dont vanish.

Source (you should point out proofs of your report, please give us some source):

**Comment by Matchbox23** [comment]
Can confirm, tried the quest about five times and faced the same result every time. I was playing a hunter, so I assumed that's part of the cause, but upon retrying without using any abilities except the troll's the same issue happened.

**Comment by MrTide** [comment]
Honestly this quest requires full rewrite this is a confirmed issue only handful of ppl were able to complete this quest
