### ISSUE TITLE
[Quest][NPC] The Last of Her Kind - Brunnhildar Warbear

### ISSUE THREAD

**Issue by Renoucer** [GameFreedomGG/Sindragosa#200]
Decription:
Low Range of putting on buff Lo'lira's Bargain(disguise) makes Bears and other NPCs attack player
How it works:
When u ride that Bear and enter area of village npcs attacks you.
How it should work:
You get disgused before reaching npcs agro area.
Source (you should point out proofs of your report, please give us some source):
![image](https://user-images.githubusercontent.com/82383779/142761843-70ba115d-1220-4ca7-9935-813b97c0bca2.png)

In addiction if u get off that bear and try to get on the  same one, he will turn back to starting location by glitching under the map.

**Comment by UltraNix** [comment]
It is delayed due to server performance and won't be fixed.
