### ISSUE TITLE
Blessing of Zim'Torga not working

### ISSUE THREAD

**Issue by Zimnywuj** [GameFreedomGG/Sindragosa#205]
Decription: In Zul'Drak you can get 3 blessings for 10 offerings each. Zim'Abwa works fine, but Zim'Torga becomes unaviable after 2 turn-ins.

How it works: After doing the chain you can get the blessing twice, then statue becomes un-clickable.

How it should work: After doing the chain you can get the blessing as many times as you want for 10 offerings

**Comment by MrTide** [comment]
Can confirm sunwell had the same issue
https://wotlk.evowow.com/?quest=12567

https://github.com/SunwellTracker/issues/issues/2794
