### ISSUE TITLE
Kreeg's Stout Beatdown and Well Fed Buff

### ISSUE THREAD

**Issue by Floasted** [GameFreedomGG/Sindragosa#208]
Decription: Kreeg's Stout Beatdown is a on use that Increases Spirit by 25 but decreases intellect by 5 for 15 min Its counted as a debuff

How it works: Kreeg's Stout Beatdown is taking off Well Fed Buff

How it should work: Kreeg's Stout Beatdown and Well Fed should stack

Source (you should point out proofs of your report, please give us some source): I Had well fed buff and drank the brew and lost well fed

**Comment by scrublama** [comment]
they should not stack 
proof:
![image](https://user-images.githubusercontent.com/24984413/142878541-d84b3b72-a902-4af0-8cd5-0fbbf91ea830.png)

**Comment by Firtwo** [comment]
on the PTR server they stacked

**Comment by mrnuggets** [comment]
> on the PTR server they stacked

Thank god it was fixed then ;-)
