### ISSUE TITLE
[Druid][Spell] Wild Growth

### ISSUE THREAD

**Issue by oldspices** [GameFreedomGG/Sindragosa#210]
Decription:
druid aoe heal is casted at enemy if you have an enemy player targeted, it puts the spell on cd but nothing happens really, no friendly targets get the heal.  i think it thinks they are friendly or something. 
How it works:
spell is on cd but nothing notable happens 
How it should work:
it should be cast on yourself. 
Source (you should point out proofs of your report, please give us some source): i noticed it in wintergrasp, maybe its pvp / player only ?

**Comment by MrTide** [comment]
Wild growth/Circle of healing can apply to all friendly targets within 15/18 yards of the target even if target is an enemy unit/npc. If you are within 15/18 yards of the target, it can apply to you.

Abillity works as intended. 
also discussed here

https://github.com/dalaranwow/dalaran-wow/issues/4829

This can be closed

**Comment by oldspices** [comment]
what you have described is not what is (or was) happening at all when i casted wild growth with enemy targeted. enemy targeted, wild growth did not go on the tank, or anyone within range of enemy. no one got the wild growth.

**Comment by MrTide** [comment]
> what you have described is not what is (or was) happening at all when i casted wild growth with enemy targeted. enemy targeted, wild growth did not go on the tank, or anyone within range of enemy. no one got the wild growth.

I did test it out again and it works i am not sure what the problem was with your encounter can you please try it one more time.
