### ISSUE TITLE
[Dungeon][NPC][Profession] Lavanthor Unskinnable

### ISSUE THREAD

**Issue by jozo-krstanovic** [GameFreedomGG/Sindragosa#216]
Decription:

After killing Lavanthor and looting him, he's still unable to be skinned.
Reference: Same issue as wolves in Duskwood.

How it works:
Lavanthor dies, gets looted and trying to skin him just opens the empty loot window popup.

How it should work:
After dying and being looted, Lavanthor should be skinnable.

Source (you should point out proofs of your report, please give us some source):
https://www.wowhead.com/npc=29312/lavanthor/heroic-encounter-journal#skinning;mode:heroic

**Comment by Renoucer** [comment]
I think its not correct link. 
I believe this is: https://wotlk-twinhead.twinstar.cz/?npc=31509#skinning
I was always thinking you cannot skin mobs above lvl80, but i see now it should be possible.

**Comment by MrTide** [comment]
> I think its not correct link. I believe this is: https://wotlk-twinhead.twinstar.cz/?npc=31509#skinning I was always thinking you cannot skin mobs above lvl80, but i see now it should be possible.

I couldn't find anything to back your claim specially when players already talking about skinning in this post as you can see you can skin him
https://www.wowhead.com/npc=29312/lavanthor#comments
you can even skin TOGC beasts.
Steps that i took to reproduce this bug
1. I went to VH and killed the boss on both normal and heroic version
2. I looted the boss took all of the items and icon to skinning pops out
3. when i attempt to skin the boss nothing happens.
