### ISSUE TITLE
[Quest][NPC] The Fate of Bloodbane - Orbaz Bloodbane

### ISSUE THREAD

**Issue by bonecrusha** [GameFreedomGG/Sindragosa#217]
Decription: NPC called Orbaz Bloodbane is not at the location he's supposed to be at.

How it works: NPC is'nt there

How it should work: He is supposed to be by the bombs underneath the Icecrown citadel.

Source (you should point out proofs of your report, please give us some source):
https://wotlkdb.com/?npc=31283

**Comment by Soufly** [comment]
![WoWScrnShot_020422_161614](https://user-images.githubusercontent.com/36957911/152543877-9e505c53-5cfd-492f-9a73-21b92ec26fbe.jpg)
He is on the right spot,even without the quest.

**Comment by MrTide** [comment]
I checked it with the quest and he was there i am guessing he got some other quest which phased him out
