### ISSUE TITLE
[Death Knight][Spell] Raise Dead

### ISSUE THREAD

**Issue by Henniken** [GameFreedomGG/Sindragosa#218]
Decription: Seems to happen when you spam a button or press the Spell "Raise Dead" to summon a ghoul fast after a global CD. Only relog fixes the problem, in arena this would obv be not possible so its a huge fuckup as Unholy Dk in PvP if this happens

How it works: If you press Raise Dead it somtimes becomes grey and not usable, doesnt trigger a CD, it is just permanently non usable

How it should work: You should just be able to summon the ghoul and if it dies or is dissmissed, be able to cast the spell again after 30 sec

Source (you should point out proofs of your report, please give us some source): Not needed as its obvious, was working correctly on whitemane, didnt work also on old sunwell server...

**Comment by Henniken** [comment]
![WoWScrnShot_112321_032327](https://user-images.githubusercontent.com/71415136/142962524-b8d2c5f4-34c2-4f9f-b89f-770ee46c3b33.jpg)

 this occurs even tho there is no ghoul summoned

**Comment by Kirschie** [comment]
I can confirm this issue. I had the same issue and to resolve it I had to exit and restart the game. A /reload did not work for me.
