### ISSUE TITLE
[Dungeon] [low priority] Occulus Heroic Mage-lord Urom encounter

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#219]
Decription:

The first pack mobs vs a mage (Mage-Lord Urom) should be on the first platform.

How it works:

It's in the middle where should appear boss after clearing 3 platforms

How it should work:

https://youtu.be/f6KLV6P9LlY?t=193

Source (you should point out proofs of your report, please give us some source):

https://www.wowhead.com/the-oculus

**Comment by Godmatik** [comment]
Already reported and labeled as fixed, I'm guessing after a server restart.

https://github.com/GameFreedomGG/Sindragosa/issues/167
