### ISSUE TITLE
[Profession][Item] Herbalism - Crystalized Life

### ISSUE THREAD

**Issue by Grompak** [GameFreedomGG/Sindragosa#220]
Decription: Drop rate from herbs of crystalized life is way too low

How it works: From 12-15 nodes i farmed, only 1 had crystalized life

How it should work: drop rate is x2 so about 75% of nodes should have crystalized life in them

Source (you should point out proofs of your report, please give us some source): just go and try to farm eternal life, cant really give any proof beside that from 6-7 hours of farming in low population hours i got 12 eternal lifes....

**Comment by MrTide** [comment]
I went around farming every type of herb available in northrend and on every 10herb 4-6 of times i got crystallized life. and based on the drop rates of the items listed here https://wotlk.evowow.com/?item=37704#gathered-from-object drop rate should be around 20-25% which with path of the adventurer drop rate would be 40-50%
I couldn't find any issues here.
steps i took to reproduce this bug:
1. went to the world farming every type of herbs at least 10-20 times
2. got the crystallized life 40-60% time

-------
This issue can be closed.
