### ISSUE TITLE
[Profession][Item][Pathing] Duskwood Herb

### ISSUE THREAD

**Issue by Icyhotpee** [GameFreedomGG/Sindragosa#221]
Decription: 36.8 33.7 location in Duskwood

How it works: herb stuck in tree and unlootable

How it should work: herb should not be stuck in tree

Source (you should point out proofs of your report, please give us some source):
![WoWScrnShot_112321_013841](https://user-images.githubusercontent.com/94892999/142986231-ed870cbd-5ffd-4b9c-b0f8-cfc69e4236c7.jpg)

**Comment by UltraNix** [comment]
Cannot reproduce and no response - closing.
