### ISSUE TITLE
[Quest][NPC] Honor is for the Weak - Restless Lookout

### ISSUE THREAD

**Issue by Renoucer** [GameFreedomGG/Sindragosa#222]
Description:
Eldolon Watcher( "vehicle"-operated by player) gets attacked by Restless Lookout even if he not face him

How it works:
When u came to Restless Lookout he attacks you.

How it should work:
You should get as close to the Restless Lookout to use 5(Assasinate Restless Lookout)

Source (you should point out proofs of your report, please give us some source):

https://user-images.githubusercontent.com/82383779/143018784-8d7312a1-8d65-4da0-b9b8-fc604887ad07.mp4

**Comment by MrTide** [comment]
Can confirm
These creatures are simply missing https://wotlk.evowow.com/?spell=58548 aura 
If you add it... it will fix it
I did it manually ingame and solved it.
No aura
![image](https://user-images.githubusercontent.com/36106057/148683433-d10e7d83-ef30-4918-8e6c-6218c223b63d.png)
