### ISSUE TITLE
[Profession] Fishing - Bobber

### ISSUE THREAD

**Issue by MasonOl** [GameFreedomGG/Sindragosa#224]
Decription:
Fishing Bobber instantly catching fish on cast.

How it works:
Currently, when you use the "Fishing" skill button gained from training fishing and it sends a bobber into water, sometimes the fish can be caught instantly.

How it should work:
On live servers and in retail Wrath of the Lich King, fishing bobbers were tuned to where fish won't be caught within the first 3 seconds of catching a fish nor in the last 3 seconds of catching a fish.

Steps to Reproduce:
1. Use the "Fishing" skill in any body of water gained from training Fishing.
2. Observe the bobber and see if it instantly catches a fish. If it does not, repeat Step 1 until it yields expected result.

Source (you should point out proofs of your report, please give us some source)

https://user-images.githubusercontent.com/79992463/143056494-05fed08c-74d4-4319-bd10-7b197b459233.mp4 - Behavior on Sindragosa Servers

https://user-images.githubusercontent.com/79992463/143058311-06a6646f-3d6f-4104-b131-2679c4a0a321.mp4 - Behavior on TBC Classic Servers

:

**Comment by relinkosed** [comment]
Can second this, a lot of the times, like a lot, it feels like I catch a fish either instantly when I cast, or the last second before it expires. Reverse of what it should be normally.

**Comment by Godmatik** [comment]
Confirmed - this is a bug present on nearly all private wrath server I have played on
