### ISSUE TITLE
[Profession][Quest][NPC] Fishing - Old Man Barlowe

### ISSUE THREAD

**Issue by MasonOl** [GameFreedomGG/Sindragosa#225]
Decription:
Old Man Barlowe is not in game, locking you out of many things such as achievements and fishing recipe.

How it works:
Old Man Barlowe is a Daily Questgiver outside of Shattrath who is useful for various things that enhance your fishing as well as locks the "Salty" achievement introduced in Wrath of the Lich King if he is not avaliable. On Sindragosa, this NPC does not appear to be in his normal position/is not in the game.

How it should work:
As you can see in the attached sources, Old Man Barlowe should be fishing at the pool right outside of Shattrath near the Dampscale Basilisks.

Steps to Reproduce:

1. Navigate to the coordinates 38, 12 on the Terrokar Forest map in Outland.
2. Observe that Old Man Barlowe is not where he should be.

Source (you should point out proofs of your report, please give us some source)
![Sindragosa Barlowe](https://user-images.githubusercontent.com/79992463/143058732-5ac308aa-b900-490c-bfe2-3f977fd9516a.PNG) - Sindragosa Behavior

![TBC Barlowe](https://user-images.githubusercontent.com/79992463/143058635-d3696a3a-2d1f-4794-a0d8-46176d4f1dda.PNG) - TBC Classic Behavior

:

**Comment by MrTide** [comment]
I just checked and he is there
![image](https://user-images.githubusercontent.com/36106057/148934252-d88dec63-d76f-47e6-877e-6b4d233a00e2.png)
