### ISSUE TITLE
Quest: Shrimpin' Ain't Easy

### ISSUE THREAD

**Issue by dutchride** [GameFreedomGG/Sindragosa#226]
Description: 
Bring 10 Giant Freshwater Shrimp to Old Man Barlo. You can find him fishing northeast of Shattrath City by Silmyr Lake.

How it works:
Fishing in Zangermarsh does not yield any bloated barbed gill trout while on the quest.

How it should work:
Fishing in Zangermarsh after quest is taken should result in bloated barbed gill trout which can be "opened" to receive the quest item.

Source (you should point out proofs of your report, please give us some source):
https://tbc.wowhead.com/quest=11668/shrimpin-aint-easy 
https://wowwiki-archive.fandom.com/wiki/Quest:Shrimpin%27_Ain%27t_Easy

**Comment by MrTide** [comment]
Can confirm
Steps that i took to reproduce this bug
1.Tried fishing with 450 skill at Serpentshrine Cavern zangarmarsh and underbog
2. Went around and tried what ever water i could find and nothing dropped
3. Drop rate is suppose to be 100% https://wotlk.evowow.com/?item=35313#fished-in-zone

**Comment by UltraNix** [comment]
@MrTide Please change the label to `Status: Confirmed Bug (Awaiting Development)`

**Comment by MrTide** [comment]
> @MrTide Please change the label to `Status: Confirmed Bug (Awaiting Development)`

done i will do the same with others too then i thought make loken wants to do them :)
