### ISSUE TITLE
[NPC] Cavedweller Worg

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#229]
Decription: There is way too low amount of wolfs in their cave.

How it works:
Low amount of wolfes in the cave.

How it should work:
There should be a lot more,from the start of the cave,not only deep into it.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/IC_C2hEaKxg?t=21
https://www.youtube.com/watch?time_continue=31&v=sljU5VzfleM&feature=emb_logo
https://youtu.be/3-1cbxoCWQw?t=36
https://youtu.be/5Vikk0QhJuc?t=65

https://github.com/SunwellTracker/issues/issues/2832

**Comment by MrTide** [comment]
Can confirm there are basically none at the entrance 
![image](https://user-images.githubusercontent.com/36106057/148683001-c528dbc6-1e7f-4797-b372-d47e0b4765ce.png)

**Comment by Soufly** [comment]
Edit: That also means more infesting jormungar since they are supposed to fight each other.

**Comment by MrTide** [comment]
Not ingame nor PTR its not resolved

**Comment by UltraNix** [comment]
@MrTide It's not needed.
I don;t why but I commited wrong coords.

**Comment by UltraNix** [comment]
@MrTide I see a lot of spawn of these mobs at the entrance.

**Comment by Soufly** [comment]
![WoWScrnShot_012122_173250](https://user-images.githubusercontent.com/36957911/150554534-3444a957-d3cc-4959-825a-ec9498fe5910.jpg)
Not live

**Comment by MrTide** [comment]
None in PTR
![image](https://user-images.githubusercontent.com/36106057/150554726-dce33b3b-6f79-4990-86a7-49261d6dede2.png)
