### ISSUE TITLE
[Profession] Engineering - Hyperspeed Accelerators

### ISSUE THREAD

**Issue by Stormbreaker23** [GameFreedomGG/Sindragosa#238]
Decription: Hyperspeed Accelerators, when u use it u have shared 1min CD with all type of potions like potion of speed, potions of wild magic etc huge bug.

How it works: The enchant gives u 340 haste for 12 sec and u are able to use potions with it .. but on this server its bugged and u cant cause it have shared 1min cd for some reason.

How it should work: On all servers and few years back on official it works like u can use the hands + any type of potion.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
I tested this interaction and they are not sharing cooldowns at all
![image](https://user-images.githubusercontent.com/36106057/148682591-c7f072e4-5a6f-4430-a8fd-e9ea15ada162.png)
![image](https://user-images.githubusercontent.com/36106057/148682607-41de1720-8e20-4228-97de-75257d5af7ad.png)
Try a cache delete and relaunch your game.
This Report can be closed.
