### ISSUE TITLE
[Core] Draw Distance

### ISSUE THREAD

**Issue by Istaryu** [GameFreedomGG/Sindragosa#240]
Decription:
Increase enemy draw distance
How it works:
Draw distance is way too low on the server. Doing quests that involve flying enemies is a nightmare, finding them is very hard because you can not see them.
How it should work:
Should be much higher.
Source (you should point out proofs of your report, please give us some source):
For example, compare https://www.youtube.com/watch?v=qzvmPD9pV5I&ab_channel=ooknat with what you see in game.

**Comment by MrTide** [comment]
We have increased draw distance since Nov 26 2021, I would assume it can be improved a little bit more if our developers see fit 
but this issue can be closed
