### ISSUE TITLE
[Warrior][Talent] Improved Hamstring

### ISSUE THREAD

**Issue by MrPieler** [GameFreedomGG/Sindragosa#242]
Decription:
The arms warrior talent "improved hamstring" does not proc the root as intended. I have tested it a few hundred times and yet to see any procs.

How it works:
Does nothing.

How it should work:
Should root 15% of the time.

**Comment by Loken-Whitemane** [comment]
Unable to recreate this. Tested 200 times and was able to get immobilize almost exactly 15% of the time.
