### ISSUE TITLE
Unable to interact with NPCs for Sons of Hodir

### ISSUE THREAD

**Issue by ennwar** [GameFreedomGG/Sindragosa#243]
Decription: Currently at honored with The Sons of Hodir rep, while they appear friendly to me, but I am unable to interact with any of the NPCs there.

How it works: No interaction and appear that I can only attack them
How it should work: Able to interact with all NPCs to farm rep.

Source (you should point out proofs of your report, please give us some source):
![Sons of hodir rep](https://user-images.githubusercontent.com/95097972/143615147-157bf90c-12dd-48c3-bb2e-0dad36801f98.png)

**Comment by Istaryu** [comment]
Untick at war with the faction.

**Comment by Loken-Whitemane** [comment]
As previously stated, this is due to being at war with the faction. Please untick the check box and you'll be good to go.
