### ISSUE TITLE
[Priest][Raid][Spell] Power Word: Shield & Loatheb (Naxxramas)

### ISSUE THREAD

**Issue by zalger** [GameFreedomGG/Sindragosa#244]
Decription: Loatheb's last tick of Deathbloom isn't absorbed. Actually all u can absorb is Loatheb's melee hits. Not sure how it should work with Inevitable Doom

How it works: Deathbloom isn't absorbed.

How it should work: Last tick of Deathbloom should be absorbed. Not sure about Inevitable Doom

Source (you should point out proofs of your report, please give us some source): 
Wowwiki: https://wowwiki-archive.fandom.com/wiki/Loatheb
retail logs: http://www.worldoflogs.com/guilds/5682/reports/78/?fbclid=IwAR0wqgmnezlTGNxGv_TOwcpebHgRJLDPSLwhTMqr53kPhvvmTDBPzoN2leQ

**Comment by UltraNix** [comment]
The last tick is properly absorbed.
![Uploading obraz_2022-01-14_215425.png…]()
