### ISSUE TITLE
[Quest][NPC] Teron Gorefiend, I am... - Karsius the Ancient Watcher

### ISSUE THREAD

**Issue by Maciupka** [GameFreedomGG/Sindragosa#247]
Decription: Quest name: Teron Gorefiend, I am...
                  Location: Shadowmoon Valley
                  Npc who gives quest: Ancient Shadowmoon Spirit

How it works: At the beginning we need to put on your glasses (Spectrecles). After that let's talk to Ancient Shadowmoon Spirit and take his quest. Then you will change form into Teron Gorefiend and your task is: kill Karsius the Ancient Watcher. When i want to use any spell being into form to attack him or use melee attack on him, Karsius just disappears.

How it should work: Krasius the Ancient Watcher should fight with us and he shouldn't disappear during fight with us, when we use any spells into form(Teron Gorefiend) and melee attack too.

Source (you should point out proofs of your report, please give us some source):
Here is my proof what happen after take quest from Ancient Shadowmoon Spirit - just watch it, link below.
 https://youtu.be/8TwpDu2bLb4

**Comment by MrTide** [comment]
This is tested ingame yes after first hit he just despawns for the players

**Comment by MrTide** [comment]
Not resolved players still can't see it even with glasses.
