### ISSUE TITLE
[Mage][Talent] Arcane Potency - Spell Ticks vs Cast

### ISSUE THREAD

**Issue by Istaryu** [GameFreedomGG/Sindragosa#249]
Decription:

How it works:
It is consumed immediately on spell ticks, such as blizzard or arcane missiles.
How it should work:
It should only work on spell cast. You cast a blizzard/arcane missiles/whatever with the buff up, the whole spell should benefit from it.
Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
This is incorrect unless you can provide proper evidence
As you can see in this video from 2009 it fades right away
https://www.youtube.com/watch?v=eLe1GacBNsk fast forward to 8:37
