### ISSUE TITLE
[NPC] Swiftmane

### ISSUE THREAD

**Issue by styxel** [GameFreedomGG/Sindragosa#25]
Was doing some happy guestin last nighjt In my favorite zone the barrens and saw this horse with stripes just standong still he is supposed to run around like a idoiot https://classic.wowhead.com/npc=5831/swiftmane

**Comment by MrTide** [comment]
By the look of it.. its missing some way points its not moving at all
https://www.youtube.com/watch?v=_-AReOGZ9rk
