### ISSUE TITLE
[NPC] Living/Mature Lasher

### ISSUE THREAD

**Issue by benkyte** [GameFreedomGG/Sindragosa#250]
Decription: Issue when looting those mobs in WG

How it works: Cannot loot items / herb them more often than not, only happens when we own WG

How it should work: once killed lootable and herbable

Source (you should point out proofs of your report, please give us some source): I am doing it right now

**Comment by MrTide** [comment]
I did test this and found no issues.
My best guess would be player was in raid group and that raid group had their loot on master loot that's why he was not able to loot it
