### ISSUE TITLE
[Quest][NPC] Tormenting the Softknuckles - Goregek the Gorilla Hunter

### ISSUE THREAD

**Issue by Enskauning** [GameFreedomGG/Sindragosa#254]
Decription: The npc Goregek the Gorilla Hunter that should spawn and give you the quest Tormenting the Softknuckles does not spawn.

How it works: A npc should spawn when you accept the quest The Ape Hunter's Slave" from High-Shaman Rakjak

How it should work: The npc Goregek the Gorilla Hunter should spawn and give you the quest

Source (you should point out proofs of your report, please give us some source): https://smallbusiness.chron.com/start-oracles-quest-chain-28903.html   https://www.wowhead.com/npc=28214/goregek-the-gorilla-hunter#starts

**Comment by CeoOfCoronavirus** [comment]
when u accept the quest you receive an item in your bags that look like a pair of bracers. clicking on them will spawn the quest npc.
now im not sure if he should spawn automatically after accepting a quest but this is a minor issue.

**Comment by MrTide** [comment]
When you get this quest you will also receive a [small ball] thats how you summon the npc . there is no issue here. tested it in game .(https://www.wowhead.com/item=38619/goregeks-shackles)
