### ISSUE TITLE
[Dungeon][NPC] Shattered Halls - Kargarth

### ISSUE THREAD

**Issue by ramiobomb1998** [GameFreedomGG/Sindragosa#255]
Decription: I was doing Shattered Halls dungeon with a group, when we entered the last boss chamber [Kargath] he ended up spawning 3 adds at the same time which is incorrect and undoable.

How it works: 3 add at a time if I remember correctly.

How it should work: 1 add at a time if I remember correctly. (I might be mistaken though, I don't do that dungeon often but I'll leave the matter to the professionals.)

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/mQfErnv

**Comment by MrTide** [comment]
Hello
Player is right
1. mobs suppose to spawn one by one while they are spawning ![image](https://user-images.githubusercontent.com/36106057/148680137-a8a10896-885f-402b-aabb-c8f826c7bd5c.png)
2. there are ![image](https://user-images.githubusercontent.com/36106057/148679675-c0af931a-4189-4563-b1b1-f04bed965a2d.png) behind the boss according to the videos and research i have done i haven't seen any in there or atleast that close to the platform in this video you can see players are running to back of the platform and there are no assassins to attack them. https://www.youtube.com/watch?
3. those assassins are suppose to spawn when you are close to stairs or outside of the platform ( they are spawning that part is working correctly)
https://tbc.wowhead.com/npc=16808/warchief-kargath-bladefist#comments:id=2829371

----------

So proper fix in my opinion would be removing those three assassins' behind the boss and making sure one add is spawning on phase change every 20 sec.
