### ISSUE TITLE
[Core][Dungeon] Zeppelin inside Dungeon

### ISSUE THREAD

**Issue by JustNao** [GameFreedomGG/Sindragosa#257]
Decription: joining a random dungeon while on a zeppelin can bring the zeppelin inside the dungeon. It has physics so it can block the path.

How it works: join a random dungeon while on a zeppelin.

How it should work: not bring the zeppeling along with the player ?

Source (you should point out proofs of your report, please give us some source): screenshot https://imgur.com/a/bJkQZLp.

**Comment by MrTide** [comment]
Hello
This is just a visual bug and can be resolved with /reload.
its not really a bug so this issue can be closed.
