### ISSUE TITLE
[Item] Indestructible Potion

### ISSUE THREAD

**Issue by Selot1234** [GameFreedomGG/Sindragosa#258]
Decription: Indestructible Potion when used pre pull, is unable to use for 2nd time during fight. Multiple people in guild noticed this bug.

How it works: Indestructible Potion when used pre pull, is unable to use for 2nd time during figh

How it should work: As normal potion, could be used for during fight when CD falls off (if used pre pull ofc)

Source (you should point out proofs of your report, please give us some source): link to vid with bug:
https://streamable.com/njmtif

Look on right side of UI for keybind F2, i tried to click it multiple times but it only got "lighted" not used.
Happened every fight.

**Comment by MrTide** [comment]
I have tested this multiple times on multiple characters i had no issues on any of them
I would assume its your addons that are interfering with your potions or its your faulty cache, next time try to use it from your inventory.
