### ISSUE TITLE
[NPC] Pustulent Horror

### ISSUE THREAD

**Issue by Ambrusius** [GameFreedomGG/Sindragosa#260]
Decription:
Pustulent Horror's arent dropping (or has a very low chance of dropping) the Flesh Giant Spine for the neutrilizing the plague daily quest
How it works:

How it should work:
normally should drop in 1-5 kills
Source (you should point out proofs of your report, please give us some source): i farmed the horros for about 40 min, no drop

**Comment by MrTide** [comment]
Between 10kills that i had it dropped 3times while drop rate is suppose to be 4% i believe its dropping more than it should
I don't see an issue here
this can be closed
https://wotlk.evowow.com/?item=44009#dropped-by
