### ISSUE TITLE
[Hunter][Pet] Sapped

### ISSUE THREAD

**Issue by bestdkworld** [GameFreedomGG/Sindragosa#261]
Decription: When u send you pet on a target u can get saped

How it works:When u send you pet on a target u can get sapped till it hits it

How it should work: As soon as you send your Pet you can't get saped anymore

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
?????? come again

**Comment by Soufly** [comment]
Trying to translate:  the pet doesn't put u in combat while running towards your target,only when it reach is ??

**Comment by UltraNix** [comment]
@Soufly And in this case it's a bug? Player should be put in combat if command pet to attack? It seems to be okay now.

**Comment by Soufly** [comment]
The pet should not put u in combat after /petaatack command..not sure how it workson sindragosa.

**Comment by UltraNix** [comment]
So it's not a bug.

**Comment by Soufly** [comment]
Yeah, close
