### ISSUE TITLE
[Warlock][Talent] Demonic Pact

### ISSUE THREAD

**Issue by hexmonkey123** [GameFreedomGG/Sindragosa#262]
Decription: Demonic Pact - demonology warlock talent - is not working properly

How it works: Whenever your pet crits after the 20s internal CD, your spell power stacks up more and more but it only takes the highest spell power value on your character. For example: Spell power - 2000. First proc of 10% will get you to 2200. The next proc will get you to 2220 sp. The next proc will get you to 2222 sp. Everytime it adds another 10% of the current active demonic pact. Also it wont refresh after the internal CD if your spell power is lower than the current highest proc of DP meaning - If i have 2000 SP and i proc DP for extra 200 SP and my trinket for 500SP procs with it as well, i get 250 SP on my next demo pact (10% of 2000 and 10% on 500). After my trinket runs out. i get back to 2250 SP, but the next crit on the pet wont refresh the duration of DP, because the trinket that gave the extra SP is stacked with the current DP.

How it should work: It should refresh AFTER 20sec internal CD on demonic pact on EVERY crit pet makes, regardless of your spell power, and it should always calculate your current spell power minus the existing demonic pact buff - so if i have 2000 SP active, i proc DP i get to 2200 SP, the next proc should happen after 20s on a crit from the pet and i should get 2200 SP again, on LIVE server you get 2220 SP instead. The 10% bonus always adds up and it's bugged. Then you reach a max amount of SP and u cant refresh the duration which results in downtime of the buff itself because it relies on pet rng crit. 

Source (you should point out proofs of your report, please give us some source):

https://www.twitch.tv/videos/1219082225 - at around 2minutes i say it shouldnt reapply but it did, because it added another extra spell power - bug

here you see i applied fel armor which is around 400SP boost. Then i removed it, and the DP did not refresh because i had WAY lower spell power. It always SHOULD refresh after 20s internal CD based on current Spell power minus the Demonic pact buff.

**Comment by Godmatik** [comment]
Bump - this needs attention

**Comment by FixWarlock** [comment]
Up.

**Comment by kinh99** [comment]
Up, bump, fix this, please! It's terrible to play like this as a demo and also has a big impact on the raid.

**Comment by Godmatik** [comment]
bump again

**Comment by Godmatik** [comment]
hello?
