### ISSUE TITLE
[Dungeon][NPC] TBC Missing Loot

### ISSUE THREAD

**Issue by Heeyhoo** [GameFreedomGG/Sindragosa#268]
Decription: I have been running heroics a lot recently in classic tbc (Mana Tombs HC, Slave Pens HC, etc) and didn't receive loot form last boss of the dungeon.
How it works: Last boss in all TBC hc dungeons drop 1x epic item and only 1x rare (blue) item.

How it should work: Last boss should drop 1x epic and 2x rare (blue) items (loot table contains 10 rare items).

Source (you should point out proofs of your report, please give us some source): That how it worked on yours previous server Whitemane and every other server I know.

**Comment by MrTide** [comment]
Can confirm even with my path of adventurer i can't get the intended loot
retail videos of the loot as you can see there are atleast 2 equip able blue/rare items

https://www.youtube.com/watch?v=2DiAudIIb9c
https://www.youtube.com/watch?v=z_2NSy6HFS8

-----------------------

Quagmirran

![image](https://user-images.githubusercontent.com/36106057/148930756-6618e3ff-f0c3-4272-b1b2-19a6f6b16e25.png)


Nexus Prince Shaffar

![image](https://user-images.githubusercontent.com/36106057/148930849-80372587-62c1-40a7-ac8e-58d6d7bb8e21.png)
