### ISSUE TITLE
[Quest][NPC] Proof of Demise: Anub'arak - Annoying NPC

### ISSUE THREAD

**Issue by Klappy1** [GameFreedomGG/Sindragosa#269]
Description: The daily quest Proof of Demise: Anub'arak has a smaller version of the boss right behind the quest giver.  This smaller version makes the same noise as the boss all day long while spinning in a circle.

How it works: Loud boss noises in the middle of Dalaran all day.

How it should work: It should not make noise.

Source (you should point out proofs of your report, please give us some source): Go stand in Dalaran by the quest giver today while the quest is active.

**Comment by zalger** [comment]
U can hear it near the fountain too! Solution? Leave Dalaran and explore XD

**Comment by Godmatik** [comment]
It's "fixed" for now, someone (perhaps Jimmy) simply removed the NPC from the viewing area when it is Anub'arak heroic daily, now no more annoying sounds.

![WoWScrnShot_011722_113847](https://user-images.githubusercontent.com/37913400/149815962-bfb32b42-2351-4482-ac2a-1cafa5a9486d.jpg)

**Comment by MrTide** [comment]
It is most likely what happened (jimmy removed it)
Npc had issues with its stand state and was making noises 
Probably a dev can re-add the npc and fix its stand state

**Comment by MrTide** [comment]
Its still happening not resolved.

**Comment by MrTide** [comment]
Not fixed yet ... opening it again
