### ISSUE TITLE
[Raid][NPC][Spell] Obsidian Sanctum - Vesperon - Twilight of Torment 

### ISSUE THREAD

**Issue by hexmonkey123** [GameFreedomGG/Sindragosa#272]
Decription: OS 25 +3 boosted version bug/glitch with twilight of torment ( Acolyte of Vesperon ability )

How it works: After Vesperon portal spawned, for some reason nobody from the raid got the Twilight Torment debuff the acolyte of vesperon casts while inside the portal realm. 

https://gyazo.com/c737b7ec5b12011e83625290a050a801

How it should work: After Vesperon spawns his portal and the acolyte inside it, the whole raid gets a debuff that affects them with reflective damage upon hitting/casting spells on any target. Inside and outside of the realm. After the add dies inside the realm, the debuff is removed.

https://gyazo.com/c5219e8b940cfd2da229bd508a8123a3

Source (you should point out proofs of your report, please give us some source):

Potential reason why it might've been bugged for them

https://gyazo.com/622568f44d018600471f5e411a244997

Evidence below:

https://clips.twitch.tv/LaconicSingleKittenGingerPower-XK68zsZk-VPd6tsG

**Comment by UltraNix** [comment]
I can't reproduce it.

**Comment by Godmatik** [comment]
@UltraNix 

It occurs if you enter the portal before Vesperon applies the debuff. Then inside the portal you will not get it. 

If you already have the debuff (from being outside when it was cast), going inside the portal you will still have it.
