### ISSUE TITLE
[Item] Braxley's Backyard Moonshine

### ISSUE THREAD

**Issue by Polaczek7** [GameFreedomGG/Sindragosa#275]
HELLO

I found a bug with a trinket ( [Braxley's Backyard Moonshine] )

After using the item, the drunk effect does not disappear even after logging out and restarting the game. The only thing that helps is death.

**Comment by Godmatik** [comment]
Confirmed, this was bugged on Sunwell servers also.

**Comment by UltraNix** [comment]
That's how drunk effect works. And drunk effect on this trinket is quite strong.

**Comment by Godmatik** [comment]
It is a bug, what is he saying is that drunk effect NEVER goes away unless the character is killed off

**Comment by UltraNix** [comment]
@Godmatik I just tested and the drunk effect has gone after a while.
