### ISSUE TITLE
[Quest][NPC][Item] I'm Stuck in this Damned Cage... But Not For Long! - Festering Ghouls - Engine-Core Crystal

### ISSUE THREAD

**Issue by ramiobomb1998** [GameFreedomGG/Sindragosa#276]
Decription: Hello, I've been doing the quest with the same name as the title and the Festering Ghouls won't drop the item [Engine-Core Crystal] needed for the quest.

How it works: I kill mob, item drops.

How it should work: Should receive it upon loot

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/LXKUNPL

**Comment by MrTide** [comment]
Drops without an issue
make sure you are not in raid group
![image](https://user-images.githubusercontent.com/36106057/148648533-3144cd50-0143-40db-9221-8bbdec7baf37.png)
