### ISSUE TITLE
[Item] Greaves of Turbulence

### ISSUE THREAD

**Issue by David12sdf** [GameFreedomGG/Sindragosa#279]
Decription:Greaves of Turbulence stats bugged

How it works:I Have Bolstered Legplates 123stam+[55stam ench+12stam gem+6stam socket bonus] =196 stam
And i replaced it with Greaves of Turbulence 150stam+[55stam ench] =205stam
But i have 260 less HP
How it should work:It should be 9 more stam,not 26 less.

Source (you should point out proofs of your report, please give us some source):

**Comment by Godmatik** [comment]
I'm going to guess 95% sure that he deactivated the 32 stamina meta socket when he switched pants
