### ISSUE TITLE
[Item] Noggenfogger Elixir

### ISSUE THREAD

**Issue by Ek-oh** [GameFreedomGG/Sindragosa#282]
Description:
Noggenfogger Elixir breaks auto attack.

How it works:
When a female blood elf drinks the Noggenfogger Elixir they can no longer auto attack. The issue will persist until you log out and back into the character.

How it should work:
Your auto attack should not be unusable when you drink Noggenfogger Elixir.

Source (you should point out proofs of your report, please give us some source):
Had this bug happen to me on my Female BE pally in Hellfire. I was able to replicate the bug by drinking another Noggenfogger Elixir.
The work around for me was logging out of the character and then logging back in. Everything works normal after that until you drink another Noggenfogger. 

*Had a friend try on a female orc character and they had no issues.

**Comment by MrTide** [comment]
I have tested this multiple times on multiple zones i don't think there is an issue with

**Comment by Loken-Whitemane** [comment]
Reopening this, multiple sources have told me recently this potion is interfering with their auto attacks, at a very random consistency
