### ISSUE TITLE
[Hunter][Spell] Freezing Trap Visible

### ISSUE THREAD

**Issue by rafako47** [GameFreedomGG/Sindragosa#283]
Decription:
Traps invisibility problem

How it works:
Sometimes(not always) during battleground/arena/world pvp hunter in opposing team leaves a visible to me trap.(so i assume my traps are visible to enemy too)

How it should work:
All traps (with exception of friendly traps) should remain hidden.

Source (you should point out proofs of your report, please give us some source):

on this picture you can see frost/freezing trap laying down on ground while my is still ready to use. That trap belongs to horde player(i am in alliance)
![WoWScrnShot_120421_111756](https://user-images.githubusercontent.com/95524232/144707560-63d81c34-436d-4273-b4b3-177b0e27eebf.jpg)

here you can see 11/9 players in Warsong Gulch
![WoWScrnShot_120421_102336](https://user-images.githubusercontent.com/95524232/144707811-8264d423-0598-4e9b-b409-811b51d7f20a.jpg)

Here i am targetting a player "Mejch"(the one on blue horse with green circle under him indicating "ally") who is listed in Alliance team while he is fighting for Horde side, could it be related to trap problem? Could game think enemy is ally so traps remain visible? Just one of possibilities...
![WoWScrnShot_120421_102344](https://user-images.githubusercontent.com/95524232/144707589-18031989-89f3-475f-8c78-b63bc953546e.jpg)

**Comment by Godmatik** [comment]
Close please, was already fixed by Jimmy
