### ISSUE TITLE
[Profession][Quest][Item] Herbalism - The Mystery of Morrowgrain - Morrowgrain

### ISSUE THREAD

**Issue by VanillaPinnk** [GameFreedomGG/Sindragosa#284]
Decription: I took the Herbalism quest and when i got to Feralas i got a followup quest to collect Morrowgrain, it's called The mystery of Morrowgrain" .

How it works: I collected already 20 Un'goro soils and used maybe 19 Packet of Tharlendis seeds, and didn't get even 1 Morrowgrain.

How it should work: You get an Evergreen pouch and you need to collect Un'goro soils and get Packet of Therlendis seeds, "Consume two Un'goro soils and a Packet of Tharlendis seeds to make an Evergreen Gerb Casing" In that Casing there suppose to be Morrowgrain.

Source (you should point out proofs of your report, please give us some source): I spoke with a GM ingame and asked him about it, he looked it up and said i should report it here.
![WoWScrnShot_120421_180322](https://user-images.githubusercontent.com/95539079/144716384-3cf842eb-20e5-46ab-a54a-4fed888995b3.jpg)
![WoWScrnShot_120421_180341](https://user-images.githubusercontent.com/95539079/144716388-7c097ef5-0fea-45e5-930c-1cc2ee99a658.jpg)
![WoWScrnShot_120421_180347](https://user-images.githubusercontent.com/95539079/144716391-5020803e-6a40-4349-b7d5-0bf2c34a7c8a.jpg)

**Comment by MrTide** [comment]
Can confirm seems like its missing from loot table

**Comment by UltraNix** [comment]
Looks okay. Loot table on the live server is okay.

**Comment by MrTide** [comment]
@UltraNix I think i know what's happening here its the path of the adventurer causing the issue would you please kindly check one more time with path of the adventurer ?

**Comment by UltraNix** [comment]
Yep - that's the problem.
