### ISSUE TITLE
[Quest][NPC] The Rider of Frost - Sapph

### ISSUE THREAD

**Issue by ProtQ** [GameFreedomGG/Sindragosa#289]
Decription:
Quest dont works
How it works:
When u kill Sapph, Quest is not completed.
How it should work:
When u kill Sapph, Quest should be completed
Source (you should point out proofs of your report, please give us some source):
Quest Rider of the Frost
![WoWScrnShot_120521_222840](https://user-images.githubusercontent.com/95591409/144764772-d8ab43f3-2e6c-4127-9b78-7ad0dda5b23f.jpg)

**Comment by MrTide** [comment]
Works without an issue probably player was in raid group
![image](https://user-images.githubusercontent.com/36106057/148648401-07ca1040-c6bd-4d63-95be-58e17865019f.png)
![image](https://user-images.githubusercontent.com/36106057/148648406-b72a3851-f35d-4233-98d5-0123e1edf872.png)
