### ISSUE TITLE
[Hunter][Spell][Raid] Trap not Triggering

### ISSUE THREAD

**Issue by dreamk33per** [GameFreedomGG/Sindragosa#292]
When I place my traps directly under Sartharion, they just sit there and do not trigger.

How it should work: When I enter the maximum melee range of the boss, a.k.a when I can no longer use my ranged abilities and place my traps, they should trigger every time.

Please fix this, it is really annoying.
![Trap bug OS](https://user-images.githubusercontent.com/72185738/144895018-fa630002-42fa-4eb6-814a-aa78576de8ac.jpg)

**Comment by UltraNix** [comment]
@dreamk33per I cannot reproduce it.

**Comment by Soufly** [comment]
its just the boss visual,his hitbox is way smaller ... close

**Comment by UltraNix** [comment]
@Soufly I placed my trap in the same spot and worked okay.

**Comment by Soufly** [comment]
yeah close. @UltraNix
