### ISSUE TITLE
[Raid][NPC][Spell] Naxxramas - Gluth - Decimate

### ISSUE THREAD

**Issue by Pepek241** [GameFreedomGG/Sindragosa#293]
Decription: Gluthʼs decimate can one shot you.

How it works: Gluthʼs decimate can deal more dmg to you then your actual HP.

How it should work: 
Decimate:
Reduce the current health of all nearby units (friendly or enemy) to 5% of their maximum health. Affects both players and zombies. Used approximately every 90 seconds.

Source (you should point out proofs of your report, please give us some source): It occured during 10man Naxx.
Screenshot from recount death recap:

![image](https://user-images.githubusercontent.com/95646548/144896325-a111aa6c-7fbf-428e-8a69-15bd3db79425.png)

**Comment by Godmatik** [comment]
We've noticed the same - and I believe it is caused because of the debuff from the zombies
