### ISSUE TITLE
[Mage][Spell] Mirror Image

### ISSUE THREAD

**Issue by zalger** [GameFreedomGG/Sindragosa#295]
Decription: When mages Mirror Image ends  the mage gets 4M threat.

How it works: Mage is taunting da boss! Have it on record (omen mid top of the screen, next to target), doesn't happen on all boses, looks like happening on bosses with threat-reset mechanics like noth, gothik or  even Skarvald (Utgarde Keep)

How it should work: Mage shouldnt get 4M threat

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=BRTQC4FQVKg

**Comment by UltraNix** [comment]
@zalger Need more info. Mage used Mirror Images after the Noth's blink?

**Comment by Soufly** [comment]
Either the enemy reset his agro or this https://github.com/SunwellTracker/issues/issues/1502

**Comment by UltraNix** [comment]
@Soufly Tell me if mirror images should transfer their threat to owner?

**Comment by Soufly** [comment]
https://youtu.be/2yS_fC9ti9w?t=85 they should ''steal'' your agro when they are up.After that u either use invisible or u die.
Mirror Images cause you to temporarily drop threat. You will still generate threat during this time.

Image Aggro works as such:
If you had aggro on cast, the boss will attack your images (until taunted or images die).
If you didn't have aggro on cast, the boss will ignore your threat and images (Placing you at the bottom of the threat table)

**Comment by UltraNix** [comment]
So this is the case here?

**Comment by Soufly** [comment]
@UltraNix my edited post above says it all,gl.

**Comment by zalger** [comment]
> @zalger Need more info. Mage used Mirror Images after the Noth's blink?

no, he used it at start of encounter. It's quite well known bug to sunwell tanks https://github.com/SunwellTracker/issues/issues/1502 an ye, its same here, just wanted to mark it still exists. 

As far as i know its connected to threat system or smtg like that and 'to repair it u'd have to write new threat system', but i have no idea how programming works and i was talking about it with some dev on other server like years ago so im not sure what im talking about here xd

**Comment by UltraNix** [comment]
Already fixed. I don't know if it's live.
