### ISSUE TITLE
[Quest][Item] Elemental Power Extraction - Elemental Power Extractor

### ISSUE THREAD

**Issue by johnsmith534** [GameFreedomGG/Sindragosa#297]
For this quest you use an Elemental Power Extractor on either Sundered Rumblers or Warp Aberrations to extract Elemental Power from them. Using the extractor does nothing currently.

**Comment by MrTide** [comment]
Quest working as intended
Once you used quest item you are suppose to kill it then another Blue like Crystal will drop under it which you can loot for your quest item 
![image](https://user-images.githubusercontent.com/36106057/148647504-56628be2-e744-49ab-b520-45d9e72093d7.png)
![image](https://user-images.githubusercontent.com/36106057/148647523-b28867a4-b480-4822-a1e0-cdbe92fc3d11.png)
