### ISSUE TITLE
[NPC][Pathing] Artificer Daelo

### ISSUE THREAD

**Issue by Raulfin** [GameFreedomGG/Sindragosa#298]
Decription:

How it works:
Artificer Daelo (17222) is almost always patrolling and only stops at his standing location (48.37, 50.27) for a few seconds.

How it should work:
He should normally be found at 48.37, 50.27 under the lean-to on the Inn, by the shaman trainer. Patrols should be less frequent.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
I didn't notice any issues with this npc.. he stops at his original location for about 10sec and also goes around patrolling waiting couple seconds on his every intended stop points and throwing out comments.
I also didn't find any source that confirms or denies player claim.
And assuming player didn't include one either this issue can be closed.
