### ISSUE TITLE
[Priest][Spell] Mind Control

### ISSUE THREAD

**Issue by Soundmanone** [GameFreedomGG/Sindragosa#301]
Decription:
Mindcontroll bug in pvp
How it works:
Mind controlling someone breaks after ur hit with 1 hit
How it should work:
Mc shouldnt get canceled with 1 hit
Source (you should point out proofs of your report, please give us some source):
https://youtu.be/cYe3jSGqJ_s

**Comment by Loken-Whitemane** [comment]
How it works:
https://streamable.com/ntj5hp

How it should work:
https://streamable.com/dqhrue

@UltraNix

**Comment by UltraNix** [comment]
@Loken-Whitemane Are you sure that MC should not be interruptable by direct damage?
