### ISSUE TITLE
[Quest][NPC] Exarch Orelis, Anchorite Karja, Adyen the LIghtwarden

### ISSUE THREAD

**Issue by 1000hi** [GameFreedomGG/Sindragosa#305]
Decription: 

The Npcs concerned  : 
- Exarch Orelis
- Anchorite Karja
- ( Adyen the Lightwarden ) 
They are not located where they supposed to be, and it is impossible to take any quest from them or give back any to them.

Here they actually  are : 
![image](https://user-images.githubusercontent.com/22479945/145226099-5cab6836-fe4f-49ec-ab01-c28264f52fca.png)
 Where they supposed to be : 
![image](https://user-images.githubusercontent.com/22479945/145227924-15407252-6e03-4c37-9482-3c80c5906160.png)

How it works:
They are possibly in the state of the last quest from this quest chain --> https://tbc.wowhead.com/quest=10507/turning-point
But they dont seem to have been reset.

How it should work:
They should be in the inn of area53 and give the correct quests :

- https://tbc.wowhead.com/quest=11038/assist-exarch-orelis
- https://tbc.wowhead.com/npc=19467/anchorite-karja

I check on another server (cataclysm but doesnt matter) : 

![image](https://user-images.githubusercontent.com/22479945/145227589-b14d0ceb-491d-4575-9b5c-b96938a207ec.png)

Source (you should point out proofs of your report, please give us some source):
https://tbc.wowhead.com/npc=19467/anchorite-karja
https://tbc.wowhead.com/quest=11038/assist-exarch-orelis

**Comment by MrTide** [comment]
Yes i can confirm this they are missing

**Comment by MrTide** [comment]
Looks like something went wrong
Npc's are spawning on wrong location they should be in area 52 as well but instead they are spawning inside of eachother
![image](https://user-images.githubusercontent.com/36106057/151702640-faca578f-4fd8-4444-a491-4d3960ee5339.png)
