### ISSUE TITLE
[Quest][NPC] Amped for Revolt! - NPCs Missing

### ISSUE THREAD

**Issue by Daniel33015** [GameFreedomGG/Sindragosa#309]
Decription:
When flying the ship, there are no monsters to kill
How it works:
You are flying a special ship whose cannons are fired at the NPC
How it should work:
During the flight with stark you will be doing monsters for q eg Gargoyle
Source (you should point out proofs of your report, please give us some source):
![1](https://user-images.githubusercontent.com/95860354/145397881-2bea2214-b807-43ef-9268-7ea89ae92089.jpg)
![2](https://user-images.githubusercontent.com/95860354/145397884-2620b5b0-694c-4711-aeec-61ab00aedd8f.jpg)

**Comment by MrTide** [comment]
This quest was added at [patch 3.3.0] i am not sure if its intended to remove these gargoyles or not but they are surely not ingame atm (https://www.wowhead.com/quest=13374/amped-for-revolt)
