### ISSUE TITLE
[Quest][NPC] Gambling Debt - "Silvermoon" Harry

### ISSUE THREAD

**Issue by TheAlkatrazAlky** [GameFreedomGG/Sindragosa#310]
Decription: Quest - Gambling Debt ID: 11464 

How it works: NPC dies and does nothing

How it should work: NPC should "give up" after certain amount of damage and give you "debt".

Source (you should point out proofs of your report, please give us some source):
![dead](https://user-images.githubusercontent.com/71934071/145414658-c7e4de39-20c2-409b-ad72-570c297b4c09.png)

**Comment by MrTide** [comment]
This happens when you do so much damage to him really fast .. basically works fine if you go without any weapon and go slow .. would be nice to get a proper fix for this.
