### ISSUE TITLE
Quest - lost! ID:4492

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#311]
Decription:
https://prnt.sc/22h0dd1

GM told me this bug was happening before and it's back so im here to report this.

How it works:
The Ringo is not there even if nobody is doing the escort.

How it should work:

The ringo should be there and we should be able to do quest.

Source (you should point out proofs of your report, please give us some source):

https://classic.wowhead.com/quest=4492/lost

**Comment by MrTide** [comment]
Tested it working without an issue
![image](https://user-images.githubusercontent.com/36106057/148644181-5e33c4a8-b917-4a75-aa65-26597271ed8d.png)
