### ISSUE TITLE
[NPC] Enraged Mammoth

### ISSUE THREAD

**Issue by Genni123** [GameFreedomGG/Sindragosa#314]
Decription: Enraged Mammoths in Zul'Drak do not drop any Chunk o' Mammoth and Chilled Meat. According to database, they should drop 1-2 on average. 

How it works: Enraged Mammoths do not drop Chunk' o Mamooth and Chilled Meat at all.

How it should work: Enraged Mammoths should have 76% chance of dropping Chunk o' Mammoth (1-2) and 27% chance of dropping Chilled Meat (1-2). 

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=28851/enraged-mammoth

**Comment by MrTide** [comment]
Chilled meat is not included in the drop list
https://wotlk.evowow.com/?npc=28851#drops:0-14+1
and Chunk o' Mammoth drops without an issue but drop rate is 1% which is pretty low got it on less than 30kills
We can close this report
