### ISSUE TITLE
[Raid][NPC] Molten Core - Ragnaros

### ISSUE THREAD

**Issue by JackieNL** [GameFreedomGG/Sindragosa#315]
Decription:
We killed all the bosses in Molten Core, but Majordomo won't spawn to talk at Ragnaros location in Molten Core.

How it works:
I've done the questline but this NPC in Azshara won't gief me more quests to continue..
How it should work:

Source (you should point out proofs of your report, please give us some source):
![WoW_mGURITejK7](https://user-images.githubusercontent.com/75321257/145543090-b3e009be-d0ad-4fd9-a98d-f85bd64edd1d.jpg)

**Comment by MrTide** [comment]
just incase if these information helps
This is how a GM fixes this issue for players
.npc add temp 12018 at the place that majordomo is located first time as an encounter  (players already finished the encounter and all of the bosses are dead)
kill the temporary boss we spawned > respawn and kill the previous boss and boom he spawns at rag encounter location and event works without an issue
