### ISSUE TITLE
[NPC][Pathing] Scorpid Worker

### ISSUE THREAD

**Issue by Frinzolli** [GameFreedomGG/Sindragosa#32]
Some mobs walk through terrain (mostly small hills) or on invisible ground (in which I can't walk on though)
![WoWScrnShot_102421_114433](https://user-images.githubusercontent.com/69170736/138588927-451f67d3-15dd-4364-b2dd-d170047f2b88.jpg)
)

**Comment by MrTide** [comment]
I investigated all of them one by one i don't see an issue here
