### ISSUE TITLE
[Hunter][Pet] Pet not targetable 

### ISSUE THREAD

**Issue by Hardkorowy** [GameFreedomGG/Sindragosa#320]
Decription:When my pet die, killed by player or.mobs his body disappear, I can't target him, can't recall him, can't revive and I can't tame new pet because is says I have already active pet... When I put this pet into stables I can tame new one but I can't retake from stables old one and it stays there forever

How it works:when pet die his body disappear and it cannot be ressurected

How it should work:when pet die, his body should be on the ground so I can ressurect him

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Can you please provide more info ? was it exotic pet ? did you change your talent from BM to something else ? and had issues after that ?

**Comment by Soufly** [comment]
Even if his corpse disappear,u can still revive him.. did that many times.It is working fine.

**Comment by Loken-Whitemane** [comment]
Closing this for now, unable to replicate. If it is still happening, let us know
