### ISSUE TITLE
[Druid][Talent] Nature's Grace

### ISSUE THREAD

**Issue by Kwyzard** [GameFreedomGG/Sindragosa#321]
Description: Nature Grace is a talent that proc on Critical hit from the Druid Spell that provide a flat 20% casting speed buff.

How it works: When you cast wrath you need to wait the impact on the target to get the crit and therefore get the Nature grace proc

How it should work: When you cast wrath and spell WILL critical hit, you should proc the buff 
It's a peculiar mechanic that give the information if you wrath will crit or not while flying in the air

Source : This wow head comment provide explanation of a burst mechanic you can do with the reign of unliving and the nature grace talent 
https://www.wowhead.com/item=47182/reign-of-the-unliving#comments:id=908516

> You can also sort of predict incoming wrath crits by tracking your Nature's Grace buff, so you can tell when a wrath flying through the air will crit.

**Comment by MrTide** [comment]
I believe this is one of the rarest spells that use prediction mechanic
also mentioned below which as you can see in the video its shown how it works
https://github.com/dalaranwow/dalaran-wow/issues/5079
