### ISSUE TITLE
[Druid][Talent] Typhoon incorrectly pushing NPCs

### ISSUE THREAD

**Issue by Conradacal** [GameFreedomGG/Sindragosa#328]
Decription:Druid balance talent  *Typhoon*

How it works: Sometimes pushes the mob sideways or towards the caster sometimes

How it should work: Pushes mob backwards 

Source (you should point out proofs of your report, please give us some source): bruh I can't record gameplay

**Comment by MrTide** [comment]
I used this spell over 200 times i didnt notice any issue with any type of mobs
![image](https://user-images.githubusercontent.com/36106057/148642683-3878628d-730b-428b-8d31-459bd12b71bb.png)
