### ISSUE TITLE
[Profession][Item] Fishing - Mr. Pinchy's Magical Chawdad Box

### ISSUE THREAD

**Issue by polischuk16** [GameFreedomGG/Sindragosa#332]
Decription: Unable to catch the box in terrokar forest

How it works: Caught over 2.000 crawdads from highland mixed schools, i've caught it before many times and it never took so many casts. Especially since daily Shirmpin' Aint Easy is not working, wouldnt be surprised if this is bugged as well

How it should work:

Source (you should point out proofs of your report, please give us some source):

**Comment by MorgenWotlk** [comment]
Bumping this. 

Been trying to go for Salty since day one of the server but also have not seen a single Box in roughly 1k casts

**Comment by UltraNix** [comment]
Mr Pinchy is in the loot table of Highland Mixed School. Chance: 0.5%.
