### ISSUE TITLE
[Quest][NPC]The Fate of Bloodbane - Orbaz Bloodbane Missing

### ISSUE THREAD

**Issue by Deenko** [GameFreedomGG/Sindragosa#334]
Decription:

Orbaz Bloodbane is missing from his usual spot, I waited for him to spawn but he is not there.
 

How it works:

The NPC is missing, and I am unable to finish the quest.

How it should work:

Orbaz Bloodbane should be standing in his spot, there should be a dialogue between him and Darion and then he dies.

Source (you should point out proofs of your report, please give us some source):

![WoWScrnShot_122221_030656](https://user-images.githubusercontent.com/92395368/147022910-a06e0b10-b34a-4f65-936d-c5892ea87c17.jpg)

![WoWScrnShot_122221_030650](https://user-images.githubusercontent.com/92395368/147022922-0b3d6ebd-a32b-4b72-bd4a-b768b30b011b.jpg)

**Comment by MrTide** [comment]
> Decription:
> 
> Orbaz Bloodbane is missing from his usual spot, I waited for him to spawn but he is not there.
> 
> How it works:
> 
> The NPC is missing, and I am unable to finish the quest.
> 
> How it should work:
> 
> Orbaz Bloodbane should be standing in his spot, there should be a dialogue between him and Darion and then he dies.
> 
> Source (you should point out proofs of your report, please give us some source):
> 
> ![WoWScrnShot_122221_030656](https://user-images.githubusercontent.com/92395368/147022910-a06e0b10-b34a-4f65-936d-c5892ea87c17.jpg)
> 
> ![WoWScrnShot_122221_030650](https://user-images.githubusercontent.com/92395368/147022922-0b3d6ebd-a32b-4b72-bd4a-b768b30b011b.jpg)

Please provide more info .. which quest is this .. this is a multi phase area, tell us which quest you are at so we can do proper testing..
by the look of it Orbaz bloodbane is at phase one and those bombs are at phase 10. still we need to find out what quest is he on to do proper testing
![image](https://user-images.githubusercontent.com/36106057/148642422-6d4327da-3ab6-4007-8cfa-6479e7f27d66.png)
![image](https://user-images.githubusercontent.com/36106057/148642432-09551f94-90ce-43dd-990b-97619625da02.png)

**Comment by Soufly** [comment]
He is there,close.
