### ISSUE TITLE
some gear lost

### ISSUE THREAD

**Issue by eddyedis** [GameFreedomGG/Sindragosa#335]
Decription:DPS gear lost

some of my gear lost, my char name is Edisi(troll warrior) 

DPS Hands,Wrist,Feet and Legs...it may be addon autosell but maybe just a bug...

**Comment by Godmatik** [comment]
Not a bug, open a GM ticket for them to restore your gear however it was misplaced.

**Comment by Loken-Whitemane** [comment]
Matik is correct, please put in a GM ticket for this.
