### ISSUE TITLE
[Warlock][Talent] Backdraft

### ISSUE THREAD

**Issue by UllabrittaFittasmitta** [GameFreedomGG/Sindragosa#336]
Decription: Wierd interaction betwen glyph and talent proc

How it works: When you get proc from glyph of corruption and the Backdraft talent at the same time you cant use shadow bolt instant cast in before you use 3 spells or cancel the talent proc

How it should work: You should be able to use shadow bolt instant cast any time because backlash talent proc works fine

Source (you should point out proofs of your report, please give us some source): https://i.gyazo.com/b58f4b7ab5868af2d2f7d89abc5f7d85.png

**Comment by MrTide** [comment]
By the look of it according to [gamepedia fandom] and [this ](https://wowpedia.fandom.com/wiki/Backdraft)(https://wowpedia.fandom.com/wiki/Nightfall_(warlock_talent))
this issue didn't get looked at until cata patch.

 Patch 2.0.3 (2007-01-09): When a Warlock is under the effects of  [Backlash] and Nightfall, only one of the effects will be consumed by a Shadow Bolt cast.
 
 Hotfix (2011-02-18): Instant-cast Shadow Bolts from Shadow Trance (both the talent and  [Glyph of Corruption] versions) should no longer consume charges of Backdraft if both procs are available. Shadow Trance will always take priority and be consumed first when Backdraft is active. Subsequent Shadowbolts will consume Backdraft stacks.
