### ISSUE TITLE
[Warrior][Spell] Berserk Stance

### ISSUE THREAD

**Issue by Sruczczi** [GameFreedomGG/Sindragosa#338]
Decription:Warrior crit bug

How it works: When i se to bersek i get +3% crit then when i back to def or battle stance i have -6% and i need relog for fix. After use bersek stance it get buged again

How it should work: bersek stance+3% crit and other stances 3% less crit than in berseker stance

Source (you should point out proofs of your report, please give us some source):

https://user-images.githubusercontent.com/96195775/147416167-e622ded9-8134-493b-b827-ce9c33cd3704.mp4

**Comment by danniellos94** [comment]
I have the same problem with the talent blood gorged when I change spec from blood to blood I sometimes 'lose' 10% of damage in the table, but the damage seems the same alt+f4 solves the problem. I remember on mograine asking and kalt said this is most likely a visual bug however if you think its not you can test it with autoattacks on dummy to have proof.

**Comment by Sruczczi** [comment]
I think its not visual

**Comment by Loken-Whitemane** [comment]
I could not reproduce this, I think it might be visual. Tested on Live, PTR & also had another test, Rage seems to be fine.
