### ISSUE TITLE
[Core] Slow

### ISSUE THREAD

**Issue by Sajaqtx** [GameFreedomGG/Sindragosa#34]
Slow spells subtract percentages of movement speed instead of applying a slow ratio. You can see this on higher based movement speed mobs. (like Elite in dungeons)

For example with 150% movement speed with 60% ms reduction
How it actually works on PTR :
 150-60 = 90

How it should works : 
150x(1-0.60) = 60

**Comment by UltraNix** [comment]
60% speed reduction is not the same as 1-0.6.
1 is the base. Everything below 1 is reduction, so it must be calculated by 0.xxx, just like everything above 1 is calculated as 1.xx.
60% is not 40% of your speed, but 0.6 of your base speed.
E.g. your base speed is 8. With 60% reduction speed, you speed is 4.8, not 3.2

**Comment by UltraNix** [comment]
It works like: 1.5 + (1.5x(-0.6)) = 0.6.
![obraz_2022-01-10_113617](https://user-images.githubusercontent.com/80540499/148752200-a8c0bc0b-de64-4777-9605-318ae09a8fd7.png)

My base speed without buffs/debuffs is 7. With sprint(+50%) and poly (-60%), it's 0.6 of base speed (1.5x(1.5-0.6))
