### ISSUE TITLE
[Quest][NPC] If Valgarde Falls... - Dragonflayer Invaders/Worgs

### ISSUE THREAD

**Issue by sjoerdinio112** [GameFreedomGG/Sindragosa#341]
Decription: the npc spawn too quick so it is very hard to complete it 

How it works: if you kill one npc the next respawns in 5 sec 

How it should work: it should work so that the npc respawns every minute or so except if it is bussy

Source (you should point out proofs of your report, please give us some source): if you try the quest it will do what i just discribt

**Comment by MrTide** [comment]
Can confirm i believe the problem is their corpse delay they simply respawn too fast after dying. (might be related to dynamic respawn rate all the creatures around the world spawn too fast i am told its getting fixed so its better to wait until fix is applied then i will test this again.)

**Comment by UltraNix** [comment]
Look at some videos, the respawn timer should be quickly. In my opinion not a bug.
