### ISSUE TITLE
[Quest][NPC] Supplies to Private Thorsen - Private Thorsen

### ISSUE THREAD

**Issue by Jebani** [GameFreedomGG/Sindragosa#342]
Decription: NONE

How it works: Quest is done, but it's not available for completing. 

How it should work:  Quest is automatically done, and the quest NPC should accept it.

Source (you should point out proofs of your report, please give us some source):
![RrRJ-3uwSSu-bWLoS8K9TQ](https://user-images.githubusercontent.com/96847726/147708406-bb39057a-4535-4b05-b5a5-6f57202a696a.png)
![pXwVJJs7RrWDspzRjoe-cQ](https://user-images.githubusercontent.com/96847726/147708411-20077f20-cf3e-4c3e-a895-cccae9cb7f6f.png)
![jAB0PkUTRRyIz0Y_i-UJYA](https://user-images.githubusercontent.com/96847726/147708414-44767b0f-ef92-4341-9208-29054fce67d4.png)

**Comment by Godmatik** [comment]
yeah confirmed, can't turn it in until he patrols away

**Comment by UltraNix** [comment]
https://classic.wowhead.com/quest=198/supplies-to-private-thorsen#comments:id=2931005
Not a bug.
