### ISSUE TITLE
[Item] Flask of the North

### ISSUE THREAD

**Issue by ZazuiNine7** [GameFreedomGG/Sindragosa#344]
Decription: Flask of the North (Flask made by alchemists only for alchemists that gives 80 Attack power 47 Spell power or 40 strength) This is a core game piece, and should be fixed and work properly.

How it works: DOES NOT GIVE 80 ATTACK POWER AT ALL

How it should work: SHOULD GIVE 80 ATTACK POWER, NOT JUST 47 SPELL POWER OR 40 STRENGTH

Source:
Get one in game and test it for urself, i've been non stop spamming it for a week, nothing in terms of Attack power at all.

Kind Regards.

**Comment by MrTide** [comment]
It depends on what class you are 
for example if you are a paladin you will get str+spellpower if you are a shaman you will get spell power and attack power 
https://cdn.discordapp.com/attachments/448057838263336961/929321134825017364/unknown.png
more info can be found here
https://www.wowhead.com/item=47499/flask-of-the-north
---------------
If you are a druid you wont get AP after 3.3.x patch changes
"As of 3.3 this flask gives either a Spellpower or Strength buff to druids, meaning you have to click it twice and/or mouse over the buff to make sure you got the one you want. There is currently no widely known way to always get one or the other with either an addon or a macro."
https://wowwiki-archive.fandom.com/wiki/Flask_of_the_North
---------------
I didn't find anything wrong with the flask so far.
