### ISSUE TITLE
Violet Hold Heroic instance loot

### ISSUE THREAD

**Issue by LDave13** [GameFreedomGG/Sindragosa#345]
Decription:
We have a problem with Violet Hold Heroic mode loots.

How it works:
It drops  [Bolstered Legplates] and [Gauntlets of Capture] for 4 days already. We completed the instance with guildmates, both on Random Heroic finder and direct Heroic joining.

How it should work:
Based on AtlasLoot, both 2 items drop rate is around 20-21% as [Mark of the War Prisoner] also. Or at least it should drop the items more differently through days, not the same two epic and rare item for 4 days.

Can you please check it?
Thank you in advance!
In game contacts: 
Ccab, the affected and the ingame reporting player
Szentszr, the GitHub reporting player

**Comment by Godmatik** [comment]
RNG is RNG, you could run it 100 times and it won't drop the trinket you want.

You're falling for this:
https://en.wikipedia.org/wiki/Gambler%27s_fallacy

No bug here.

**Comment by LDave13** [comment]
Okay, thank you. Just wanted to be sure as it dropped the same loot for days.
