### ISSUE TITLE
[Profession][Item] Herbalism - Firethorns not dropping Fire Leaf

### ISSUE THREAD

**Issue by Mrldmz** [GameFreedomGG/Sindragosa#346]
Description: I was gathering plants in Borean Tundra. After gathering some Firethorns, I noticed that I got 2 full stacks of Fire Seeds but not a single Fire Leaf.
My Character's Data:
 Race: Tauren.
 Class: Druid.
 Herbalism Skill: 444/465 (at the time of this report).
 Racial abilities changed: No.
 Path chosen: of the Adventurer.

How it works: No Fire Leaves are dropping from any Firethorn plant, even the ones I have seen spawn to make sure nobody else got part of the drops beforehand.

How it should work: Fire Leaf Should drop in amounts of  2-3 units from a single Firethorn plant with a 50% base drop chance (not including the drop bonus from Path of the Adventurer).

Source:
 Some proof of the drop frequency (you can see many Fire Seeds dropped, but no Fire Leaves):
![image](https://user-images.githubusercontent.com/49105425/147959328-71d82263-5160-4b78-9a9e-8361a3ecb769.png)

 Conversation with a passerby (also herbalist): 
![image](https://user-images.githubusercontent.com/49105425/147960759-f9aa0cf6-3dff-4d0d-a0c8-050f0c4d7496.png)

**Comment by MrTide** [comment]
tested it with over 20 herbs probably something wrong with drop rate should be pretty low
https://wotlk.evowow.com/?item=39970#gathered-from-object

**Comment by UltraNix** [comment]
Tested and works okay.

**Comment by Mrldmz** [comment]
We are having different results. I can provide more info if you require it, but that item really isn't dropping for me.

**Comment by MrTide** [comment]
Might be related to path of adventurer as well

**Comment by Mrldmz** [comment]
Hello. This issue is marked as resolved, but the bug still persists. Proof: 
![image](https://user-images.githubusercontent.com/49105425/149047040-f433fbb5-0a9b-40c9-aa09-efa98328b11b.png)
