### ISSUE TITLE
[Quest][NPC] Get Me Outa Here! - Bonker Togglevolt

### ISSUE THREAD

**Issue by illillusion** [GameFreedomGG/Sindragosa#347]
Decription: 
This is an escort quest.
You free a gnome, Bonker Togglevolt, shackled with a ball and chain and escort him out of the cavern.

How it works: 
The NPC spawns when you get close to the pool in the cavern. When you talk to him he doesnt have a quest, but in his dialog he is asking you to free and escort him.

How it should work: 
He should already be in the cavern on the other side of the pool, with a ball and chain attached to him, with an escort quest (!).

https://www.youtube.com/watch?v=6Zj91XRWlrk

Source (you should point out proofs of your report, please give us some source):
![WoWScrnShot_010422_020129](https://user-images.githubusercontent.com/97084036/148021689-833babbb-d56e-4435-90d0-07fceddf2967.jpg)

**Comment by MrTide** [comment]
Ok according to my test on first encounter npc is offering the quest without an issue  and there are no requirements
https://cdn.discordapp.com/attachments/448057838263336961/929316040414998618/unknown.png
--------
If you fail you wont get the quest until you abandon it which is normal
https://cdn.discordapp.com/attachments/448057838263336961/929317137087090728/unknown.png
--------
The only issue i have found with it is that if you fail and npc dies or you finish the quest.. after he spawns creatures around him will still hit him even tho quest is already over and he is freshly respawned
https://cdn.discordapp.com/attachments/448057838263336961/929317002085023755/unknown.png
