### ISSUE TITLE
[PVP][Core] Wintergrasp Queue

### ISSUE THREAD

**Issue by Whitemane-Calypso** [GameFreedomGG/Sindragosa#348]
Decription:
Wintergrasp invites are being sent out to players not in the que and even after they decline, they keep popping up again.
How it works:
A player who isn’t even in the WG que gets absolutely bombarded with invites for WG, declines but invites still get sent out, spamming them. You get the invites everywhere- Dungeon group, raid, even while in arena. It only happens when WG is soon to start, not while it’s on-going. Relog/reload doesn’t stop the spam. 

How it should work:
You shouldn’t get invited while not in the que.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/GxGomDoBZdQ

**Comment by Verozz** [comment]
I have been experiencing this issue for last 2 weeks. Thanks god, not for every wg but it can happen like 1-2 times per day, then it will make pause for 1-2 days and it will start again. All in all it's random.
There is no fix. I have tried ALT+F4 & Relog & /reload - none will work.
This que issue starts 15 minutes before WG starts, and it lasts until WG finishes so it can basically last 15 minutes before start and 15-20 minutes after wg starts, so that would be 30-40 minutes of unplayable game.

Please just check the video that I have uploaded to see how painful it is, and it will happen anywhere, you can be in in Dung, you can be in Arena, doesn't matter.  [https://youtu.be/eLDV_aj9gao](url)

**Comment by UltraNix** [comment]
@Whitemane-Calypso @Verozz Does anybody knows how to reproduce it? I see you are no longe in que (and in WG), but still got world states displayng at your screen. Have you been on WG, but leave/teleportfrom it somehow? How do you event queue for WG? I need more info

**Comment by Verozz** [comment]
@UltraNix  I don't know how to reproduce it, it just randomly appears. I don't play WG, I don't go to WG zone. I just get que when wg is about to start (15 minutes), and while wg lasts and that's it. Constant que spam

**Comment by UltraNix** [comment]
@Verozz And when WG is about to start (these 15 min to start), you are in Dalaran/Nothrend/somewhere else?

**Comment by Verozz** [comment]
@UltraNix Yesterday, I was doing Naxx25 when que spam started

**Comment by UltraNix** [comment]
But it should be sent only to those in queue. So you must've been in queue somehow - maybe before Naxx?

**Comment by UltraNix** [comment]
And you are sure you was not in queue before that day?

**Comment by Verozz** [comment]
@UltraNix I hate WG, I didn't que for like a week or so

**Comment by Verozz** [comment]
@UltraNix Only thing that connects me with WG is that I have few WG quests active, dunno if that what's making the problem.
And sometimes I fly over it when I fly to some other zone.

**Comment by scrublama** [comment]
This was an issue on whitemane aswell where they first implemented a crystal item which gave you the opportunity to queue up for WG anywhere.  At first it was thought this crystal was the issue but even after removing it the problem persisted. There are more bug reports over at https://github.com/SallyWhitemane/Mograine/issues?q=wg

**Comment by Verozz** [comment]
@UltraNix I have removed all my WG quests yesterday, and since then I didn't get any single WG que so far.
Will keep you updated.

**Comment by Bagfire** [comment]
I have the same issue. It's been going on for two days now. Nothing helps: relogging, reloaden, force quit, exit game. I also removed all quests, but it doesn't seem to work.

**Comment by MrTide** [comment]
Sadly this issue is still happening its surely slowed down but we are still looking for the cause, we do appreciate any information about this issue.

**Comment by Godmatik** [comment]
@MrTide you may want to re-open it then
