### ISSUE TITLE
[Item] Epics

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#352]
Decription:Boe EPIC drop rate in northrend.

How it works:The drop rate is way tooo high(i know that people have 2x drop for everything,but still AH is full of them(u can get them under an hour from a specific place).

How it should work:Percentage should be the same as the database says.

Source (you should point out proofs of your report, please give us some source):
https://wotlkdb.com/?item=37835
https://wotlkdb.com/?item=43573
https://wotlkdb.com/?item=44308
https://wotlkdb.com/?item=44309
https://wotlkdb.com/?item=44312
https://wotlkdb.com/?item=44313

**Comment by MrTide** [comment]
I don't think this is true.. based on fast respawn rate of creatures (which is as low as 30 sec on some of them) and number of items found in AH (which is 1-4 max and priced pretty high) and having cross faction AH also my testing killing poor npcs all over the place drop rate looks good at least on world creatures.

**Comment by Soufly** [comment]
Try cavedweller word and decide afterwards @MrTide

**Comment by MrTide** [comment]
> cavedweller worg

just killed about 150 of those nothing..

**Comment by MrTide** [comment]
> cavedweller worg

just killed about 150 of those nothing..

**Comment by Soufly** [comment]
ok
