### ISSUE TITLE
[Warrior][Raid][Spell] EOE10 - Charge

### ISSUE THREAD

**Issue by AxelHanks900** [GameFreedomGG/Sindragosa#354]
Decription:
I'm a level 80 warrior. In the raid EoE 10, I died on p3. After revival, I wasn't able to use my Charge ability any more. Everytime I try to use it, it says "Unable to move"

How it works: I press charge- instead of charging my character stays put- gives an error text saying "Unable to move"

How it should work: Character should use charge ability when commanded to use Charge instead of not charging and getting a text saying "Unable to move"

Source (you should point out proofs of your report, please give us some source): Personally faced the problem in-game and contacted a GM about it

**Comment by MrTide** [comment]
This is pretty rare, i believe it only happens after a wipe on last phase. might be related to drakes you ride on last phase or falling down to the abys thats all the info i got for now.
