### ISSUE TITLE
[Profession][Item] Mining - Thorium Nodes & Arcane Crystals

### ISSUE THREAD

**Issue by Loken-Whitemane** [GameFreedomGG/Sindragosa#357]
Decription: Player reported that drops for Thorium are messed up. Currently nearly all the time Arcane Crystal's drop, but Large Opals, Blue Sapphires etc should drop too. 

How it works: Only Arcane Crystal's are dropping.

How it should work: Arcane 10% drop rate. Blue Sapphire 3%. Huge Emerald 3%. Large Opal 3%. Azerothian Diamond 3%. 

Source (you should point out proofs of your report, please give us some source):
https://wotlk-twinhead.twinstar.cz/?object=175404

**Comment by MrTide** [comment]
Can confirm mined over 150 nodes and all i got was arcane crystal + Thorium ore + dense stone + azerothian diamond

**Comment by UltraNix** [comment]
Got no problem with it. Mined couple thorium veins (small, rich) and got some other crystals.
![obraz_2022-01-10_102807](https://user-images.githubusercontent.com/80540499/148743635-508345ac-0c85-4fac-96c7-b461271af506.png)

**Comment by MrTide** [comment]
@UltraNix Thanks for taking a look
by the look of  it... you can get it in PTR but on live you can't
I tested both PTR and LIVE one last time and i do got them on PTR but not on live
Probably someone didn't push the fix or something
Would you please kindly double check ?
all i got was arcane crystal + Thorium ore + dense stone + azerothian diamond
--------
Blue Sapphire, Huge Emerald, Large Opal, Star ruby, are missing
https://wotlk.evowow.com/?object=175404

**Comment by UltraNix** [comment]
I can't tell anything about it. I don't see any difference between PTR DB and Live DB.
