### ISSUE TITLE
[Profession][NPC] Skinning - Rabid/Starving Dire Wolf

### ISSUE THREAD

**Issue by mylken** [GameFreedomGG/Sindragosa#361]
Decription:
Rabid and Starving dire wolves are unable to be skinned in Duskwood.

How it works:
Loot the corpse and it has the loot bag stay over the corpse; it doesn't change to the skinning hover.

How it should work:
Be able to right click to skin it.
Using skinning from your spellbook also doesn't work; should be able to click it and it to manually apply to corpse.

Source (you should point out proofs of your report, please give us some source):
GM Brook was with me to see testing

**Comment by MrTide** [comment]
Both can be skinned, I don't see an issue with any type of wolf there.. probably player forgot to empty the wolves loot or require a cache delete
https://cdn.discordapp.com/attachments/448057838263336961/929305305190375464/unknown.png
https://cdn.discordapp.com/attachments/448057838263336961/929305420152057906/unknown.png

**Comment by mylken** [comment]
Thanks so much for the thought but I know how to loot a wolf.

Had GM Brook with me - ask him for more details.

Cian Fenaughty
