### ISSUE TITLE
[Warrior][Spell] Devastate threat

### ISSUE THREAD

**Issue by Nilar9** [GameFreedomGG/Sindragosa#362]
Decription: 
Devastate is a direct replacement for Sunder Armor. It should be as powerful, if not more powerful than Sunder Armor threat wise, and right now it's weaker than Sunder Armor.

How it works: 
Right now first application of Devastate works correctly. Its threat is sunder threat + threat from damage. But after there's already sunder debuff on the target it only continues to do threat from damage and completely ignores sunder threat generation part, which makes it weaker than Sunder Armor ability in terms of threat generation

How it should work: 
Devastate threat generates threat in 2 (3 if you count bonus separately) parts: sunder threat (+ additional threat from more stacks) + weapon damage threat. Every additional cast of it should boost sunder threat part a little bit, and once there's 5x stacks of sunder on the target it should continue doing  sunder threat (with a 5 stacks bonus) + threat from damage

Source (you should point out proofs of your report, please give us some source):
I did some target dummy testing in Dalaran sewers (with macro to immediately stop autoattack) and this was the result:
after 1st Devastate: 1.1k total threat on dummy
after 2nd Devastate 1.4k total threat on dummy   
after 3rd Devastate 1.6k total threat on dummy  
after 4th Devastate 1.9k total threat on dummy
after 5th Devastate 2.1k total threat on dummy

What it should roughly look like:
after 1st Devastate: 1.1k total threat on dummy
after 2nd Devastate 2.5k total threat on dummy   
after 3rd Devastate 4.1k total threat on dummy    
after 4th Devastate 6.0k total threat on dummy    
after 5th Devastate 8.1k total threat on dummy   

For comparison I did 3 applications of Sunder Armor instead of Devastate (could only go up to 3 before recount got reset due to no damage done) :
after 1st Sunder Armor: 847 total threat on dummy
after 2nd Sunder Armor: 1.7k total threat on dummy
after 3rd Sunder Armor: 2.5k total threat on dummy

Conclusion: 
Devastate (after first application of sunder debuff) is only taking threat from damage it deals and threat bonus due to number of stacks and completely ignores Sunder Armor threat part, which makes it useless for tanking at the moment and tanks need to rely on Sunder Armor (basically a downgraded Devastate) ability if they want to keep threat vs dps.

Additional link to similar/same problem from another bugtracker on different server: https://github.com/SunstriderEmu/BugTracker/issues/3162

P.S. While at it, I'd also suggest you check if Shield Slam threat is scaling correctly with block value and Defensive stance threat multipliers. For example Revenge does way more threat than Shield Slam, which shouldn't be the case, as Shield Slam should be highest threat generating ability

Screenshoots: 
After 1st Devastate:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_000354.jpg?raw=true "Optional Title")
After 2nd Devastate:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_000356.jpg?raw=true "Optional Title")
After 3rd Devastate:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_000358.jpg?raw=true "Optional Title")
After 4th Devastate:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_000401.jpg?raw=true "Optional Title")
After 5th Devastate:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_000403.jpg?raw=true "Optional Title")

After 1st Sunder Armor:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_001608.jpg?raw=true "Optional Title") 
After 2nd Sunder Armor:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_001611.jpg?raw=true "Optional Title") 
After 3rd Sunder Armor:
![Alt text](/Nilar9/screenshoots2/blob/main/WoWScrnShot_010822_001617.jpg?raw=true "Optional Title")

**Comment by Nilar9** [comment]
Any updates on this? It's impossible to keep threat as warrior.
Also in addition to the post above, Devastate/Sunder Armor, completely stops generating threat if you already have 5x stacks on the target (it does like 5-10% of what it's supposed to generate).

**Comment by scrublama** [comment]
fixed?

**Comment by UltraNix** [comment]
@scrublama Fixed on repo. I don't know if it's live.

**Comment by Nilar9** [comment]
@UltraNix  did you check maybe was it just the Devastate threat or other abilities/defensive stance multiplier aswell?

**Comment by UltraNix** [comment]
Nothing like that. The bug was related to Devastate itself.
