### ISSUE TITLE
[Profession] Cooking - Dalaran Cooking Awards

### ISSUE THREAD

**Issue by Veectr** [GameFreedomGG/Sindragosa#363]
Decription: You can get unlimited Dalaran Cooking Awards in Dalaran Cooking Awards Achivment

How it works: While doing my stuff in Dalaran i came to cooking trainer placed in Dalaran and i missclicked buy wrong recipe. I turned back this recipe and got achivment for Dalaran Cooking Awards. I was in a shock a little and I wanted to check if I can do it again and id works. I buyed Fish Feast recipe 3 times and then i got higher achivment for Dalaran Cooking Awards. I think it shouldn't work like that that's why I wrote ticket. 

How it should work: Achivment shouldn't count these points when I'm turning back some recipes to NPC Derek Odds (Cooking Supplies) in Dalaran.

Source (you should point out proofs of your report, please give us some source): You can check my achivment that i made in about 15 seconds.

**Comment by oldspices** [comment]
this only gives you achievement. max achievement is from getting 50 rewards and the achievement has no reward in and of itself.  i tested and  confirmed, but hardly worth fixing IMO.

**Comment by MrTide** [comment]
Yes you can get this achievement with just buying and selling it back
Confirmed.
