### ISSUE TITLE
[Item] Pendulum of Telluric Currents 

### ISSUE THREAD

**Issue by DebowyMocny** [GameFreedomGG/Sindragosa#365]
Decription: Pendulum of Telluric Currents proc is bugged and deals damage to wrong person.

How it works: 
Pendulum of Telluric Currents proc deals damage to the player instead of enemy who got hit by spell.

How it should work: 
Pendulum of Telluric Currents proc should deal damage to enemy that was hit by spell what triggered proc.

Source (you should point out proofs of your report, please give us some source):
Item in wotlk database.
https://wotlkdb.com/?item=37264

Screenshots with combat log and MSBT.
https://imgur.com/a/5e3ED2s

**Comment by DebowyMocny** [comment]
I made a video about pendulum problem. It shows it deals damage to me while i cast spells on target dummy.
https://streamable.com/8q4eed

**Comment by MrTide** [comment]
Can confirm 
![image](https://user-images.githubusercontent.com/36106057/149591357-0061f216-da68-466d-b8a5-b83880e9bbe0.png)
Dealing damage to the player instead
