### ISSUE TITLE
Wrong Emblems dropping Ulduar

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#366]
On the PTR, all bosses in  Ulduar10m and 25m are dropping Emblems of Heroism.

Should be:
10m --> Emblem of Valor
25m --> Emblem of Conquest

**Comment by Godmatik** [comment]
I am also fairly certain that defeating a boss in 10m hardmode should drop Emblem of Conquest, I can't find the source for this though.

**Comment by Soufly** [comment]
Yes,1 emblem of conquest per hard mode 10 man.
