### ISSUE TITLE
Nodes disappearing

### ISSUE THREAD

**Issue by Lampasak** [GameFreedomGG/Sindragosa#367]
Decription:Its not only when i phase out from location,its also random,but only in northrend

How it works:When i get close to node it disappears,gas clouds too.

How it should work:Obviously not disapearing.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/6iK6MEe2fb4

**Comment by MrTide** [comment]
This node is located at the edge of the phase  that is why you are experiencing this. we can change this node phase and make it available for all phases in that area 
or extend the phase from village side to little bit pass brijana .
![image](https://user-images.githubusercontent.com/36106057/148682042-ceb04048-babd-441f-807c-4b65605578bc.png)
