### ISSUE TITLE
The problem with Magister Terrace HC

### ISSUE THREAD

**Issue by Galonesko** [GameFreedomGG/Sindragosa#368]
Decription: I can't start the Magisters Terrace quest. Together with GM, we tried to solve the problem by resetting the questgiver and start an alternative prequest. Unfortunately, this did not help at all. According to GM, there is information that I have this quest in the log, but I do not have a quest with this name.

How it works: I do not see the quest to MT HC

How it should work: I should start the quest without any problems.

Source (you should point out proofs of your report, please give us some source):
![Error](https://user-images.githubusercontent.com/95701438/148682387-2b3cae92-01d1-4368-9585-99624c4d26b3.jpg)
![Error2](https://user-images.githubusercontent.com/95701438/148682389-ad0d59b9-3574-471a-8ff8-1ebc6bb7c855.jpg)

**Comment by MrTide** [comment]
Can confirm NPC Missing from https://wotlk.evowow.com/?quest=11481 from shattrath so player can't get the first quest.
