### ISSUE TITLE
[Core][Dungeon] Dungeon Finder - Dismount

### ISSUE THREAD

**Issue by JackieNL** [GameFreedomGG/Sindragosa#370]
Decription:
When u flying in air and dungeon finder popup u enter and when ur ready u get dismounted and fall down without mounting.

How it works:
U fall down when your done with Dungeon finder group.

How it should work:
Stay up on your mount and dont die from falling

Source (you should point out proofs of your report, please give us some source):
I've got this isssue and many other guildies.

**Comment by JackieNL** [comment]
Any update's? Its still bugged.. :'(

**Comment by oldspices** [comment]
i thought this happened only to druids , no?

**Comment by Soufly** [comment]
If u are on a flying mount before u enter a dungeon,and if u are on a ground mount just before leaving it u will get double mount... if u try to remove it u will get dced(doesnt happen always,sometimes).

**Comment by UltraNix** [comment]
@JackieNL Cannot reproduce it.

**Comment by UltraNix** [comment]
Cannot reproduce and no response - closing.
