### ISSUE TITLE
[Ulduar][25M][Boss] Freya Hard Mode wrong pre-nerf HP values.

### ISSUE THREAD

**Issue by mrnuggets** [GameFreedomGG/Sindragosa#371]
Decription:

Currently Freya on 25 Hard Mode has the wrong values, boss HP, adds HP, roots HP on the **PTR.**

How it works / How it should work:

Freya has: **6.7M** should be **7.95M**

Ancient Conservator has: **3.5M** should be **4.2M**

Ancient Water Spirit has: **827K** should be **990.5K**

Snaplasher has: **1.6M** should be: **1.86M**

Detonating Lasher has: **372.8** should be **445.7k**

Strengthened Iron Roots has: **54.4k** should be **64.6K**

VoD: https://www.twitch.tv/videos/1259303029?t=01h02m35s

Source (you should point out proofs of your report, please give us some source):

Retail kill video: https://www.youtube.com/watch?v=tb5ho7F8nAA

**Comment by Godmatik** [comment]
Health values still wrong on live

**Comment by Soufly** [comment]
This needs fix ASAP.
