### ISSUE TITLE
[Ulduar][25M][URGENT FIXES] Mimiron & XT & Yog

### ISSUE THREAD

**Issue by AugustFloden** [GameFreedomGG/Sindragosa#372]
Decription 1: Mimiron phase 3 is broken. The head stays down indefinately and the fire-bots down extinguish flames at all.
Decription 2: XT HM health is 72,000,000 which is pure fiction. Look at prenerf values on wowwiki.
Decription 3: Yog - The yog fights have alot of gamebreaking bugs that make it unplayable.

How it works 1: When you get the head down on the ground, it should fly back after the duration. Emergency bots should extinguish flames.
How it works 2: XT HM should have pre-nerf values.
How it works 3: Yog'saron deserves an own thread. It is completely broken.

How it should work 1: Description above.
2: Description above.
3: Deserves an own thread.

Source (you should point out proofs of your report, please give us some source): I sadly cant provide any link/vod from the testing. www.twitch.tv/merfin should be able to.

**Comment by Godmatik** [comment]
Jimmy said these were fixed but it needs testing - Especially Yogg

**Comment by MrTide** [comment]
Should be fixed let us know if you found anything wrong

**Comment by Godmatik** [comment]
XT: fine
Mimiron: fine
Yogg: Will update when we get to it

**Comment by Godmatik** [comment]
the fire bots may be extinguishing flames a bit too aggressively though, they clear the whole room very fast, but I don't have any source or reference for how it should be

**Comment by Godmatik** [comment]
Reference this thread for the Yogg bugs I found so far:

https://github.com/GameFreedomGG/Sindragosa/issues/388

**Comment by Soufly** [comment]
Actually the HP of XT HM is wrong.It should be almost 57m,right now is 49m and a half.
PROOF: https://youtu.be/FBWcpewe5uQ?t=127 frosthold pre nerf.
![Untitled](https://user-images.githubusercontent.com/36957911/149539521-094f24f7-aa3c-4dc7-b9c2-1de45bb6247b.png) 
Sindragosa

**Comment by Godmatik** [comment]
The 49.5 million amount he has now is based on the Sunwell pre-nerf
document which stated 120% health buff from heartbreaker from his original
22.5 million health. I can't find any reference to what Blizz made the
percentage buff before they nerfed it (which was done a few weeks or so
after Ulduar released cause no guild could kill it).

**Comment by Soufly** [comment]
The frosthold video was made at the same day(or even earlier) with the realm first yogg 0 kill.And frosthold from what i remember has no custom stuff except Yogg(maybe algalon).

**Comment by Soufly** [comment]
https://sunwell-community.com/topic/15801-frosthold-secrets-of-ulduar-and-furious-gladiator-season-ulduar-difficulty/

**Comment by Godmatik** [comment]
The 220% HP they indicated on there was a typo according to Jimmy and it should be 120% (else XT would be at 72m+ health)

I don't know where Frosthold eventually got the 56.5million number from.
