### ISSUE TITLE
[Ulduar][25M][Boss] General Vezax & Animus pre-nerf wrong HP values.

### ISSUE THREAD

**Issue by mrnuggets** [GameFreedomGG/Sindragosa#373]
Decription:

Currently on the PTR, General Vezax and the Animus have the wrong pre-nerf HP values.

How it works / How it should work:

General Vezax has **23M** should be **30.7M**

Animus has **14M** should be **12.6M**

VoD: https://www.twitch.tv/videos/1259303029?t=03h36m14s

Source (you should point out proofs of your report, please give us some source):

Retail kill video: https://youtu.be/lKm4g6pT15U

**Comment by Godmatik** [comment]
It's set correctly on live realm, can close

**Comment by mrnuggets** [comment]
closed it, since it's fixed.
