### ISSUE TITLE
[Quest] [Reputation] Oracles/Frenzyheart factionswitching

### ISSUE THREAD

**Issue by Renoucer** [GameFreedomGG/Sindragosa#374]
Decription:
After finish both questlines(first for frenzy, then for oracles) we gets to a 
How it works:
After killing Jaloot, Zepik attacks player
How it should work:
After killing Jaloot, Zepik should be friendly to you and be able to give you a daily quest(after defeating  Artruis)

i suggest setting both npcs to firendly, and make switching factions easier than killing this strong boss

**Comment by MrTide** [comment]
Hello I have tested this multiple times over and over and every time they turned friendly after killing one of them I couldn't find any issues 
Please if you are having issues completing this quest make a ticket ingame we will investigate your situation (try to ask for me in your ticket)
