### ISSUE TITLE
[Item] Oil of Immolation should not share CD with potions

### ISSUE THREAD

**Issue by balkai** [GameFreedomGG/Sindragosa#375]
Decription: Oil of Immolation https://wotlkdb.com/?item=8956

How it works: Using Oil of Immolation puts potions on CD.

How it should work: Oil of Immolation should not put potions on cd, the only CD it should share is the 3 second CD with flasks/elixirs

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki-archive.fandom.com/wiki/Oil_of_Immolation
Quote from wowwiki "Does not share cooldown with other potions and can be chugged in combat as often as every 3 seconds."
https://wotlkdb.com/?item=8956#shared-cooldown:100-2

Also this https://www.wowhead.com/item=8956/oil-of-immolation#comments
Altho no comments say it shouldn't share a CD, there are ones that suggest adding them to macros cause they don't incur any shared CDs, from patch 3.2.2

**Comment by balkai** [comment]
Clarification; Oil of Immolation does not activate CD on potions, but it cannot be used while potions are on CD
How to reproduce; Use Potion of Speed(example) and then try to use Oil of Immolation, doesn't work.

**Comment by Whitemane-Calypso** [comment]
Confirmed on PTR. If you use Potion before you use Oil of Immolation, the icon itself doesn't say it's on cooldown but you're unable to use it. If you do the opposite, use Oil before Potion, and then attempt to use another Oil of Immolation, it does not work.

**Comment by UltraNix** [comment]
I cannot do anything with it. Even If I correct the "visual" bug, the client always think it's a potion and put it on cooldown with other potions.
