### ISSUE TITLE
[Ulduar][10M][Boss]Hodir 10 man Does not drop Leg tier tokens

### ISSUE THREAD

**Issue by GMHiki** [GameFreedomGG/Sindragosa#377]
Decription: Killing hodir 10man is not dropping a leg tier piece.

How it works: Does not tier leg piece.

How it should work: should drop 1 leg tier token.

tier token IDs
45650
45651
45652

Source (you should point out proofs of your report, please give us some source):
3 tickets with the same issue.

**Comment by Godmatik** [comment]
Also - it looks like the sigil for the hard mode will drop from Hodir even if you don't kill it before 2 minutes (speed kill)

**Comment by Soufly** [comment]
Hodir 10 gives 25 man mail bracers,fix that as well
