### ISSUE TITLE
[Ulduar][Boss] Razorscale missing ability

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#378]
Razorscale is missing his "Devouring Flame" ability in 25m during Phase 2

https://www.wowhead.com/spell=63816

**Comment by MrTide** [comment]
Hello
I checked it seems like its working
![image](https://user-images.githubusercontent.com/36106057/149531542-2d01462d-ab51-4747-8e42-97ed4e8e1f8e.png)
shots fireballs to the players and also ground catches on fire

**Comment by Soufly** [comment]
It is working,just watched their vod and phase 2(ground phase) 
She is casting it every 20 seconds like it was back on frosthold.

**Comment by Godmatik** [comment]
I am talking about ground phase, I thought I recall she was supposed to face a player and throw a fireball at them also to create a fire patch. Ah well.
