### ISSUE TITLE
[Ulduar][Spell][Boss]Tower buffs from Flame Leviathan effecting Razorscale + Ignis + trash 

### ISSUE THREAD

**Issue by mrwiggleslol** [GameFreedomGG/Sindragosa#383]
We think the Tower buffs from FL are effecting Razorscale and Ignis and Ignis trash. The adds and trash seemed to do way more damage than theyre supossed to and the bosses had too much HP. 
It got 'fixed' after someone in our raid skinned FL with engineering after we killed razorscale, people saw ignis' HP drop down to normal values.
![razorscale](https://user-images.githubusercontent.com/81237635/149311637-0d938e99-ee8f-47b9-894a-3c399b946a9b.png)

**Comment by Godmatik** [comment]
Noticed the same, apparently they aware and fixing it before next reset

**Comment by Godmatik** [comment]
Can close perhaps? Changelog posted on discord indicated it might be fixed. Didn't notice any frost tower buff in 10m or 25m.
