### ISSUE TITLE
[NPC] Critters

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#385]
How it works:Critters are not triggering any of the hunter traps.
How it should work:They should in order to get Lock and Load proc at least.
Source (you should point out proofs of your report, please give us some source):
(https://wowpedia.fandom.com/wiki/Critter)
Edit: It was working back on sunwell.

**Comment by MrTide** [comment]
You say that but i can't find any evidence that they should or should not trigger the traps

**Comment by Soufly** [comment]
Is not only frost trap/freezing arrow.Not a single trap can damage/activate  from them,same goes for the dummies down in dalaran.Its something about their hitbox.
