### ISSUE TITLE
[Spell][Shaman] Greater Fire Elemental

### ISSUE THREAD

**Issue by nippari** [GameFreedomGG/Sindragosa#386]
Decription:
Fire ele does more damage than in tier 10 bis in tier 7 here
How it works:
fire elemental fix went wrong
How it should work:
fire elemental is doing around 300k + damage on use which is ridiculous, you should check the spell again the fix was not correct
Source (you should point out proofs of your report, please give us some source):

https://www.youtube.com/watch?v=G2ODZ510mVc&ab_channel=PuffedTV tier 10 ele shaman fire elemental is hitting for 3k ish.
there is logs from this server on legacy players where ele shamans fire ele is critting for 8k and some more
https://gyazo.com/9979e9dbc1e982f6562bc3b2cdd733e9 
![image](https://user-images.githubusercontent.com/77241121/149381471-41ad2b4f-f8b0-495c-a957-821546875cd5.png) this is from enh shaman too.

its hard to find retail stuff since logs are not available anymore. most 10-11years old videos they do 1-3k damage usually hard to find too but clearly is bugged it has never been this strong

https://youtu.be/j4s9xilLlNU?t=389 fire ele in tier 10, smacking for 2k s on enh shaman

https://gyazo.com/e04928f2702f6d5bf5d3243836e19521

**Comment by Godmatik** [comment]
Here's another bug report showing the fire ele statistics, it shows as resolved a week ago, were these changes pushed to live server yet? Or did the changes mess up the fire ele damage?

https://github.com/GameFreedomGG/Sindragosa/issues/40

**Comment by Soufly** [comment]
Any news on this ?

**Comment by nippari** [comment]
https://gyazo.com/471d6226832a0588362a77786936f5d6 kill with fire ele 9k + dps

https://gyazo.com/828b1562a4d93cffa8900fe54f8eec09 kill without fire ele 7,6k dps

like u can see its pretty massive if snapshotted atleast

**Comment by Soufly** [comment]
It is not known if either +spell power gear or Elemental passives that affect critical effects or fire totems benefit the elemental. Considering the fire elemental is not benefited by any party-wide abilities, and seems to be the "pet" of the totem, it is doubtful.

**Comment by Soufly** [comment]
https://youtu.be/ktDNlwkAS_k?t=301 pet damage are the orange hits on the boss during bloodlust

**Comment by Soufly** [comment]
https://youtu.be/ktDNlwkAS_k?t=301 some enh during toc

**Comment by Soufly** [comment]
https://youtu.be/ktDNlwkAS_k?t=348 some enh during toc

**Comment by nippari** [comment]
looking at lightning shield theres some bug on it too its triggering too much on the server when comparing to these videos and to sindragosas enh shamans. I dont think theres a gcd looking at retail videos the proc % however is just wrong someway but i cant find any info about what it should be..

**Comment by Soufly** [comment]
@UltraNix watch?v=G2ODZ510mVc&t=63s pet hits doing 2-3-4k with ICC gear and spell power ... also put on high priority,nerf the damn pet finally.

**Comment by Soufly** [comment]
It would be good if u calculated the time between the pet attacks,they should be a lot slower,but i dont know really how fast the pet hits on synergie.

**Comment by demetrzz** [comment]
#459 
Provided some data from tests in comments.
