### ISSUE TITLE
[Item]Wintergrasp Commendation

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#389]
How it works:Wintergrasp Commendation is missing from the vendor npc Knight Dameron(check the horde npc Stone Guard Mukar for the same issue).
How it should work:It should be there from the release.
Source (you should point out proofs of your report, please give us some source):
https://wotlkdb.com/?item=44115

**Comment by MrTide** [comment]
Can confirm they are not ingame

**Comment by Game-Freedom** [comment]
This is intended, WG Commendations are gonna be back on wednesday with Season 6.

/Jimmy
