### ISSUE TITLE
[Custom][Priest][Spell] Lightwell

### ISSUE THREAD

**Issue by Weuyn** [GameFreedomGG/Sindragosa#392]
Decription: The lightwell object summoned by priests with the lightwell talent can only be clicked once before breaking and being unable to be clicked again.

If the lightwell gets attacked, then you can click it again, but I don't think you're supposed to be able to attack the lightwell either.

How it works: Priest summons lightwell. Priest clicks lightwell, priest can no longer interact with the light well

How it should work: You should be able to click it multiple times as long as you don't have the lightwell regen buff (changed for wotlk iirc)

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
By the look of it ... We just need to change the faction ID of the light well so it would cause issues when horde and alliance players are in same party

**Comment by Loken-Whitemane** [comment]
Adding on to MrTide, we tested and were unable to find exact problem with reproduction steps provided. But we did find that in xfaction party's, opposing faction is able to destroy the lightwell. MrTide's comment is resolution to this bug

**Comment by Weuyn** [comment]
> Adding on to MrTide, we tested and were unable to find exact problem with reproduction steps provided. But we did find that in xfaction party's, opposing faction is able to destroy the lightwell. MrTide's comment is resolution to this bug

The problem is not that opposite factions can't use it, though that'd be a problem too, The problem is that trying to use the lightwell more than once doesn't work.

1) summon lightwell
2) get damaged
3) use lightwell once (charge is consumed, you get the lightwell renew buff like you should)
4) get damaged again
5) you can't use the lightwell now.

optional:
6) get an enemy NPC to attack the lightwell, even one autoattack works
7) you can use the lightwell one more time before it locks up (get an NPC to attack it again to be able to use another charge)

**Comment by UltraNix** [comment]
@MrTide @Loken-Whitemane Lightwell should be attackable by hostile unit?

**Comment by MrTide** [comment]
> @MrTide @Loken-Whitemane Lightwell should be attackable by hostile unit?

Yes It should but not when horde and alliance are in same group
