### ISSUE TITLE
[Ulduar][10M][Freya]Adds are healed at Freya 

### ISSUE THREAD

**Issue by WhenFresh1** [GameFreedomGG/Sindragosa#394]
**Decription:**

Adds at Freya hard mode are healed even if there is no Eonar’s Gift around 

**How it works:**

Adds at Freya hard mode are healed even if there is no Eonar’s Gift around (probably invisible Unstable Sun Beam)

**How it should work:**

Adds shouldn't be healed 

**Source (you should point out proofs of your report, please give us some source):**

**Comment by Godmatik** [comment]
Did it always happen or was it a one-time thing for you? I've done two 10m Freya hard-mode kills and never seen this (doesn't exist in 25m Freya HM either)

**Comment by WhenFresh1** [comment]
We never seen this Unstable Sun Beam at our 10man and did few wipes there, around 4

**Comment by Godmatik** [comment]
Just did another 10m Freya with all keepers up, there was a sunbeam up everytime at regular intervals.

**Comment by WhenFresh1** [comment]
We did it today and Unstable Sun Beam was visible, and adds did not heal, so i guess it was only incident

**Comment by Whitemane-Calypso** [comment]
I’m closing it then.
