### ISSUE TITLE
[Dungeon][Battleground]Deserter from Dungeon and BG don't stack.

### ISSUE THREAD

**Issue by Whitemane-Calypso** [GameFreedomGG/Sindragosa#395]
Decription: Deserter which you get when you leave a BG and one when you leave a Dungeon currently don't stack. That means people who don't want to do a dungeon, can just leave, get 30min Deserter, then join RBG que, leave BG and get that debuff instead, then he can que for Dungeons again. 

How it works: I tested this on my player character. It is true. If i leave a dungeon, get the 30 min Deserter, then que for RBG and leave,  I have the RBG Deserter, not the Dungeon one, hence I can queue again.

How it should work: The two Deserters should stack. You shouldn't be able to cheese out of a Dungeon like that.

Source (you should point out proofs of your report, please give us some source): -

**Comment by oldspices** [comment]
NA players wont have to worry about this one XD

**Comment by MrTide** [comment]
By the look of it, simply coming out of BG removes the debuff.
Can confirm.
