### ISSUE TITLE
[Npc][Raid]25m Auriaya

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#396]
How it works:Auriaya HP is doubled
How it should work:Should be 16.7m
Source (you should point out proofs of your report, please give us some source):
https://youtu.be/xB7EZu38hvc?t=62

**Comment by Godmatik** [comment]
31 million is the correct pre-nerf value from retail - Sunwell used the wrong number.

Source:
https://www.youtube.com/watch?v=QJ5ShR4XnAo

**Comment by Soufly** [comment]
Actually they forgot about the HP part,but everything else(adds hp,damage etc..)
