### ISSUE TITLE
[Hunter] Trap triggering on critters/Ogre Pinata

### ISSUE THREAD

**Issue by parsafr0st** [GameFreedomGG/Sindragosa#400]
Decription: if u guys fixed the Lock and Loading procing with frost trap on immune bosses u should also fixed the trap trigger on critters and this guy >>>https://tinypix.top/i/wowscrnshot-011622-124657.eM76r<<<

How it works: traps are not working critters and that "Ogre Pinata"

How it should work:  its pretty simple, it should work

Source (you should point out proofs of your report, please give us some source):

**Comment by scrublama** [comment]
#385

**Comment by parsafr0st** [comment]
@scrublama And Ogre Pinata?

**Comment by Soufly** [comment]
no proof so far,didnt found anything u can close ...
