### ISSUE TITLE
[Rogue][Talent]Hack and Slash talent not working

### ISSUE THREAD

**Issue by Qunskap** [GameFreedomGG/Sindragosa#405]
Decription:
The Hack and Slash combat rogue talent does not seem to work properly.
How it works:
I killed Kel'thuzad and i did a total of 338 melee swings. This gave me 1 proc of the talent (might be bad luck). The one proc i got did 23 damage. I went and tried it on a training dummy and this time the talent hit for a whopping "1" damage.
How it should work:
It's supposed to be a 5% chance on melee swing to do another swing on the same target. I highly doubt it's supposed to do so little damage since it doesn't even add 1dps.
Source (you should point out proofs of your report, please give us some source):
Testing

**Comment by UltraNix** [comment]
I see no bug here.
![obraz_2022-01-18_185106](https://user-images.githubusercontent.com/80540499/149991562-f0066834-8948-4604-b41e-14bf1823a1bd.png)
