### ISSUE TITLE
[Ulduar][Boss][Important] Freya Strengthened Iron Roots gripable by DKs.

### ISSUE THREAD

**Issue by mrnuggets** [GameFreedomGG/Sindragosa#408]
Decription:

Currently on Freya Hard Mode Strengthened Iron Roots are gripable by DKs 'death grip' ability.

This makes it easier for people to kill roots, cause you can just grip it towards the raid.

How it works:

Get rooted by Strengthened Iron Roots, get a DK to use his spell 'death grip'.

How it should work:

Strengthened Iron Roots should be immune to death grip.

Source (you should point out proofs of your report, please give us some source):

**Comment by Godmatik** [comment]
Confirmed, although note the person still has the roots debuff on them and takes damage (doesnt free them), but it makes it easier to kill the roots
