### ISSUE TITLE
[Shaman][Spell]Riptide and Earth Shield aren't being levelled up automatically

### ISSUE THREAD

**Issue by sarc8201** [GameFreedomGG/Sindragosa#409]
Decription:
Riptide and Earth Shield was stuck at r1 instead of having Earth Shield at r5 and Riptide at r4.
How it works:
Riptide and Earth Shield stuck at r1.
How it should work:
Riptide and Earth Shield should be at r4 and r5 respectively.
Source (you should point out proofs of your report, please give us some source):
[https://imgur.com/a/JI295ZF](url)

**Comment by UltraNix** [comment]
Looks okay on my local. @Whitemane-Calypso @sarc8201 I can't reproduce it.
