### ISSUE TITLE
[Shaman][Spell] Feral Spirit

### ISSUE THREAD

**Issue by GMHiki** [GameFreedomGG/Sindragosa#41]
Expected behaviour:
1) Spirit wolves should have base strength of 331 and get 2xAP per each point.
They should also get 61% of shaman AP while glyphed.

30% base AP scaling + 30% glyphed + 10% after being affected by Unleashed Rage = 61%
it gets even more complicated, because base str converted to AP should be also affected by Unleashed Rage
So (2xbase str + 60% of shaman AP)*10% Unleashed Rage
final formula is then: (331 * 2 + 0.60 * [Shaman AP]) * 1.1
2) Spirit Wolves should gain 1hit rating per 1hit rating point of the shaman. Their attacks fit into 1h/2h table, so they should be hit capped at 8% or 262 rating.

http://archive.is/6SLfn#selection-1726.0-1726.1
http://www.mmo-champion.com/threads/624759-*Enhancement-Shaman-FAQ-(3-3)*

**Comment by UltraNix** [comment]
Everything from here works okay. This is exactly what is in the code.
