### ISSUE TITLE
[Death Knight][Spell]Didn't auto learn new runes for runeforging as DK

### ISSUE THREAD

**Issue by sarc8201** [GameFreedomGG/Sindragosa#410]
Decription:

How it works:
Doesn't auto learn new runes as DK
How it should work:
Learns all runes for runeforging as DK
Source (you should point out proofs of your report, please give us some source):
https://imgur.com/a/XUq5mcY

**Comment by UltraNix** [comment]
As tester said - you must do the quest chain.
