### ISSUE TITLE
Hunter at the Algalon - impossible to survive bing bang.

### ISSUE THREAD

**Issue by pierrdzacy** [GameFreedomGG/Sindragosa#411]
Decription: Hello, check my link and our algalon pulls.

How it works: Only Hunter in raid cant survive the big bang on the algalon.

How it should work: Hunter should be alive after bing bang portals finish instead of dying instantly.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?t=10821&v=bkl_XcVT5OE&feature=youtu.be

**Comment by Soufly** [comment]
Its either phasing bug(u could get that if u do the quest under ICC,forgot the name some elite) or he didnt go in.

**Comment by Whitemane-Calypso** [comment]
I don't really understand why this is a bug report. What exactly are you reporting? As far as I can see, he didn't go in the portal.
