### ISSUE TITLE
Feral tier 8 - 2 set

### ISSUE THREAD

**Issue by nippari** [GameFreedomGG/Sindragosa#414]
Decription:
bleed have chance to enter clearcasting state
How it works:
is it working? or am i just very unlucky
How it should work:
should proc ooc
Source (you should point out proofs of your report, please give us some source):
i spent some time running bleeds on dummy but got 1 proc after like 200ticks is the proc rate really low or just not working? maybe broken after the fixes? can u check it out and fix if necessary.

**Comment by Soufly** [comment]
Its 2%.

**Comment by nippari** [comment]
okey just unlucky then thought it was 6 with that set bonus too

**Comment by nippari** [comment]
can u still check if its really 2% a tick? i just did a test with 500 rip ticks and 2 procs which equals like 0,.4% chance ?

**Comment by gandalkk** [comment]
Got my 2-set last night too it does feel really useless set bonus i agree. Maybe its 1% on each bleed tick or something? Definatelly worth a look atleast :/

**Comment by MrTide** [comment]
Well proc rate as you know is pretty low (2%) but maybe a developer can check to make sure, i spent a quite a while trying to get a proc and i didn't even get one

**Comment by UltraNix** [comment]
Everything works okay. It's just 2%. Just tested and the spell itself works okar.
