### ISSUE TITLE
[Ulduar][Yog Saron 25m][last phase]

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#417]
Decription:

Crusher tentacle is spawning on the last phase on yog saron 25m, on today raid we've got 3 spawned.

How it works:

New Crusher tentacles are spawning on the last phase on yog saron 25m, on today raid we've got 3 spawned.

How it should work:

Crusher tentacle shouldn't spawn after last phase is enabled.

Source (you should point out proofs of your report, please give us some source):

GM Tide helped us to kill the tentacles but I'm reporting this just in case.

**Comment by Godmatik** [comment]
They claim fix is coming tomorrow, but yes please make sure it is done.

![crusher](https://user-images.githubusercontent.com/37913400/150031293-a2d3a0be-82c9-4dc8-a1f5-1d9b22614383.png)

**Comment by Whitemane-Calypso** [comment]
It is fixed. Closing.
