### ISSUE TITLE
[Ulduar][Loot] Flame leviathan loot.

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#422]
Decription: Flame leviathan is suppose to drop 2HM Loot but its either dropping one or none at all

How it works: its dropped one or none

How it should work: it should drop two HM items (4towers)

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=bB0jHxqJNyg

**Comment by Godmatik** [comment]
in 25m it worked fine for this guild, are you certain all 4 towers buffs were up?

https://www.twitch.tv/videos/1269036425?t=139m20s

**Comment by MrTide** [comment]
Yes we had multiple cases that players just received one or none
