### ISSUE TITLE
[Ulduar][25m HC][NPC] XT-002 - Life Spark

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#425]
Occasionally - the life spark that spawns from a searing light bomb in XT-002 hard mode encounter (Heartbreaker) does not move and just stands still where it spawns, there doesn't seem to be any pattern that I could tell and it only happens every once in a while.

How it should work: The Life Spark should always follow proper aggro table and go to the person with highest threat.

**Comment by Lechy901** [comment]
This happened on whitemane too IIRC

**Comment by Godmatik** [comment]
My best theory - after seeing it occur a few more times - it is getting stuck in the terrain, generally it stops moving if spawning around the same spot. See clip below.

https://clips.twitch.tv/SingleSoftLocustDogFace-DufP-oyz5LOWJn1y

**Comment by Godmatik** [comment]
Still happens
