### ISSUE TITLE
Feral Druid procs way less clearcasting than It should

### ISSUE THREAD

**Issue by Cipelin** [GameFreedomGG/Sindragosa#427]
Decription: Omen of Clarity doesn't work properly on Feral druid. T8 2set bonus is bugged. Faerie Fire is not causing Omen of Claritiy proc. In general Clearcasting doesn't proc as much as it should.

How it works: T8 Set bonus which gives you chance to proc Clearcasting https://imgur.com/8Qj8kTw Procs in general once per 2minutes. I did test where I only hit target dummy with rake and rip for more than 4 minutes and It went off 4 times, 2 of those times were caused by rake instant damage. https://imgur.com/eWAUASy
I also noticed that Faerie Fire(feral) spell, which normally should proc Omen of Clarity, is bugged, or it has very very low chance, cause I can count on my 1 hand how many times It proc during whole content of Naxxramas. 
I main feral, I've been playing him last 3 wotlk servers and I suppose that in general Omen of Clarity procs less often than It should. On Whitemane na Frosthold servers I remember pulls, when there's clearcasting after clearcasting after clearcasting proc, but now it feels like blessing whenever you get a clearcast.

How it should work: T8 2set Bonus should proc more often, Faerie Fire(feral) doesn't proc Clearcasting, which should do it. And In general Feral should proc more Omen of Clarity,

**Comment by gandalkk** [comment]
Faerie fire procs it, its 6% chance tho, 100 casts u only get average 6 procs from it. But i still agree with tier 8 it feels really wierdly low but it was confirmed it is 2% apparently.

**Comment by Godmatik** [comment]
Dev already commented that the T8 2 set bonus is not bugged, just has low proc rate of 2%

https://github.com/GameFreedomGG/Sindragosa/issues/414

**Comment by Soufly** [comment]
Patch 3.0.2 (14-Oct-2008): Now a passive spell. Now also procs on damage and healing spells, yet no longer procs on feral abilities(only auto-attacks proc it). Proc rate is roughly 6% with a 10 second internal cooldown.

**Comment by styxel** [comment]
ooc works fine most of the people that make these report are from frosthold = 6% chance on tier8 , consumables procced ooc etc. 
6% is correct in general but its 0gcd it was never in patch notes but can be found from old logs and videos from retail in ulduar to icc.
2% for tier 8 - 2 set havent gotten my 2 set yet so no comments if it works.

**Comment by Soufly** [comment]
Well yeah the latest change notes are from 3.0.2,cant say much after that during wotlk.

**Comment by styxel** [comment]
ye its 0 gcd here on sindragosa its fine just wanted to proof it so ppl dont make false report about it after having to be 10seconds or smthing :d

**Comment by Cipelin** [comment]
Pls fix feral <3

**Comment by Soufly** [comment]
This guy wins the thread lol

**Comment by MrTide** [comment]
We already tested this with another report and its working as intended
https://github.com/GameFreedomGG/Sindragosa/issues/414
