### ISSUE TITLE
[Ulduar] Teleporters

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#431]
The Ulduar teleporters, two things I noticed:

1 - They can be used while in combat to teleport - this can be used to improperly reset bosses/trash/etc - I think only should be able to use them when out of combat.
2 - The teleporter in XT-002's room behind him is active before the boss is defeated (and as above, can be used during encounter to escape and reset boss), that specific one should only be active after XT is defeated I believe.

https://www.wowhead.com/object=194569/ulduar-teleporter

**Comment by MrTide** [comment]
For Number 1 - I couldn't use it on PTR you can click on it but nothing happens 
![image](https://user-images.githubusercontent.com/36106057/150420907-58c80ca1-0f59-40c4-a130-b9a2ecac122c.png)
and for number 2 - yes you can click on it but you can't go further

**Comment by Godmatik** [comment]
On live realm it definitely works, maybe only certain ones do? For example teleporter near Conservatory of Life, we over-aggro a pack in the Freya room, and in-combat was able to teleport to the entrance.
