### ISSUE TITLE
Yogg-Saron Constrictor Tentacle (25m)

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#433]
Despite what the changelog says, using hand of protection still does not break free the person who is grabbed by the constrictor tentacle (in 25m Yogg)

![Constrictor](https://user-images.githubusercontent.com/37913400/150470261-aa7d7127-ad6e-4b2c-bbc4-66af4e5cb404.png)

**Comment by danniellos94** [comment]
Can confirm hop doesn't break free the person grabbed by the contrictor tentacle.

**Comment by Godmatik** [comment]
From changelog posted today:

☑️ [Raid/Ulduar]: Ensure that player will be set free from Constrictor Tentacle if he has Hand of Protection (Yogg-Saron).

Will go ahead and close this report, but will re-open if it still isn't fixed

**Comment by Godmatik** [comment]
Going to re-open this, as this bug is partially fixed. Now hand of protection frees the player from the constrictor tentacle, however the constrictor tentacle still stays alive and doesn't instantly die as it should.

An additional bug is that you can not use Divine Shield or Ice Block while grabbed by the tentacle, but you should be able to. 

![1](https://user-images.githubusercontent.com/37913400/151686421-2b02b6f1-f2bc-4c96-8a9b-5561d7f65ef1.png)

![2](https://user-images.githubusercontent.com/37913400/151686424-249cd24f-d49f-4dc7-83b7-881cac2ca60e.png)
