### ISSUE TITLE
[Hunter][Talent] Improved Hunter's Mark

### ISSUE THREAD

**Issue by botwg** [GameFreedomGG/Sindragosa#435]
Decription: Hunter's Mark should renew the dmg attack power of all attackers against that target by 500 without adding points in Improved Hunter's Mark, it should increase this value by 30% Currently, Hunter's Mark does not increase Hunter's damage, no matter if you have points added in Improved Hunter's Mark or not. increasing attack power by 500 on each attack range should significantly increase its damage

How it works: it doesn't work at all

How it should work:
Increases the bonus attack power granted by your Hunter's Mark ability by 30%, and reduces the mana cost of your Hunter's Mark ability by 100%.

Source (you should point out proofs of your report, please give us some source):
[dmg without Hunter's Mark](https://ibb.co/7YB7dPF) 
[dmg Hunter's Mark](https://ibb.co/f9DQBSK)

**Comment by Soufly** [comment]
I dont get it,is the talent not working or what ? IHM should give 150 attack power(3/3),which is 30 dps per shot(aimed/chimera/auto).Kshot dps increase is 60,and steady should be 22.5 dps.

**Comment by botwg** [comment]
as a base it should give 500 +150 of talents that is 650AP which should be about 150 dps per shot(aimed/chimera/auto).Kshot dps increase is 300dps, and steady should be 90dps.
if the number is right, the HM itself should visibly increase the dmg without IHM, it is 500AP.
and here, despite the additional 650AP, the difference in dmg is practically none.

for ss without HM I do the same dmg and even more than when I use HM

**Comment by Soufly** [comment]
Your calculations are slightly off,on average IHM should give 55 dps with all of those shots(except kshot ofc).

**Comment by botwg** [comment]
there you are right IHM should be 55 dps, so the dmg should be much higher when using it at the target, in my case, within 1 minute of the puppet attack on the same talents with the same rotation, I practically do not have a difference,of 7k dmg more or less, it's a matter of proc buff

**Comment by Soufly** [comment]
Do your test without gear,with only weapon... Otherwise is not accurate..

**Comment by spyke13** [comment]
+ if you have talent + glyph it would be 500*1.3*1.2=780
now glyph and talents just stack and its give 750 ap

**Comment by Soufly** [comment]
i dont see a problem here,maybe close ?

**Comment by Loken-Whitemane** [comment]
The comments in this report are different from the original report (ie: Improved Hunter's Mark "does not work at all"). Closing this out
