### ISSUE TITLE
Fire elemental totem

### ISSUE THREAD

**Issue by jeffspicher** [GameFreedomGG/Sindragosa#437]
Decription:
Sometimes my fire elemental totem don't hit at all
How it works:
most of the time when i summon my fire elemental totem in or out combat he will just stay doing nothing.
How it should work:
Hit mob just after being summoned
Source (you should point out proofs of your report, please give us some source):

**Comment by demetrzz** [comment]
It doesn AFK for me, but i tested with few pulls on target dummy, sometimes it doesnt use auto attack at all while using other spells and sometimes it doesnt use specific spells like fire blast, **proofs:** 
https://i.imgur.com/W4bQg07.png https://i.imgur.com/agnaZIU.png https://i.imgur.com/QHlmPmS.png https://i.imgur.com/lV6gbwe.png https://i.imgur.com/PuQa1zu.png https://i.imgur.com/Dpc2Kuk.png

**How it should work:** it needs to cast all spells and auto attacks equally. 

Also another bug is it should prio your current target. On bosses that has adds or something like spores on loatheb it would always prio that over hitting boss.

**Comment by UltraNix** [comment]
@jeffspicher @demetrzz @Game-Freedom I can't reproduce this one Please record a video about this bug.

**Comment by demetrzz** [comment]
@UltraNix when i tested damage yesterday it seemed to work properly, only thing that was different when i did those tests on screenshots 1 week ago is i was unequipping trinkets, not sure if its related somehow. 
Thats related to his damage abilities prio.

About fire ele being afk @jeffspicher needs to make a video, it doesnt afk for me personally.

Regarding his weird behaviour you can reproduce it by pulling loatheb, waiting for spores to spawn, then summoning fire elemental, or same with Ignis and his adds or any other boss that has adds. 
It should prio target boss/your current target, not randomly switch on adds. Also it needs to always readjust position to hit from behind, even tho i never saw his attacks getting parried or dodged so it wont matter much, i dont have much data on it tho.

**Comment by UltraNix** [comment]
I'm talkin about the problem reported here - elemental does not always auto attack/cast spells.

**Comment by demetrzz** [comment]
Sorry then, will make separate reports for those issues.

But for me whenever i summon it **during combat** it never AFKs, maybe try reproducing it by summoning outside of combat then start attacking, otherwise i dont see any way how this can be a bug. jeff also mentioned "most of the time" which also makes it questionable, possibly its pvp related?

**Comment by UltraNix** [comment]
I tried many possibilites - no result. 
Other problems described by you are already reported in different tickets.

**Comment by jeffspicher** [comment]
Hello it seem that after a reset my fire elem "seem"to work properly and attack everytime i summon it. But i'll keep an eye on him cuz he was sometimes really slacking doing nothing wether i was summoning him out of combat then go in combat or in combat.

**Comment by jeffspicher** [comment]
Well No ! finally he does have some time where he doesnt do anything ! specially if for example: i"m in a fight i summon him he will attack a monster, once that monster is killed i get out of combat and start to hit another monster he will not hit it.
![WoWScrnShot_012822_181611](https://user-images.githubusercontent.com/74730662/151640326-05e6bf07-deac-40ba-8fee-0b600f427366.jpg)
![WoWScrnShot_012822_181622](https://user-images.githubusercontent.com/74730662/151640335-0da10337-4ded-42b4-8d3c-d68e20dc2759.jpg)
![WoWScrnShot_012922_003611](https://user-images.githubusercontent.com/74730662/151640352-33ed61fb-0d8e-4b94-a3d5-40600ad99899.jpg)
![WoWScrnShot_012922_003623](https://user-images.githubusercontent.com/74730662/151640360-d3a30329-b8e9-4f7c-af4c-c68483cb37e0.jpg)
![WoWScrnShot_012922_003627](https://user-images.githubusercontent.com/74730662/151640373-010b71dd-863c-42ae-abd2-1102acaf772a.jpg)

**Comment by danniellos94** [comment]
I have similar problem with dancing rune weapon, however rune weapon seems to attack the next target but doesn't copy abilities. However if you kill mob, lose combat kill mob it seems it's working. 
#360
https://www.youtube.com/watch?v=BnuRI3CQ9ZQ
https://www.youtube.com/watch?v=2DTuYE8wQoc
