### ISSUE TITLE
310% mounts and druid 

### ISSUE THREAD

**Issue by nippari** [GameFreedomGG/Sindragosa#438]
Decription:
i got glory of the ulduar raider 310% mount but my swift flight form remains 280% shouldnt it go up to 310% now with all the other mounts too? only the rusted proto drake is currently 310% speed
How it works:
only 280% speed with from and other mounts
How it should work:
310% on all?
Source (you should point out proofs of your report, please give us some source):
https://www.mmo-champion.com/threads/801995-310-flying-and-Swift-Flight-Form

https://wowwiki-archive.fandom.com/wiki/Swift_Flight_Form
Flight Form and Swift Flight Form benefit from a paladin's Crusader Aura. Druids who have acquired a mount able to go 310% flight speed will now also go that speed while in this form.

**Comment by airness456** [comment]
Wrong, only flight form should scale to 310% if you got a 310% mount. Tooltip says 280% but flight form is scaling to 310% regardless. You can test it on your own. It is working fine.
