### ISSUE TITLE
[Store Item] Talent Mastery allows use of untalented talents

### ISSUE THREAD

**Issue by vCas** [GameFreedomGG/Sindragosa#439]
Description: By using the item "Talent Mastery" to change talents, I am able to use Divine Sacrifice, https://wotlk-twinhead.twinstar.cz/?spell=64205, even though I do not have it talented, in my current spec.

How it works: Using a macro (/cast Divine Sacrifice) I am able to use the talent, while not having it talented.

Spec Layout:
  Talent Mastery 1
    Prot Build 1 - Has Divine Sacrifice
    Prot Build 2 - Has Divine Sacrifice
  Talent Mastery 2:
    Holy Build 1 - Has Divine Sacrifice
    Holy Build 2 - Does not have Divine Sacrifice, but can still use it with a macro

How it should work: Should not be able to use it.

Source (you should point out proofs of your report, please give us some source):

**Comment by UltraNix** [comment]
@vCas Ping me on Discord: UltraNix#5638

**Comment by Whitemane-Calypso** [comment]
Solved.
