### ISSUE TITLE
[Core] No Friend Online/Offline Notification

### ISSUE THREAD

**Issue by Keoduen** [GameFreedomGG/Sindragosa#441]
Decription: There is no notification when a friend in logs.

How it works: Nothing thats the problem.

How it should work: You should get a notification in chat that ' playername ' has come online / went offline

Source (you should point out proofs of your report, please give us some source):
https://streamable.com/u9m0im
https://streamable.com/eq2oxz

**Comment by Lechy901** [comment]
Can confirm this is happening.

**Comment by Game-Freedom** [comment]
Bug confirmed.

**Comment by UltraNix** [comment]
I cannot reproduce it.
![obraz_2022-01-28_215501](https://user-images.githubusercontent.com/80540499/151620078-60ed89e2-3cf6-4b14-acb5-2d3003730cc6.png)

**Comment by Game-Freedom** [comment]
@UltraNix  I've tried it on PTR - added Hiki to friends, he logged in and it did not appear though.

**Comment by UltraNix** [comment]
@Game-Freedom Still don't know how to reproduce this one :(

**Comment by MrTide** [comment]
Happens to me everytime as well idk

**Comment by Loken-Whitemane** [comment]
Can confirm, possibly has to do with xfaction friends implementation, or could be a result of old changes? (ie if friends are re-added, this problem no longer occurs?)

**Comment by Keoduen** [comment]
happened afther we could add alliance too our horde friendlist. Removing them and readding doesnt solve the issue at hand
