### ISSUE TITLE
shaman lightning shield

### ISSUE THREAD

**Issue by nippari** [GameFreedomGG/Sindragosa#443]
Decription:
Lightning shield has no icd or too high proc rate on the server. Also should fix fire elemental totem report before new tiers
How it works:
procs constantly in raids atleast
How it should work:

Source (you should point out proofs of your report, please give us some source):
looking at lightning shield theres some bug on it too its triggering too much on the server when comparing to these videos and to sindragosas enh shamans. Not sure if there should be a icd? or proc chance is too high?

https://classic.wowhead.com/spell=905/lightning-shield in classic theres a 3,5sec cd and on some other wowhead link i found 1,5seconds
https://wotlk.evowow.com/?spell=324 here its 3 seconds
Apply Aura: Proc Trigger Spell 3 sec cooldown
https://tbc.wowhead.com/spell=324/lightning-shield

Patch 4.2.0 (2011-06-28): Lightning Shield and Water Shield can no longer be dispelled.;### Water Shield has had its internal cooldown reduced to 3.5 seconds, once again matching other shields. The amount of mana restored when Water Shield procs has been reduced by 50%.
World of Warcraft: The Burning Crusade/World of Warcraft: Wrath of the Lich King Patch 3.0.2 (14-Oct-2008): New ranks have been added of Water Shield, starting at level 20. (Level 20, 27, 34, 41, 48, 55, 62, 69)

https://www.youtube.com/watch?v=5yIZJKDF1Sg&ab_channel=Retslep
https://www.youtube.com/watch?v=zi8YZvneDEw&ab_channel=Retslep

https://youtu.be/5Df8hmRw_wQ?t=2439 sindragosa

**Comment by Viryll** [comment]
You linked wrong spells and talents. The lightning shield doesn't proc on hit as enha, it's the talent they have called Static Shock. 
https://wotlkdb.com/?spell=51526
As wotlkdb says GCD: 0, meaning it has no internal cooldown(same as wowhead). (you linked 3.5 second between attacker hiting you and geting hit twice with lightning shield orb not the talent. Also you compared Enhancement to double flametongue enhancement, which are 2 different builds. In your videos, non of the shammy used fel caps (which double the proc rate of the talent [intended by blizzard]). Anyway nothing to look here.

**Comment by nippari** [comment]
How is flame cap double proccing it intented? Is there proof to this

**Comment by Viryll** [comment]
Because the talent says "You have a 6% chance to hit your target with a Lightning Shield orb charge when you deal damage with melee attacks and abilities", which means your swing has 6% chance to trigger lightning shield. Adding flametongue and flame caps to your swings increases it to 18% making the number quiet noticeable on melee swings, but also lightning bolt and shock spells can proc it too. That's one of the reasons why haste is one of the best stats for shammy. Now whether flame caps should proc it or not is different case.

**Comment by Viryll** [comment]
The proc rate is fine out of:
171 melee
199 flametongue
14 fire novas
13 lightning bolts
6 fire shocks (damage over time doesn't proc it?)
8 earth shocks
22 stormstrikes
6 lava lashes
114 flame caps
which adds up to 539 and got 40 lightning shield procs, giving us about ~ 7,23% proc chance

**Comment by UltraNix** [comment]
As above - everything is okay with this spell. The cooldown is already 3 sec,
