### ISSUE TITLE
[General] Mobs aggro while sapped

### ISSUE THREAD

**Issue by jimrs** [GameFreedomGG/Sindragosa#447]
Description: When two mobs stand next to each other and you sap 1, then come out of stealth to kill the second, the first mob will become aggressive and even if you kill the second mob, you will be in combat. Happens in about 8/10 cases.

How it works: When two mobs stand next to each other and you sap 1, then come out of stealth to kill the second, the first mob will become aggressive and even if you kill the second mob, you will be in combat.

How it should work: mob should ignore you while sapped, even if his friend is dying

Source (you should point out proofs of your report, please give us some source): Westfall near Sentinel Hill, tried it at the Defias mobs.

**Comment by Game-Freedom** [comment]
https://streamable.com/2maalb

Confirmed. It does not happen everytime though, not sure what exactly it depends on. Maybe stealth detection.
