### ISSUE TITLE
[Druid][Spell] Clearcasting

### ISSUE THREAD

**Issue by tii86** [GameFreedomGG/Sindragosa#449]
Decription:
Clearcasting procs are being generated by spells that should not generate them.

How it works:
Clearcasting being generated by the following spells incorrectly:

Savage Roar
Tiger's fury
Prowl
Survival Instincts
shapeshifting (confirmed cat form/need to check others)

How it should work:

https://github.com/SunwellTracker/issues/issues/2500

Sums up the behavior pretty well, with examples for a few cases.

Source:

Tested a little bit comparing blackrock behavior vs. current server behavior.
See the sunwell issue for videos.

**Comment by Soufly** [comment]
https://www.reddit.com/r/wow/comments/exhip/the_real_406_ptr_patch_notes_no_clue_where/c1bppye/
some cata ptr thoughts

**Comment by gandalkk** [comment]
Barkskin works fine, also i doubt anyone is gonna use shapeshifting for ooc procs if its not high chance probably just a dps loss if u do that. But yeah sure some things still broken

**Comment by UltraNix** [comment]
(https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity)
As you can see, almost every Druid spell can trigger it.

**Comment by tii86** [comment]
![image](https://user-images.githubusercontent.com/57909970/152661657-a93acba1-2a0a-49e7-9587-da53272b6767.png)
