### ISSUE TITLE
[Ulduar][Boss][Aura] General Vezax Mark of the Faceless removes Shadow Crash Aura

### ISSUE THREAD

**Issue by scrublama** [GameFreedomGG/Sindragosa#450]
Decription:
https://gyazo.com/1e13d3c51755c5bc5bbc809c3a851503

How it works:
Whenever General Vezax casts Mark of the Faceless on a player it removes the Shadow crash debuff of other players whos standing inside it for 0,5 seconds.

How it should work:
Shadow Crash debuff aura should not vanish anytime you stand in it

Source (you should point out proofs of your report, please give us some source):

**Comment by scrublama** [comment]
Upon further inspection its not Mark of the Faceless causing aura to drop, its when two Shadow Crashes overlap and the elder one fades away

**Comment by scrublama** [comment]
Upon further inspection its not Mark of the Faceless causing aura to drop, its when two Shadow Crashes overlap and the older one fades away

**Comment by scrublama** [comment]
Upon further inspection its not Mark of the Faceless causing aura to temporarily drop, its when two Shadow Crashes overlap and the older one fades away

**Comment by Whitemane-Calypso** [comment]
I don’t really get this. The buff from the Shadow Crashes isn’t supposed to stack, so it’s working correctly if the newer one replaces the old one. Elaborate please

**Comment by Soufly** [comment]
just the old crash disappear,i dont see anything wrong on that video ?

**Comment by Whitemane-Calypso** [comment]
Doesn’t seem like a bug to me. I’ll reopen it if someone reports it again.
