### ISSUE TITLE
[Shaman] Elemental shaman tier 8 - 4 set

### ISSUE THREAD

**Issue by gandalkk** [GameFreedomGG/Sindragosa#451]
Decription: elemental 4 set is working incorrectly

How it works: i believe its stacking wrongfully
Doin more dmg than it should. 

How it should work:
 from wowhead :
I've only tested it with wow damage shower, but from what I've seen, it ticks for 800 damage once and then it's over. If one would crit before the 4 seconds would expire it will tick for another 800 damage and it'll be over again.

So this is basically "Your lightning bolt gives more 8% damage on crit". It sucks badly.

Source (you should point out proofs of your report, please give us some source):
https://www.mmo-champion.com/threads/639578-Tier-8-elemental-Itemization

**Comment by Soufly** [comment]
Its actually doing more damage than it should, but i need to make more research.

**Comment by Soufly** [comment]
https://twitch.tv/videos/1274567839 1h 50m 40 sec

**Comment by Soufly** [comment]
The dot should not stack like the old ignite from tbc,also lightning overload should never affect it.

**Comment by gandalkk** [comment]
Yes i mean it does too much dmg in my opinion too i edited a bit

**Comment by Soufly** [comment]
![WoWScrnShot_012622_221854](https://user-images.githubusercontent.com/36957911/151240605-091c2823-3972-47e8-b0ee-956a4ca7611b.jpg)
5% wtf,should be 1

**Comment by Soufly** [comment]
![WoWScrnShot_020522_210041](https://user-images.githubusercontent.com/36957911/152655150-e2b2f208-0036-4170-af85-e0048bf06e0d.jpg)
not live/fixed,still doing a lot of damage @MrTide
