### ISSUE TITLE
[Mage][Talent] Frosbite & Fingers of Frost

### ISSUE THREAD

**Issue by tii86** [GameFreedomGG/Sindragosa#455]
Decription:
frostbite and fingers of frost have a 15% chance to proc off freezing spells, and should proc together.

How it currently works:
Frost effects have a 15% chance to apply frostbite and a 15% chance to apply fingers of frost, but these effects can proc individually.

How it should work:
when you get a proc, fingers and frostbite should apply (assuming frostbite isn't DR or immune) @ 15% chance.

Source:
https://www.youtube.com/watch?v=OR-bIxvAzR0&ab_channel=PiotrMazurowski

Can see proper behavior on warmane.

**Comment by Soufly** [comment]
In PvP, the Frostbite effect is subject to [diminishing returns](https://wowwiki-archive.fandom.com/wiki/Diminishing_returns). It will also always proc along with [Fingers of Frost](https://wowwiki-archive.fandom.com/wiki/Fingers_of_Frost) if both are fully talented

**Comment by tii86** [comment]
@Soufly yes it should. but currently this is not a case of diminishing returns, sometimes you will get just the frostbite proc or just the fingers proc (frostbite not dr).

**Comment by Loken-Whitemane** [comment]
Looks like this is still an ongoing issue (Or possibly not pushed to live as of Sunday?) tested on live and still am getting procs individually.

**Comment by UltraNix** [comment]
@Loken-Whitemane Frostbite should proc off Fingers of Frost. But I don't see any source saying that Fingers of Frost should proc off Frostbite.

**Comment by UltraNix** [comment]
@Loken-Whitemane ??

**Comment by MrTide** [comment]
Similar issues on sunwell might be helpful 
https://www.youtube.com/watch?v=xLA-PjtXs5s 3:35
https://www.youtube.com/watch?v=bjpi1SPpseY 0:52
https://www.youtube.com/watch?v=l8p9kz4svQI 3:19

https://github.com/SunwellTracker/issues/issues/3177
https://github.com/SunwellTracker/issues/issues/2518
https://github.com/SunwellTracker/issues/issues/79

**Comment by Soufly** [comment]
That mmo comment is from patch 3.0.9..

**Comment by MrTide** [comment]
> That mmo comment is from patch 3.0.9..
went patch by patch no changes 
![image](https://user-images.githubusercontent.com/36106057/155795426-fdde55fe-df4d-4f65-beb6-bb2303e3308e.png)
