### ISSUE TITLE
[Ulduar][Flame Leviathan][Vehicles] You can forcefully change chopper driver.

### ISSUE THREAD

**Issue by Decard6** [GameFreedomGG/Sindragosa#457]
**How it works:**
When 2 players are already in a chopper third person is able to click on it. When they do it they replace the driver and driver is kicked from the vehicle.

**How it should work:**
You can't get into filled chopper.

**Source (you should point out proofs of your report, please give us some source):**
Honestly this is just a wrong vehicle behavior in general which doesn't happen with other vehicles. I doubt I can find any source of somebody trying to get into vehicle with 2 passengers already in.

**Comment by Whitemane-Calypso** [comment]
We can’t reproduce, if someone else complains it happens I’ll reopen the report.
