### ISSUE TITLE
[Warrior][Item] Spirits of the Lost - T7 4set

### ISSUE THREAD

**Issue by Dunderj** [GameFreedomGG/Sindragosa#460]
Decription: 4set Tier7 for warrior dps is bugged atm

How it works:
Only Rend procs it

How it should work:
Both Rend and Deep Wounds should proc it

Source (you should point out proofs of your report, please give us some source):
https://wotlkdb.com/?spell=60176

**Comment by UltraNix** [comment]
Works okay.
![obraz_2022-01-28_220425](https://user-images.githubusercontent.com/80540499/151621219-773b8c1e-028d-4823-bef8-b84cd213946a.png)
