### ISSUE TITLE
[Warrior][Spell] Charge/Intercept 

### ISSUE THREAD

**Issue by Kupcakez** [GameFreedomGG/Sindragosa#461]
Decription:
Charge/Intercept will work through textures and up z-axis

How it works:
Currently you can charge up z-axis (bottom of dalaran up to middle of arena even when not near the stairs), through pillars, and it also follows movement spells like shadowstep when used at the same time.

How it should work:
Intercept does not go up Z-axis and should leave you where the target originally was not where the movement spell put the target, thus, if a rogue shadowsteps the same time as intercept the rogue will be at your original location and you will be at the rogue's original location.

Source (you should point out proofs of your report, please give us some source):

**Comment by UltraNix** [comment]
@Kupcakez Could you record it?

**Comment by UltraNix** [comment]
@Kupcakez ??

**Comment by UltraNix** [comment]
No response - closing.
