### ISSUE TITLE
[Herbalism] Slave Pens flame cap farm ruined by bad mob aggro ranges

### ISSUE THREAD

**Issue by husker3011** [GameFreedomGG/Sindragosa#463]
Decription: Wastewalker Workers & Wastewalker Slaves & Coilfang Slavehandler have bugged aggro targeting to the point you cant reach the flame cap spawn without dying/shadowmelding to reset threat. On retail wastewalker mobs wont aggro you if you're above their level even if you walk over them yet on this server they get aggrod through reduced visibility of druids prawl almost every time you walk through. This means you can only pickup the flame cap once every 2 minutes on shadowmeld resulting in a completely broken economy for flame caps compared to other private servers (40g+).

How it works:
Chokepoint at Slave Pens entry has almost a 100% chance a Wasteland worker/Wasteland slave aggros to you.
How it should work: 
https://youtu.be/JHi83ryC2bM?t=51 passing through the slave+worker packs even in melee range of workers with 0 aggro.
https://youtu.be/rtCaMJP0FlI?t=23 similiar situation

Source (you should point out proofs of your report, please give us some source):
Millions of slave pen farm videos on youtube.

**Comment by Game-Freedom** [comment]
https://streamable.com/9mxfos

It did not happen every time I've passed through, but these mobs should not aggro if Naga npcs do not aggro.
