### ISSUE TITLE
Frost Trap not proccing Lock and Load on bosses

### ISSUE THREAD

**Issue by MagicNoodle** [GameFreedomGG/Sindragosa#464]
Description: Frost Trap not proccing Lock and Load on bosses

How it works: Frost Trap doesn't proc the Lock and Load talent when it's on bosses (dungeons too). I haven't tested Freezing Trap. It does appear to be working on the Heroic Training Dummy. It might be that it simply doesn't work on dungeon bosses, as I haven't raided yet.

How it should work: Frost/Freezing Traps should be giving a 100% chance to proc Lock and Load regardless of immunity flags I think. It worked like this on Warmane.

Source (you should point out proofs of your report, please give us some source): It's how it works on Warmane and this is a post on Wowhead during retail which seems to confirm it. [https://www.wowhead.com/forums/topic/survival-hunter-freezing-arrow-in-pve-rotation-129747](url)

**Comment by demetrzz** [comment]
https://ptr.wowhead.com/forums/topic/70835
https://outdps.wordpress.com/2009/03/12/trapdancing-part-3-grobbulus-gluth/
https://outdps.wordpress.com/2009/03/16/trapdancing-part-4-thaddius-noth-heigan/

Those posts proving that it shouldn't work on immunte targets (bosses), only on adds.

Also another private server even if its the most popular one is a bad source, it's very possible that it's bugged there and works properly here.

**Comment by Soufly** [comment]
''its how it works on warmane'' STFU !!!
