### ISSUE TITLE
Archmage Vargoth's Retreat

### ISSUE THREAD

**Issue by Raulfin** [GameFreedomGG/Sindragosa#465]
Decription:
In Archmage Vargoth's Retreat, a sub-zone of Dalaran 22.4,54.7, only accessable by using the 'The Schools of Arcane Magic - Mastery' book (43824) obtained from the achievment 'Higher Learning' (1956), the portal to retun to the ground is not active so the player is stuck at the top.
How it works:

How it should work:
a portal to return to the bottom of the KT tower should be in the room.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
There is no portal sir just use the book again and you will get port out.
