### ISSUE TITLE
Prophet Tharon'ja deletes warrior taunt keybinds and wipes stances

### ISSUE THREAD

**Issue by Weuyn** [GameFreedomGG/Sindragosa#466]
Decription:The last boss in Drek'Tharon Keep, on turning everyone back from skeletons into t heir normal form, will delete a warrior tanks taunt keybind and wipe their primary action bar as all their stances are disabled.

How it works:
Prophet activates skeleton phase, works fine
On exiting skeleton phase, Slaying Strike, taunt, Bone Armor and Touch of Life are all 'Unlearned', this is what probably wipes warrior taunt keybinds.
On exiting skeleton phase, warriors are dropped out with no stance active and therefore no binds on their primary action bar.

How it should work:
taunt keybinds shouldn't be wiped, stance should be remembered

**Comment by danniellos94** [comment]
Proof that shouldn't happen :

https://www.youtube.com/watch?v=y4xypcWd_oI 7:06+

**Comment by Game-Freedom** [comment]
https://streamable.com/76xaxp

Okay, it does seem like after getting back from Skeleton Form, you simply have your stance disabled - that is a bug indeed.

**Comment by Weuyn** [comment]
Maybe it's because I have it in a macro, but its not just the stances my taunt button is removed as well.

I have it on 1, on the primary action bar (the one the boss is messing with). The macro is a taunt/mocking blow castsequence with reset being the cd of mocking. It is unbound after the skeleton phase and I have to rebind it every time
