### ISSUE TITLE
Dragonmaw Race: Captain Skyshatter

### ISSUE THREAD

**Issue by Roebietrice** [GameFreedomGG/Sindragosa#467]
Decription: Quest called Dragonmaw Race: Captain Skyshatter is bugged.

How it works: The NPC is flying normally for the first 10% of the flight, but then gets stuck and randomly yeets to the moon.
At that point the quest automatically fails.

How it should work: He should fly his path and if you manage to follow him for a while the quest is completed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Game-Freedom** [comment]
https://streamable.com/51dbhm

Pathing of this NPC is bugged indeed -> he is moving weirdly and quest is failed if you follow him.
