### ISSUE TITLE
[PVP][Mage][Spell] WSG Blink

### ISSUE THREAD

**Issue by Glaedr990** [GameFreedomGG/Sindragosa#471]
Decription:
Apparently mage blink can go though terrain in WSG and it can be abused in many situations.
How it works:
I do not know fore sure. Was chasing mage in WSG, he was carrying the flag, we surround him and he was above the tunnel ( apparently he knows very well what he was doing). I guess he is facing the camera with double mouse button and just blink though the terrain.  Works on some walls in flag room not sure which on exactly.

How it should work:
Well, blink cant go though terrain, we all know this and the way it was abused was terrible

Source (you should point out proofs of your report, please give us some source):
I do not have photos as you can imagine was very hard to understand what actually is going on. I saw it on 31/12022 in wsg 500 around 18:10 - 18:15pm done by Undead mage Nokk (Avalon), he might have more information on how this exactly works

**Comment by Loken-Whitemane** [comment]
A lot of fixes for falling through map depend on where it happened, you can't fall through all areas of the map for example. Do you know where this happened on the map? I can test out the walls in flag room

**Comment by danniellos94** [comment]
I know this is blink issue but you may also check this :
On the start of the server on arathi basin on gold mine I could death grip the guy from the hill through the hill the guy was the warrior I think and he died inside the rock through the texture falling down. I don't play pvp much and I don't know if it works now correctly.

**Comment by UltraNix** [comment]
@Glaedr990 @danniellos94 ??

**Comment by danniellos94** [comment]
Waited 30 mins queue for arathi basin so I don't think it's possible to test for me, I dont have GM power on PTR to possibly check it out.

**Comment by UltraNix** [comment]
No response - closing.
