### ISSUE TITLE
Pendulum of Telluric Currents has no icd deals 10% + dmg

### ISSUE THREAD

**Issue by nippari** [GameFreedomGG/Sindragosa#474]
Decription:
https://wotlk-twinhead.twinstar.cz/?item=37264 has no icd
How it works:
Deals 10-15% of my damage on my shaman if i use it, isee People abusing it.. 
How it should work:
Should have icd of 45seconds 
Source (you should point out proofs of your report, please give us some source):
https://www.wowhead.com/item=37264/pendulum-of-telluric-currents?bonus=6710

**Comment by MrTide** [comment]
Its indeed proccing waay to often most likely missing internal cooldown
Based on wowhead comments it should be 45 sec
