### ISSUE TITLE
[Shaman][Item] Totem of Dueling

### ISSUE THREAD

**Issue by Viryll** [GameFreedomGG/Sindragosa#475]
Decription: The totem is supposed to provide only 60 haste to the user for 6 seconds, after using Stormstrike.

How it works: The totem provides 60 haste to the user as supposed to, but also gives 120 attack power from an unknown source.

How it should work: It should only provide 60 haste.

Source (you should point out proofs of your report, please give us some source): 

https://wowwiki-archive.fandom.com/wiki/Totem_of_Dueling

Also here's RAWR look at the stats it should provide:

![image](https://user-images.githubusercontent.com/98886485/152155293-048c30b6-cae8-47f3-9a38-6e52debe84c3.png)

**Comment by MrTide** [comment]
Multiple private databases shows that it should be there but there is no reason for it and there never been a talk about it, its probably a mistake
https://wotlk.evowow.com/?spell=60765
https://wotlkdb.com/?spell=60766

I will leave it to the devs to decide
