### ISSUE TITLE
[Hunter] Steady Shot

### ISSUE THREAD

**Issue by botwg** [GameFreedomGG/Sindragosa#477]
cast time is bad at level 4 it should be 1.5s and currently it is 2s 
How it works:
https://postimg.cc/9wV31Xgv
How it should work:
https://wotlkdb.com/?spell=49052
https://wotlk-twinhead.twinstar.cz/?spell=65867

**Comment by Godmatik** [comment]
Not a bug, 2.0 cast speed is correct for Wrath

![Steady](https://user-images.githubusercontent.com/37913400/152246509-8f300412-3749-4018-9ebf-542f24b90deb.png)
