### ISSUE TITLE
[Quest][Profession][Item] Gaffer Jacks

### ISSUE THREAD

**Issue by MageRazor** [GameFreedomGG/Sindragosa#478]
Decription: the fish never drops, i've been fishing up 300+ fishes and still no Gaffer Jacks

How it should work: just go to beach and buy a fishing pole and start fish and after 15-20 min you should have all 8 gaffer jacks, i have literally fished here for over 2 hours and not a single one. 0/8 Gaffers

**Comment by MrTide** [comment]
Can confirm
https://wotlk.evowow.com/?item=6717
Item is not dropping. tried different spots .. and nothing
