### ISSUE TITLE
[Core][PvP] PvP Flag Not Expiring

### ISSUE THREAD

**Issue by SynergieKaladin** [GameFreedomGG/Sindragosa#484]
Description: When in uncontested areas usually if you are /pvp off in ~5m you unflag for PvP and your name turns from Green to Blue and you are no longer able to be killed by opposing faction unless you attack them first or if you move to a contested area. This does not happen only for my character Kaladin

How it works: I ensure I am /pvp off. I teleport to Stormwind (Or any uncontested Alliance area) and wait 10m+ and I am still pvp enabled. I try to /pvp until I get the message: "You will be unflagged for PvP combat after five minutes of non-PvP action in friendly territory." I wait 10m+ and I am still PvP. This is tested as working on other characters.

How it should work: Ensure that you /pvp until I get the message: "You will be unflagged for PvP combat after five minutes of non-PvP action in friendly territory." Wait 5m in friendly territory and you are then unflagged for PvP

Source (you should point out proofs of your report, please give us some source):
07:01 Realm time
![WoWScrnShot_020522_160119](https://user-images.githubusercontent.com/99065536/152630774-c8e39166-0978-4b88-bba8-dffe75235767.jpg)
07:07 Realm time
![WoWScrnShot_020522_160704](https://user-images.githubusercontent.com/99065536/152630846-c60f110e-d2c4-4d71-952c-76a4d6afbaa2.jpg)

**Comment by MrTide** [comment]
I believe thats intended behavior please make sure you don't have any PVP related quest and you will be fine
Let me know how it goes

**Comment by UltraNix** [comment]
Cannot reproduce it. @SynergieKaladin more info needed.

**Comment by SynergieKaladin** [comment]
Not sure what else I can add to the ticket. My PvP flag does not clear. Ever. I have no PvP quests and I can sit in Stormwind for hours and the flag does not drop. You can see in the screenshots that I have toggled /pvp off and it does not clear.
Can you advise what other information I can get for you, please?

**Comment by UltraNix** [comment]
@SynergieKaladin Have you tried going outside Stormwind, e.g. Elwyn and then clear your PvP flag?

**Comment by MrTide** [comment]
> Not sure what else I can add to the ticket. My PvP flag does not clear. Ever. I have no PvP quests and I can sit in Stormwind for hours and the flag does not drop. You can see in the screenshots that I have toggled /pvp off and it does not clear. Can you advise what other information I can get for you, please?

I believe you most have some pvp related quest please make a ticket ingame and lets discuss this issue (please make sure to ask for me)

**Comment by UltraNix** [comment]
Cannot reproduce and no response - closing.
