### ISSUE TITLE
Fire elem not working 

### ISSUE THREAD

**Issue by jeffspicher** [GameFreedomGG/Sindragosa#485]
Decription:
Fire elem not working
How it works:
doesnt do anything
How it should work:
Hit cast switch target when dead.
Source (you should point out proofs of your report, please give us some source):
Video
https://youtu.be/I7ePur-vwQY

Why closing the issues when it's not fixed ?

**Comment by Godmatik** [comment]
You already made an issue and it was tagged as 'resolved', meaning it will be fixed on next server update.

https://github.com/GameFreedomGG/Sindragosa/issues/483

**Comment by jeffspicher** [comment]
yes i did but it was fixed at a moment my fire elem was working some days ago but now it does not at every summon he does nothing so its not fixed ...

**Comment by jeffspicher** [comment]
Since 3 days ago he is not working at all at any summon

**Comment by Godmatik** [comment]
Again - he labeled it as "resolved", however when devs fix things on a server it doesn't get pushed out instantly, you need to wait for them to do a server update.

**Comment by Afgann** [comment]
Fixes are not applied instantly, it will be applied on next update, there is no need to spam here.

**Comment by jeffspicher** [comment]
Sure i'll wait server update then hope it'll fix it ...

**Comment by jeffspicher** [comment]
When is next update ?

**Comment by MrTide** [comment]
I am not sure if its related to his issue.. his pet simply won't attack at all

**Comment by jeffspicher** [comment]
Hello is anything went live ? My fire elemental still not working...

**Comment by Godmatik** [comment]
Yes the fix is live, it seems like an issue for you alone, just did an Ulduar and all fire eles working perfectly from our shamans.

**Comment by jeffspicher** [comment]
ok so Will i just never have My own fire elemental working ?

**Comment by Godmatik** [comment]
Dunno mate, even with all addons off it's not working for you?

**Comment by jeffspicher** [comment]
Yes we tried many things with GM Tide but nothing seems to work. It does work on other shaman char but this one seems it will never work.....
