### ISSUE TITLE
[Warlock][Talent] Backdraft talent not working properly with Rain of Fire

### ISSUE THREAD

**Issue by Smorgarson** [GameFreedomGG/Sindragosa#487]
**Description:**
[Rain of Fire](https://wotlk.evowow.com/?spell=27212) channeling speed is not modified by [backdraft.](https://wotlk.evowow.com/?spell=47260)
Backdraft should reduce the global cooldown and the cast time of destruction spells by 30%.
Rain of Fire is a destruction spell that is modified by haste(haste Increases the speed that your spells cast so it has the same description as backdraft)
**How it works:**
Rain of Fire channeling speed is not reduced by Backdraft
**How it should work:**
Rain of Fire channeling speed should be reduced by Backdraft
**Source (you should point out proofs of your report, please give us some source):**
[Here](https://wotlk.evowow.com/?spell=27212) you can see what talents modify/affect the spell - backdraft is the first talent in the list.

**Comment by MrTide** [comment]
Backdraft is not suppose to reduce the channeling time its just for global CD in this case.
https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire
Similar discussion here
https://github.com/SunwellTracker/issues/issues/2809
