### ISSUE TITLE
[Core][Pathing] Crowd Control & Delayed Position Updating

### ISSUE THREAD

**Issue by tii86** [GameFreedomGG/Sindragosa#488]
Decription:
When an enemy player is crowd controlled, their position is occasionally not being updated until the end of the CC.

How it works:
If a target is stunned, feared, rooted, etc you can have issues where the hitbox of the player is in the wrong location. At the end of the CC, they will update and the player will appear to teleport.

For example: Priests fears a target. On occasion, the target will appear to be feared in place, not moving from the initial fear location. Once the fear is up, the target will teleport to another location.

Another example: A druid stuns a mounted player who is moving with pounce. At the location of the stun, the druid will be unable to hit the target, even though they appear to be right on top of them. Once the pounce duration is up, the target appears in another location.

How it should work:
Target's position should continuously be updated throughout the CC.

**Comment by Loken-Whitemane** [comment]
Does this happen with all CC? Every class etc?

**Comment by tii86** [comment]
I'm not sure if it applies to all classes, but I suspect it is. I think it is likely to happen when two events occur at the same time.
Ex: Pounce on charge ---> warrior position won't get updated till pounce finishes.
As for the conditions for the fear / poly path visibility to break I'm not sure. 
Additionally I have seen pets teleporting out of CC (nova / deep pet -->teleports somehow) --> maybe /petfollow + cc at same time cause same issue.
I do think it is a universal issue rather than a class specific issue.
