### ISSUE TITLE
[Raid][NPC] Zul'gurub Missing Boss

### ISSUE THREAD

**Issue by Taartampion** [GameFreedomGG/Sindragosa#489]
Decription: with Gurubashi Mojo Madness, you're able to summon on of this 4 bosses at the Edge of Madness  in Zul'gurub 10 man. After light off the brasero, a yellow cloud spanwed but that's all

How it works: light off the brasero with the Gurubashi Mojo Madness ans one of the 4 boss spwaned

How it should work: One of the 4 boss should have spawned

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Can Confirm event is not working at all.
