### ISSUE TITLE
Not being able to melee

### ISSUE THREAD

**Issue by sarc8201** [GameFreedomGG/Sindragosa#494]
Decription:
Should be able to melee
How it works:
Not being able to melee
How it should work:
Being able to melee
Source (you should point out proofs of your report, please give us some source):
https://imgur.com/a/za3SEI4
https://legacyplayers.com/viewer/20624/base?history_state=1

**Comment by Godmatik** [comment]
I reviewed several fights in your logs, and they do show auto attacks are being done. Sounds like your add-on just isn't recording it properly
