### ISSUE TITLE
[Ulduar][25m][Spell] Mimiron - Laser Barrage

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#498]
In phase 2 of the Mimiron encounter, there is a chance that Mimiron will begin doing "Spinning Up" in preparation of casting "Laser Barrage" ability, but will cancel it and resuming doing Rapid Bursts shots.

How it should work: Mimiron should never be able to cancel his "Laser Barrage" ability in either Phase 2 or Phase 4

https://www.wowhead.com/spell=63414/spinning-up
https://www.wowhead.com/spell=63293/p3wx2-laser-barrage

Clip that shows this happening:
https://clips.twitch.tv/AthleticScaryFoxPanicBasket-vf3CqMs4C19619Wk

**Comment by Loken-Whitemane** [comment]
Was this Normal or HC?

**Comment by Godmatik** [comment]
Happened in HC, I think I've seen it happen once on normal though a while back, but not certain
