### ISSUE TITLE
[Custom][Profession] Recipes Disappearing

### ISSUE THREAD

**Issue by DcLollipop** [GameFreedomGG/Sindragosa#50]
Learned recipes vanish after a racial change, if they are in the range >=(actual skilllevel + 1) & <= (actual skill+ racial bonus). They can't be relearned from the trainer.

Tested with: 
Gnome/Ingi -> racial change to Orc/Ingi

Not tested:
Recipes learned from scrolls
Major devolpment skills (journeyman, artisan, expert, ...)

**Comment by MrTide** [comment]
I tested this multiple time i dont see an issue
you need 360skill to learn Field repair bot schematic 
https://cdn.discordapp.com/attachments/448057838263336961/932984260791525417/unknown.png

changed my racial and lost 15 skill coming from gnomes
https://cdn.discordapp.com/attachments/448057838263336961/932984371508547594/unknown.png
and it was still there
Can you please provide more info
