### ISSUE TITLE
(DRUID) Fist Weapon transmog dissapearing 

### ISSUE THREAD

**Issue by areus1** [GameFreedomGG/Sindragosa#500]
Decription: I transmoged a main hand fist weapon on my main hand weapon (staff). When I use maul with the nogenfogger costume in bear form, the fist weapon disappears if you keep spamming maul. not a big deal but if it's a simple glitch to fix it would be cool

How it works: use noggenfogger to get skelly on bear druid with fist weapon transmog, keep activating maul on target dummy

How it should work: show fist wep all the time :)

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/VpRKuYC

**Comment by UltraNix** [comment]
First weapons are allowed for druids?

**Comment by Soufly** [comment]
https://www.quora.com/Can-Druids-use-fist-weapons-in-WoW

**Comment by UltraNix** [comment]
@areus1 Tell me exact what is that staff and fist weapon.

**Comment by areus1** [comment]
https://wotlk.evowow.com/?item=40280 staff
https://wotlk.evowow.com/?item=40383 fist weapon
