### ISSUE TITLE
Meta gem

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#502]
How it works:https://wotlkdb.com/?item=41398 is giving more than 3% damage on crit without multipliers.
How it should work:It should give 3% without multipliers.
Edit: i did my test only with hunter,u should check all of those ''3% more damage'' meta gems with other classes.
Source (you should point out proofs of your report, please give us some source):
Soon™

**Comment by styxel** [comment]
works fine on feral i think if my math is correct

rake 607 no meta, 5 less ap.
with meta 623

which equals like 2,6% damage or something

**Comment by MrTide** [comment]
I recommend using DrDamage addon for correct values.. i will try to do test later as well to make sure

**Comment by nippari** [comment]
Seems to work fine on feral imo too, easy to test with rake since it always does the same base damage other abilities have base damage of like 560-590 for example or % of your melee damage

**Comment by Soufly** [comment]
Yesterday was almost 8% damage increase on crit,now is working correctly... wtf ,close for now
