### ISSUE TITLE
Warrior Deep Wounds not triggering T7 4-piece set bonus

### ISSUE THREAD

**Issue by snootly** [GameFreedomGG/Sindragosa#503]
Decription: Deep Wounds debuff isn't triggering Spirits of the Lost from the T7 4p set bonus.

How it works: From what I've tested as fury warrior, only Rend triggers Spirits of the Lost. After about two hours of testing with just deep wounds as bleed, Spirits of the Lost didn't proc once. Deep wounds had about an 85% uptime through all the testing.

How it should work: According to various wikis, deep wounds should have a 10% chance to proc Spirits of the Lost.

Source (you should point out proofs of your report, please give us some source): 
Spirits of the lost info: https://www.wowhead.com/spell=61571/spirits-of-the-lost
See "Triggered By" section to see proc chance. 

Comment from 2009 patch 3.1.3 claims that deep wounds does proc Spirits of the Lost: https://www.wowhead.com/spell=60176/bleed-cost-reduction#comments

Here's an outline of my tests on a dummy:
1. Berserker Stance, deep wounds only (only auto attacks). 0 procs in 20 minutes, 88.2% deep wounds upime. Also just sat and auto attacked the dummy again later for about 50 minutes and no Spirits of the Lost procs; didn't note the deep wounds uptime, though.
2. Battle Stance (testing different variables), deep wounds only. 0 procs in 20 minutes, 81.5% deep wounds uptime.
3. Battle Stance, deep wounds and Rend. 41 procs in 20 minutes, 81.9% deep wounds uptime, 97.2% Rend uptime.

**Comment by Loken-Whitemane** [comment]
Unable to reproduce, please refer to picture below. Only had exact needed talents, no gear besides 4 pieces of T7 and a weapon, using only auto attack, got a proc in first 2 minutes of testing.
![image](https://user-images.githubusercontent.com/97129814/154166068-baf19d01-8890-4ddc-a9a9-7b5b519d27e3.png)

**Comment by snootly** [comment]
Testing with only T7 4p and two weapons (titan grip) in Berserker stance: No procs after 10 minutes.
Testing with only T7 4p and one weapon (still titan grip, just one weapon) in Berserker stance: No procs after 10 minutes.

Possibly a talent issue? Is there a PTR I can test with? I don't have the money to dual spec/respec just for this. 
My build: https://wotlkdb.com/?talent#Lhbf0fhZhxIoVMu0eRVkAo:MGo0zo 

I've attached my log file for this round of testing if that's useful at all.
[WoWCombatLog.txt](https://github.com/GameFreedomGG/Sindragosa/files/8075897/WoWCombatLog.txt)

**Comment by UltraNix** [comment]
Everything works okay.
![obraz_2022-02-18_152336](https://user-images.githubusercontent.com/80540499/154700323-1c829082-0103-4433-a76d-6b752e43c262.png)

**Comment by snootly** [comment]
I hate to be a pain in the butt, but it is _definitely_ not working. I'm still testing it on a dummy right now and no procs, even in raid I haven't gotten procs. You can see from the logs I posted earlier that I went at least twenty minutes without a proc, not to mention the 7+ hours I've sat and attacked a dummy with no procs. I'm not sure how you guys testing this, but I can't replicate your results at all.

Here's a video for more proof that I'm not getting procs: https://www.twitch.tv/videos/1303649720

If you'd like even more proof, we can set up a time to meet at a dummy and try getting procs. I'd love to show you in real time that this isn't working. 

Prior to recording the video, I was testing again with just a weapon and four pieces of T7 (no other gear):
Just Deep Wounds 3/3 and needed prerequisites (Imp. HS 3/3, Imp. Rend 2/2, Iron Will 2/3, Tactical Mastery 3/3, Impale 2/2): No procs after 30 minutes with 30.2% Deep Wounds uptime. I even retested this setup for another 30 minutes with the Synergie client and no addons to verify that it's not client-side. After these two tests, I recorded the video with the same setup.

I was going to test all of the other Fury talents, but I'm not getting procs with even the bare minimum talents, similar to what Loken did in his test (see Twitch video). I think it's fair to say at this point that it's not an issue with any Fury talents.

Could it be an issue with the gear? 2 of my T7 pieces are ilvl 213 and the other two are ilvl 200. I just bought what was available with emblems, so the ilvl is different.

**Comment by Manpower99** [comment]
can confirm that is it not working as fury , only rend is proccing it

**Comment by UltraNix** [comment]
@snootly Poke me on Discord: Ultranix#5638

**Comment by snootly** [comment]
> @snootly Poke me on Discord: Ultranix#5638

Just sent the friend request.
