### ISSUE TITLE
Auto Attack Not working Randomly

### ISSUE THREAD

**Issue by Uridiculous** [GameFreedomGG/Sindragosa#504]
Decription: Auto Attack not working. In order to get it to work I have to completely reboot wow.exe

How it works: It's random, no way to tell how it occurs.  Just randomly you can't use auto attack and no spell or ability will help you enable it.

How it should work: Right clicking on any apposing faction or npc and should be enabled

Source (you should point out proofs of your report, please give us some source): sorry I am old and don't know how to source code for you.

**Comment by styxel** [comment]
did u use noggenfogger elixir

**Comment by Uridiculous** [comment]
This only happens on my Paladin. And it also happens on my son's paladin. Only happens when we are spec'd as retribution. And its intermittent,  I only use ElvUI, pally power, carbonite, recount, healbot, dbm, atlas loot and decursive. My son uses dominos, carbonite, recount, dbm, pally power, postal, and atlas loot. Hope that helps. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 12, 2022 at 2:11 PM, Styxel team ***@***.***> wrote:   


did u use noggenfogger elixir

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Uridiculous** [comment]
And we haven't unlocked noggin fogger

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 13, 2022 at 5:41 PM, Dave ***@***.***> wrote:   This only happens on my Paladin. And it also happens on my son's paladin. Only happens when we are spec'd as retribution. And its intermittent,  I only use ElvUI, pally power, carbonite, recount, healbot, dbm, atlas loot and decursive. My son uses dominos, carbonite, recount, dbm, pally power, postal, and atlas loot. Hope that helps. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 12, 2022 at 2:11 PM, Styxel team ***@***.***> wrote:   


did u use noggenfogger elixir

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Loken-Whitemane** [comment]
Hey there, I am having a hard time recreating this one. Are you sure it isn't addon related? (IE still happening with addons disabled?)

**Comment by Uridiculous** [comment]
It's very intermittent,  even when on blizzard ui. Only happens when we are in retribution paladin spec and I noticed it happens more often when come back from a battleground to northrend continent. 

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 15, 2022 at 3:51 PM, ***@***.***> wrote:   


Hey there, I am having a hard time recreating this one. Are you sure it isn't addon related? (IE still happening with addons disabled?)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by UltraNix** [comment]
@Uridiculous Did you use some elixirs/potions?

**Comment by Uridiculous** [comment]
No potions no elixirs. 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 18, 2022 at 7:55 AM, ***@***.***> wrote:   


@Uridiculous Did you use some elixirs/potions?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Uridiculous** [comment]
I removed all addons and it happened on my feral druid. Only when que transfer from world to dungeon or world to bg, and only remedy is relogging 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 18, 2022 at 7:55 AM, ***@***.***> wrote:   


@Uridiculous Did you use some elixirs/potions?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrTide** [comment]
There were a lot of reports about such issues back in sunwell i believe pressing alt button couple times solved some of them.
Similar issues
https://github.com/SunwellTracker/issues/issues/2461
https://github.com/SunwellTracker/issues/issues/2406
https://github.com/SunwellTracker/issues/issues/2392
https://github.com/SunwellTracker/issues/issues/2391

**Comment by Godmatik** [comment]
There is a client bug that occurs when you alt tab out, tabbing back in sometimes messes things up and pressing 'alt' once fixes it. Possibly applies to this as well.

**Comment by UltraNix** [comment]
Screenshot with combat log/ video would be better to identify the cause of the problem.

**Comment by UltraNix** [comment]
@Uridiculous
