### ISSUE TITLE
T8 Set Bonus Bugged

### ISSUE THREAD

**Issue by David12sdf** [GameFreedomGG/Sindragosa#505]
Decription:Paladin T8 Set Bonus Bugged.

How it works: I got Helm of the Faceless TMOG on T8 Helm,and its didnt gave the set bonus 

How it should work:

Source (you should point out proofs of your report, please give us some source):
![WoWScrnShot_021322_013038](https://user-images.githubusercontent.com/95449014/153733421-6b26fe4e-f28c-4318-aecc-13eb9f9c7239.jpg)
![WoWScrnShot_021322_013125](https://user-images.githubusercontent.com/95449014/153733434-5033be72-e931-4eea-be3e-d471c980808d.jpg)

**Comment by Godmatik** [comment]
The transmog is a visual bug only, you still get the set bonus

**Comment by Whitemane-Calypso** [comment]
Closing it. What poster above said.
