### ISSUE TITLE
[PTR] 3.2.0 Content TOGC/TOC Emblems of Triumph

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#508]
Decription: Instance TOGC/TOC still giving emblem of conquest 

How it works: TOGC/TOC gives emblem of conquest

How it should work: TOGC/TOC should give Emblem of Triumph

Source (you should point out proofs of your report, please give us some source):
https://wowwiki-archive.fandom.com/wiki/Emblem_of_Triumph

**Comment by Godmatik** [comment]
I know it sounds obvious/silly, but is the PTR realm "set" atpatch 3.2? 

I remember the improper badges were dropping from Ulduar, only because Jimmy had the PTR still set at patch 3.0.8

**Comment by MrTide** [comment]
Resolved
