### ISSUE TITLE
Herald Volazj insanity not working

### ISSUE THREAD

**Issue by jozo-krstanovic** [GameFreedomGG/Sindragosa#51]
Herald Volazj in Ahn'Kahet the Old Kingdom casts Insanity, but it has no effect on the players.

**Comment by Game-Freedom** [comment]
It doesn't do anything when fighting solo, https://www.youtube.com/watch?v=SnoISHwu3-4.

**Comment by jozo-krstanovic** [comment]
The fight was done in a 5-man group, so it wasn't solo.
When he casted insanity, none of us were actually transfered to the insanity realm.
