### ISSUE TITLE
Pet XP in Dungeons

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#511]
How it works:Currently pets do not get any XP from dungeons.
How it should work:All 5 man dungeons should give XP,except VH trash packs.

**Comment by Soufly** [comment]
https://www.youtube.com/watch?v=Ab4yVYUeRCo outside of dungeons(working)

**Comment by UltraNix** [comment]
@Soufly What about xp in battlegrounds - pet should get any?

**Comment by MrTide** [comment]
Re-opening this players still complain about this issue

**Comment by UltraNix** [comment]
@MrTide More info about that dungeon: all party members were 80 lvl?
