### ISSUE TITLE
[Ulduar] Thorim Record timer not working properly 

### ISSUE THREAD

**Issue by syk7** [GameFreedomGG/Sindragosa#516]
Decription: This server has a feature where the fastest kills are tracked on a boss by boss basis. Usually these timers start when the boss is engaged and stops counting when the encounter is done

How it works: Thorim's timer doesn't work properly. Could be caused by a number of factors like, Hodir not "Dying" at the end of his encounter and keeps the timer going as a Hodir timer, there being 2 parts where you're in the thorim encounter but not attacking thorim leading to having no clear encounter start point, or the RP at the end of the encounter not being the encounter end point bleeding into the timer for another encounter (Freya most of the time). Could be any of these or all 3 that lead to Thorim not having a proper record timer

How it should work: This is a custom feature so there's no blizzlike version to base it off. How I assume it's intended to work is from the moment the hard mode timer start (or maybe, but unlikely, from the moment to hit the first enemy in the initial brawl) a timer starts counting to the moment thorim starts his end of encounter RP (He also doesn't die in the encounter)

Source (you should point out proofs of your report, please give us some source): I don't have a Screencap of this but there have been 10+ minute thorim speedkills announced which just isn't true

**Comment by Godmatik** [comment]
Confirmed, when you kill Thorim, it says "you have killed Hodir in X amount of seconds"

**Comment by UltraNix** [comment]
Encounter is not only fighting with boss. It's intended.
