### ISSUE TITLE
[Raids] PvP enabled after leaving group

### ISSUE THREAD

**Issue by Minrol** [GameFreedomGG/Sindragosa#520]
Decription:
Well as it says above PvP is enabled after leaving a raid group with alliance's and horde players.
How it works:
Get in a raid group with alliance and horde players. Leave the raid group after your done and boom PvP is toggled and you can attack / be attacked.
How it should work:
No PvP should be allowed in raids after dropping out of group

**Comment by MrTide** [comment]
Can confirm player is hostile
![image](https://user-images.githubusercontent.com/36106057/155236364-83b0533c-c3e9-4446-a912-5ceec548c50e.png)
