### ISSUE TITLE
Artisan Riding is not reduced with reputation (Honor Hold)

### ISSUE THREAD

**Issue by Jiokko** [GameFreedomGG/Sindragosa#521]
Decription:The Artisan Riding (Fast flying mount) skill that you buy to fly at 280% speed should be reduced to the following:
Friendly = 4750 gold
Honored = 4500 gold
Revered = 4250 gold
Exalted = 4000 gold

How it works: I was Revered and after that i got Exalted with Honor Hold and the amount of gold needed to buy it, was always 4500g, I cannot reproduce the bug with another character nor at another faction but i think it might happen to all. For Sure now it is with Honor Hold.

How it should work: If you are Friendly you should buy it with 4750g, if Honored you should buy it for 4500g, if Revered you buy it for 4250g and if Exalted you buy it for 4000g.

Source (you should point out proofs of your report, please give us some source):
![Artisan gold rep bug](https://user-images.githubusercontent.com/6665852/155343176-42d4f5bb-b964-48fb-a14b-65f6ff4695e8.jpg)

**Comment by Soufly** [comment]
Meh,why would u care tho??? The endgame content and flying is in northrens..

**Comment by Jiokko** [comment]
Firstly because we should report all bugs and secondly cause im exalted with Honor Hold to get it as fast as possible.

Αποκτήστε το Outlook για Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UltraNix** [comment]
No. As you can see, this NPC has Stormwind faction, not Honor Hold. With rep on Stormwind, it works okay.

**Comment by Jiokko** [comment]
you are right. i was confused cause of horde Thrallmar rep. Sorry for the post. Cancel it.
