### ISSUE TITLE
[Warrior Tier 7 DPS 4 Piece Set Bonus]  No longer proccing on Deep Wounds

### ISSUE THREAD

**Issue by balo-git** [GameFreedomGG/Sindragosa#524]
Decription:
The warrior Tier-7 DPS 4-piece set bonus is no longer proccing off of deep wounds. It still seems to proc off of rend.
It was definitely proccing off of Deep Wounds a week or two ago
Worth noting that I have used the transmog feature on 3/4 of the items.
I happen to be wearing the helm, shoulders, chest and gloves
It was already the case that the tooltip would not show the set bonus as active when using too many transmogged pieces, but this was strictly a visual bug and the set-bonus was working properly.

How it works:
Equip 4 pieces of Dreadnaught Battlegear
Put a bunch of crits into a target for awhile to proc Deeps Wounds, never see a single proc of the set bonus.

How it should work:
Equip 4 pieces of Dreadnaught Battlegear
Put a bunch of crits into a target for awhile to proc Deeps Wounds, eventually you should get some procs and gain the buff "Spirits of the Lost"

Source (you should point out proofs of your report, please give us some source):
5 minutes of cleaving + thunder clapping target dummies -> zero procs
Put up a few Rend debuffs -> a few procs

**Comment by snootly** [comment]
Old tickets for the same problem (should be pretty clear by now that this is not working, despite other tickets being closed): https://github.com/GameFreedomGG/Sindragosa/issues/503, https://github.com/GameFreedomGG/Sindragosa/issues/460

**Comment by UltraNix** [comment]
Duplicate.
