### ISSUE TITLE
[PTR] [Dungeon] 3.2.0 Content Trial of Champion 

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#526]
Description: Trial of Champion dungeon is not working couldn't even get through first phase/fight

How it works: Its not scripted correctly couldn't even get through first fight to test the rest
![image](https://user-images.githubusercontent.com/36106057/155733373-8e53fd19-c163-47ee-bbf4-fdb0322d092d.png)
the first champions just come to you and you can't do the events (if you stay far back event spawns all three factions but if you get close it will bug out again

How it should work: Requires developers attention i will post a video below (they should come in order and wait to fight you one by one)

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=7xEjH1mjzYA
Video from Aug 10, 2009

**Comment by balkai** [comment]
Similar thing occurs on The Black Knight, he aggros before he properly lands and does his RP, starts attacking and is unattackable by players. https://streamable.com/cw5fpg

**Comment by MrTide** [comment]
By the look of it the whole dungeon has issues and requires full rewrite 
![image](https://user-images.githubusercontent.com/36106057/155737383-68c20d4f-3eaa-4fac-93a3-dd023343ddb1.png)
![image](https://user-images.githubusercontent.com/36106057/155737444-b01afa66-3733-4d68-ade4-f0d10c747670.png)
