### ISSUE TITLE
immolate+conflagrate combo

### ISSUE THREAD

**Issue by Soufly** [GameFreedomGG/Sindragosa#529]
How it works:There is no delay  between the immolate and conflagrate cast.
How it should work:There should be.
Source (you should point out proofs of your report, please give us some source):
https://youtu.be/RsEgbFnAcBE?t=47 - how it should work.

**Comment by danniellos94** [comment]
True the delay should be about 0.4 second https://www.youtube.com/watch?v=KUizH_eVcuA 2:49+.
Good warlocks always cast chaos bolt after immolate and then conflagrate with 3x incinerates.

**Comment by MrTide** [comment]
This might be caused by missing prediction/delay core mechanic requires research on the whole case
