### ISSUE TITLE
Glyph of Scourge Strike

### ISSUE THREAD

**Issue by Jackers92** [GameFreedomGG/Sindragosa#531]
Decription:
Using a Scourage Strike with engraved Glyph of Scourge Strike to extend the diseases' timer on a target.

How it works:
When used on a target with diseases' timer > 14 secs it brings it down to 14 secs.

For example, when used instantly after applying the diseases, it brings it from ~19 sec left to 14 secs. It doesn't seem to account for the Epidemic talent.

How it should work:
Should extend by 3 secs up to 9 secs.

Source (you should point out proofs of your report, please give us some source):

Can be checked easily in-game.

**Comment by Naiters92** [comment]
Screenshots of that happening:

[https://imgur.com/a/bYzFs0C](url)
