### ISSUE TITLE
[PTR][Raid] 3.2.0 Content Onyxia 10man Draconic_for_Dummies

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#533]
Decription: Onyxia 10man Draconic_for_Dummies Required for quest Bind Draconic For Dummies which is required for scarab lord title quest line

How it works: Its not dropping on 10man mode

How it should work: Draconic For Dummies chapter 6 should drop from onyxia 10man
![image](https://user-images.githubusercontent.com/36106057/157097757-9295d1f1-ff28-4ca5-b674-5b2d24731154.png)

Source (you should point out proofs of your report, please give us some source):
https://wowwiki-archive.fandom.com/wiki/Draconic_for_Dummies_(6)

**Comment by balkai** [comment]
Seems to be fixed
![billede](https://user-images.githubusercontent.com/13424991/157973884-98eb49cb-9ddb-4b7e-981e-236394322346.png)
checked both 10/25

**Comment by MrTide** [comment]
> 

Looks like 10man version requires the quest but not the 25man version
Weird. Thanks
