### ISSUE TITLE
[PTR][Quest] 3.2 Scarab Lord; The Might of Kalimdor

### ISSUE THREAD

**Issue by balkai** [GameFreedomGG/Sindragosa#539]
Decription: Talk to Anachronos to receive the Scepter for the final part of the quest line

How it works: The quest does not give the player The Scepter of the Shifting Sands
![billede](https://user-images.githubusercontent.com/13424991/157986539-17112614-552f-466c-8424-04a2d31d9756.png)

How it should work: Should give the Scepter

Source (you should point out proofs of your report, please give us some source):
https://wotlkdb.com/?quest=8742
https://wotlkdb.com/?item=21175
![billede](https://user-images.githubusercontent.com/13424991/157986494-cc2c6533-ee5e-4e00-a9ca-6f2381996d16.png)

**Comment by MrTide** [comment]
We need a developer to take a look into this
its most likely related to npc not casting https://wotlkdb.com/?spell=25861
