### ISSUE TITLE
[Paladin] Glyph of Holy Light auto-learned on every paladin at level 2

### ISSUE THREAD

**Issue by balkai** [GameFreedomGG/Sindragosa#540]
Decription: Auto-learn teaches paladins Glyph of Holy Light at level 2

How it works: Get level 2, learn Glyph of Holy Light 
![billede](https://user-images.githubusercontent.com/13424991/158049925-75852a65-d449-4564-bfa2-5cbaede845f7.png)

How it should work: Don't learn 

Source (you should point out proofs of your report, please give us some source):
https://streamable.com/ykggs6
![billede](https://user-images.githubusercontent.com/13424991/158050018-a9c0006a-f92b-4162-a8cd-8ecaa24cc9aa.png)

**Comment by MrTide** [comment]
I am not sure how many paladins learned this but its confirmed
