### ISSUE TITLE
 Val'anyr item level

### ISSUE THREAD

**Issue by Nessy27** [GameFreedomGG/Sindragosa#550]
Decription:
With patch 3.2 (Call of the Crusade), the item stats of Val'anyr was increased from 239 to 245 to match the weapons from TOC. Right now Val'anyr still has its 239 stats.

How it works:
Val'anyr still has its 239 stats.

How it should work:
Val'anyr should have its 245 stats on 3.2 release.

Source (you should point out proofs of your report, please give us some source):
https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0
Val'anyr, Hammer of Ancient Kings: This item's stats and level have been increased to match the power level of healer weapons coming from the Coliseum 25-person normal difficulty instance. In addition, each time Val'anyr is equipped, Blessing of Ancient Kings will be placed on a 45-second cooldown before it can occur.

https://static.mmo-champion.com/mmoc/images/news/2009/july/valanyr32.jpg

**Comment by MrTide** [comment]
Hello, You need to delete your cache folder and relaunch the game to see the right value
