### ISSUE TITLE
Raging Deathbringer Proc chance is too low

### ISSUE THREAD

**Issue by TheRailgun** [GameFreedomGG/Sindragosa#551]
Description:

Sorry if this is a waste of time, or not easily fixed. Feel free to close the ticket if that is the case.

from the forums back from original wotlk it seems like this had a 5% proc chance, or 1/20 hits. 

How it works:

I have tested for 5~ minutes a few times on target dummies along with in raids and gotten about 0.5%-0.8% proc chance or 1/200
5/400 melee hits and this should work on some spells to according to old wiki so more like 5/600~

How it should work:

I think maybe this was implemented with an extra 0 in the proc chance modifier

Source (you should point out proofs of your report, please give us some source):

https://www.wowhead.com/item=49500/raging-deathbringer#comments
![image](https://user-images.githubusercontent.com/14112639/160225164-b1f69d2b-ad59-4155-9916-c4113cd9cc47.png)
![image](https://user-images.githubusercontent.com/14112639/160225170-ecc47875-b5a3-4d7f-ac87-dbec43b443f2.png)

**Comment by Soufly** [comment]
https://www.mmo-champion.com/threads/670120-Raging-Deathbringer 
scales with haste,5% chance.

**Comment by UltraNix** [comment]
Tested with 0 haste.
Weapon speed - 2.70
Proc chance = 2.70 * 1.8 = 4.86%
![obraz_2022-04-01_111404](https://user-images.githubusercontent.com/80540499/161233642-3d36cff1-a584-4984-bf9d-f01e69410655.png)
13/298 = 4.36%
I see no bug here.
