### ISSUE TITLE
[PTR] 3.3.X Content Festergut gas Cloud

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#569]
Decription: Festergut gas Cloud animation is not showing up

How it works: gas cloud is not working as intended animation is not showing up

How it should work: it should fill the room with gas and damage the raid with brown animation

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=ziBktQHYsRo

**Comment by danniellos94** [comment]
Each inhale blight cast festergut  should eat 1/3 of the gas so the room should be more visible each cast. Dont fuck it up it was bugged on whitemane.
