### ISSUE TITLE
[PTR] 3.3.X Content  Malleable Goo Professor Putricide

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#570]
Decription: Professor Putricide is not casting  Malleable Goo 

How it works: Professor Putricide is not casting  Malleable Goo

How it should work: Professor Putricide should cast Malleable Goo

Source (you should point out proofs of your report, please give us some source):
https://wowwiki-archive.fandom.com/wiki/Professor_Putricide

**Comment by danniellos94** [comment]
This happened on last phase.

**Comment by MrTide** [comment]
Further testing proved its casting it
