### ISSUE TITLE
[PTR] 3.3.x Content Marrowgar 10 hc charging into air

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#571]
Decription:
When marrowgar will charge into bonespiked target while bonestorming he will charge into air.
How it works:
When marrowgar will charge into bonespiked target while bonestorming he will charge into air.

How it should work:
Marrowgar should charge normal.
Source (you should point out proofs of your report, please give us some source):
I didn't make screenshot sadly.

**Comment by MrTide** [comment]
Hello Thanks for your report
I believe it happens when players get bone spike, although you can see yourself on top the spike other players see you inside spike as well
