### ISSUE TITLE
[PTR] 3.3.x Content geist patrol before rotface and festergut

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#572]
Decription:
PTR There should be a geist patrol before rotface and festergut
How it works:
Mobs are there but they are not patrolling at all.
How it should work:
They should patrol around.
Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Can confirm the pack on top of the stairs is not patrolling the area
