### ISSUE TITLE
[PTR] 3.3.X Content Kinetic bombs Blood Prince Council

### ISSUE THREAD

**Issue by MrTide** [GameFreedomGG/Sindragosa#573]
Decription: Kinetic bombs can be killed 

How it works: Kinetic bombs can be killed sometimes  for some reason their behavior is not right they took the damage and procced anyway

https://clips.twitch.tv/SilkyOnerousRadishDendiFace-OMPnLk9W8EnDINSU
![image](https://user-images.githubusercontent.com/36106057/163483922-4ecada13-33d7-4800-9ff5-c939202f27b7.png)

How it should work: Players should not be able to kill the kinetic bombs and they should react to damage

**Comment by danniellos94** [comment]
The linked damage is from ball of inferno flame that casts prince taldaram it's something else that melees need to run with to make it smaller and did less damage to a targeted caster. But yea you can see warlock on a clip killed kinetic bomb with a pet.
