### ISSUE TITLE
[Instance][Encounter] Not a priority! Fighting Deathbringer Saurfang crashes the server

### ISSUE THREAD

**Issue by jozo-krstanovic** [GameFreedomGG/Sindragosa#64]
Tested in 3 pulls.
Every pull the server would crash at approx. 15 seconds to 1 minute into the fight.

Could be unrelated, but is a high possibility since the server was stable before fighting him and after we stopped entering the fight.

**Comment by Game-Freedom** [comment]
crash wasn't related to this boss.
