### ISSUE TITLE
[Raid][NPC] Ulduar - Pyrite 

### ISSUE THREAD

**Issue by jozo-krstanovic** [GameFreedomGG/Sindragosa#66]
The spawns of Pyrite in the air are bugged, too few spawn at where the boss is, and there are no spawns in the pillars area.
Tested in 10man

**Comment by Godmatik** [comment]
Having tested in PTR, I confirm and I mentioned this also in the PTR discord. There are way too few pyrite spawns when tested in 25m. This will impact players pushing hard mode attempts.
