### ISSUE TITLE
[Dungeon][Low Prio] The Forge of Souls: Bronjahm Crash

### ISSUE THREAD

**Issue by DcLollipop** [GameFreedomGG/Sindragosa#68]
Bronjahm in Forge of Souls produces DCs at least for the running group. Timer seems to be a bit random, but fits roughly with the first expected 'Corrupt Soul' Cast (https://wowpedia.fandom.com/wiki/Bronjahm)

**Comment by Game-Freedom** [comment]
crash wasn't related to this boss.
