### ISSUE TITLE
[Death Knight][Quest][NPC] Massacre At Light's Point

### ISSUE THREAD

**Issue by Kirschie** [GameFreedomGG/Sindragosa#69]
After selecting the cart the NPC pulls you to the boat. He despawns on the deck, at this point you should be jumping out of the cart to use the cannons.

What is happening, after the NPC despawns you are left in the cart. You cannot exit the cart to progress the chain.

FIX: To fix the issue log out while stuck in the cart and log back in. You will be standing on the boat next to the cannons.

**Comment by MrTide** [comment]
I tested this out and i was able to get out without an issue
![image](https://user-images.githubusercontent.com/36106057/149621678-a328f88d-54b3-4526-b6f0-eaa7b0b4f8d2.png)
its most likely your addons blocking the action.
