### ISSUE TITLE
[Druid][Spell][Item] Clearcasting & Dragonbreath Chili / Stormchops 

### ISSUE THREAD

**Issue by foxeelol** [GameFreedomGG/Sindragosa#70]

**Comment by foxeelol** [comment]
Tested it a lot and those effects are not procing Clearcasting . Omen of Clarity ->Each of the Druid's damage, healing spells and auto attacks has a chance of causing the caster to enter a Clearcasting state. The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage, healing spell or offensive ability by 100%.

**Comment by styxel** [comment]
Thats good they shouldnt we dont need sunwell 2.0 clearcasting is working perfectly dont mess with it

**Comment by foxeelol** [comment]
Each of the Druid's damage, healing spells and auto attacks has a chance of causing the caster to enter a Clearcasting state. So i cant agree with you.

**Comment by styxel** [comment]
ok but its a consumable not druids damage or spell, is there any proof that it should work like this.

**Comment by gandalkk** [comment]
@Loken-Whitemane 

https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity

Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.

**Comment by nippari** [comment]
kinda what wowwiki says

**Comment by UltraNix** [comment]
@nippari I don't know if it's live. It's fixed on repo. I think it's gonna be live with the next update.

**Comment by Soufly** [comment]
https://github.com/SunwellTracker/issues/issues/3136

**Comment by styxel** [comment]
Think this was because stormchops had no cd and is an "aoe" they fixed it Though

**Comment by gandalkk** [comment]
Yes its 8 second gcd here on schops

**Comment by nippari** [comment]
@UltraNix seems fine so far but shapeshifting procs ooc now for some reason : /

Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.

**Comment by Godmatik** [comment]
Please reopen and look into this again, as said above literally everything procs omen of clarity now and it can be heavily abused, not sure what you changed but it should be reverted.

**Comment by UltraNix** [comment]
Please do not comment on closed issues.
