### ISSUE TITLE
[Dungeon][NPC] Deadmines - Mr. Smite

### ISSUE THREAD

**Issue by DcLollipop** [GameFreedomGG/Sindragosa#71]
Mr. Smite can be attacked during his weapon changing animation/ run towards the chest. As intended (https://wowpedia.fandom.com/wiki/Mr._Smite)

Further testing necessary what happens, if you trigger his P3 during the animation for the switch between P1 to P2. Update: Behaviour for triggering P3 in his run during P1: Casts the stomp stun again + fast switch to his set from P2 (dual axe), without further running.

Shouldn't be much of a problem for regular runs on that intented level, could lead to odd behaviour in boosted runs.
Pathing itself looked good. Pulled him up to Edwin Van Cleef and he used the ramp on his way down and back up.

**Comment by MrTide** [comment]
Yes player is right
So basically all we need to do is to make sure players can't hit him until he finishes his script and switches his weapons.
