### ISSUE TITLE
[Dungeon][NPC][Pathing] Deadmines - Defias Overseer

### ISSUE THREAD

**Issue by DcLollipop** [GameFreedomGG/Sindragosa#72]
Encountered a mob that didn't reangage after he finished his fleeing animation. Produced a similar behaviour on a ranged mob. Roughly 1 in 50-100 mobs.
![WoWScrnShot_110821_174106](https://user-images.githubusercontent.com/41908370/140782489-4dbd0ef9-09ec-423f-a02f-35b574082f0a.jpg)

**Comment by MrTide** [comment]
Can't reproduce this bug i tested all of them and didn't find an issue

**Comment by UltraNix** [comment]
Cannot reproduce and no response - closing.
