### ISSUE TITLE
Herald Volajz in Ahn'Kahet

### ISSUE THREAD

**Issue by demetrzz** [GameFreedomGG/Sindragosa#73]
Description:
Did a run where Herald Volajz casted insanity multiple times but it didnt go off and we killed him without being phased to fight mirror images.

How to reproduce:
Pull a boss and down his hp until he starts to casts Insanity.

How it should work:
After Insanity cast finished players should be phased to fight 5 mirror images.

**Comment by jozo-krstanovic** [comment]
I already posted this and they put it as invalid because they thought I was fighting it solo.
I can confirm this is a bug for a 5-man party.
