### ISSUE TITLE
[Mage][Talent] Prismatic Cloak & Invisibility

### ISSUE THREAD

**Issue by mavrt** [GameFreedomGG/Sindragosa#78]
**Issue:** Invisibility [with Prismatic Cloak specialization] does not always nullify spells that are airborne. 
Tested with Deathcoil and Chaos bolt. Worked roughly 50% of the times with Deathcoil and 1 out of 5 with Chaos bolt.
Video:
https://user-images.githubusercontent.com/94023508/141031164-48556010-dd4c-42c2-8a23-e7ee387b1456.mp4

**How it should work:** When a spell is airborne  (e.g Deathcoil, Chaosbolt), using invisibility with the "Prismatic Cloak" should nullify the spell (provided the caster doesn't have detection of some sort).
Video at 0:21 as proof: https://stream.warcraftmovies.com/streams/apTpcfpCszUC_web_hq.mp4

**Comment by MrTide** [comment]
Well going invis with mage does nullify one incoming single target spell from the enemy and also you will lose your invisibility it has nothing to do with Prismatic Cloak
![image](https://user-images.githubusercontent.com/36106057/149623434-2164a573-956b-4b61-a42a-cd5eb0b0fefa.png)

**Comment by UltraNix** [comment]
Cannot reproduce and no response - closing.
