### ISSUE TITLE
[Druid] Eclipses not proccing at all

### ISSUE THREAD

**Issue by Foxypaw** [GameFreedomGG/Sindragosa#80]
The issue:
So I just crit with SF on a Dummy target and i didnt get Solar Eclipse
Same goes for Lunar, i just spammed like 30 Wraths and didnt proc it.
How it should work:
SF crit should 100% give you Solar Eclipse
Wrath crit has 60% to give you Lunar Eclipse

Video proof: https://youtu.be/j9AznJhWhaE

**Comment by Sajaqtx** [comment]
Same here, Eclipse available, 1 crit no proc

https://imgur.com/a/zY5dIKY
