### ISSUE TITLE
Totem of Wrath stacks with Demonic Pact (Ele shaman + Demo warlock SP buff)

### ISSUE THREAD

**Issue by hexmonkey123** [GameFreedomGG/Sindragosa#83]
Totem of Wrath - gives 280 spell power
Demonic Pact - 10% of Warlock's current spell power

How it works on PTR:
1. Place totem of wrath
2. Make sure you have less than 2800 spell power on warlock
3. Send pet to attack a target for DP proc
4. Check spell power - it will be double stacked by both totem and DP

How it should work:
1. Place totem of wrath
2. If warlock's spell power is lower than the totem (280) only one should be applied - whichever has the higher value. Not both.
3. If a warlock has 2800+ SP totem of wrath will be overwritten by DP.
4. If a warlock has less than 2800 SP, Totem of wrath is superior to DP so it overwrites DP.

![link github](https://user-images.githubusercontent.com/92916943/141457113-14abea56-1d70-42fd-90ab-90e894e02615.jpg)

**Comment by kinh99** [comment]
5. If a Totem of Wrath is placed before the pet crits an extra +28 sp is added to the next DP. Until being removed by the higher DP, Totem of Wrath works as a buff increasing the base SP of the warlock by 280 so it does count in the next DP that removes the 280 Totem of Wrath buff but gains the 10% of it ^^ I hope it is clear and understandable! :D
