### ISSUE TITLE
[Dungeon][NPC] Wailing Caverns - Naralex

### ISSUE THREAD

**Issue by Kedlar** [GameFreedomGG/Sindragosa#85]
On naralex first three snakes can one shoot tank no matter what you do , we try 3 times and these hapen all the time

**Comment by MrTide** [comment]
Players are correct npc is hitting waay too hard for a lvl 15 dungeon.
Deviate Moccasin npc ID 5762
Boss : Mutanus the Devourer ID 3654
Reducing their damage should solve the issue

Similar issues here
https://github.com/SunwellTracker/issues/issues?q=Mutanus+the+Devourer
