### ISSUE TITLE
[Profession][Item] Enchanting - Lesser/Greater Magic Essence

### ISSUE THREAD

**Issue by Grahoss** [GameFreedomGG/Sindragosa#91]
Lesser/Greater Magic essence cant be obtain from disenchant. Cant level up my enchanting cuz of this, i disenchant like 50-60 items and got 0 lesser magic essence, the drop rate for this item is soo rare or dont drop cuz i dont drop even one, ppl in world chat got the same problem

**Comment by skiller94** [comment]
Same here, you have to go to enchanting vendor and buy these to be able to continue leveling enchanting. Rip server first.

**Comment by Raulfin** [comment]
i had no issue getting them from weapons, but the rate seems way off on armor.
Armor should have an 80% dust and 20% chance to give essence, but I only got 1 from 200-300 armor de's.
Weapons should have 20% on dust and 80% on essence.

**Comment by kohahahu** [comment]
im de'sing items from lvl 1 to 40 and didnt get any essence

**Comment by UltraNix** [comment]
Should be okay now.
