### ISSUE TITLE
[Custom] Shared Quest Loot Missing

### ISSUE THREAD

**Issue by SushiWoW** [GameFreedomGG/Sindragosa#92]
Demonic Rune Stones from https://tbc.wowhead.com/quest=10144/disrupt-their-reinforcements aren't working properly for shared quest loot, the NPC shows sparkly and the other player is able to loot the mob, however it contains no items.

This also happens for https://tbc.wowhead.com/quest=9361/helboar-the-other-white-meat, same issue, sparkly corpse, able to loot, however just reports as "Empty"

Will update for any other quests found while questing.

**Comment by MrTide** [comment]
Both drops without an issue you probably were in raid group.
![image](https://user-images.githubusercontent.com/36106057/149626951-1cc23618-277c-4573-8b7f-859d4b6a2595.png)
![image](https://user-images.githubusercontent.com/36106057/149626976-5d04bf16-c0a4-4b01-9473-53b294586ecd.png)
